### ISSUE TITLE
Don't set conceallevel and concealcursor globally

### ISSUE THREAD

**Issue by sid-6581** [OXY2DEV/markview.nvim#102]
**Have you done all of these?**

- [X] I am using the latest version of the plugin.
- [X] I have checked the wiki.
- [X] I have checked previous issues(even closed ones).

**Describe the bug**

`enableAll` contains the following lines of code, which overrides default or custom settings when `setup()` is run.

```lua
		vim.o.conceallevel = 2;
		vim.o.concealcursor = "n";
```

**Neovim version**
nightly

**Are you using a distro?**
No

**To Reproduce**
1.  Install `markview.nvim`.
2.  Check conceallevel and concealcursor

**Expected behavior**
Global settings shouldn't be modified.

**Actual behavior**
Global settings are modified.

**Comment by Kang-geophysics** [comment]
Still, Last set from ~/.local/share/nvim/lazy/markview.nvim/lua/markview/spec.lua line 274 force to set conceallevel.  I can directly change this in this script. But could you give an option?

**Comment by OXY2DEV** [comment]
That's not a *bug*, if a window has a `conceallevel` then any window you open from that will inherit the `conceallevel`.

That's just how windows work.

**Comment by Kang-geophysics** [comment]
I didn’t mean to say that this was a bug—I was just wondering if there could be more flexibility in that part. Sorry if it sounded like I was calling it a bug.

**Comment by OXY2DEV** [comment]
Not much can be done on my end since this would require something to track new windows which may unintentionally load file(increase plugin load time) even when you aren't using the plugin.

> Plus, this would need to handle edge cases such as help windows, changing filetype, `:e` etc. which would make this more complicated than it already is.

You could simply use an `autocmd` to reset the conceallevel.

>[!NOTE]
> This won't handle edge cases but should be good enough for general use.

```lua
--- I haven't tested this, so you might want to tweak it.
vim.api.nvim_create_autocmd({ "BufEnter" }, {
  callback = function (event)
    local buffer = event.buf;
    ---@type string[]
    local mkv_b = { "markdown" };

    --- If `markview.nvim` is loaded fetch the configuration option for filetypes.
    if package.loaded["markview.spec"] then
      mkv_b = spec.get({ "preview", "filetypes" }, { fallback = {} });
    end

    if vim.list_contains(mkv_b, vim.bo[buffer].ft) == false then
      ---@type integer[]
      local wins = vim.fn.win_findbuf(buffer);

      --- 'conceallevel' is a window option, so we must apply it to every window that is showing this buffer.
      for _, win in ipairs(wins) do
        vim.wo[win].conceallevel = 0;
      end
    end
  end
});
```
