### ISSUE TITLE
idk what I'm doing wrong, it's not rendering most things

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [OXY2DEV/markview.nvim#103]
**Have you done all of these?**

- [x] I am using the latest version of the plugin.
- [x] I have checked the wiki.
- [x] I have checked previous issues(even closed ones).

**Describe the bug**
title

**Neovim version**

```bash
nvim --version
# Output
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Are you using a distro?**
No

**To Reproduce**
Steps to reproduce the bug:

1.  Install `markview.nvim`.
2.  Open a `markdown` document.

**Configuration table**

If you have configured the plugin then you **must** share your config.

```lua

-- MarkView --
local markview = require("markview");
local presets = require("markview.presets");

markview.setup({
    headings = presets.headings.glow_labels,
    hybrid_modes = { "n" },
    callbacks = {
        on_enable = function (_, win)
            vim.wo[win].conceallevel = 2;
            vim.wo[win].conecalcursor = "c";
        end
    }
});

vim.cmd("Markview enableAll");

```
https://imgur.com/a/leID0vq

list of all other plugins I have installed

nvim-tree.lua, venn.nvim, nvim-cmp, lualine, treesitter, tokyonight.nvim, nvim-spider, which-key.nvim, noice.nvim, telescope.nvim, telescope-undo.nvim, plenary.nvim, hydra.nvim

I know it's something I'm doing wrong, idk what it is, it was working a couple days ago, and I don't remember what I changed

thanks in advance guys

**Comment by OXY2DEV** [comment]
You config is fine. So, either the plugin isn't loading or something else is stopping it.

If you are using lazy check if the plugin is loaded or not.

**Comment by 4rtemis-4rrow** [comment]
nope, not lazy loading it

```lua
        {
            "OXY2DEV/markview.nvim",
            lazy = false,      -- Recommended
            -- ft = "markdown" -- If you decide to lazy-load anyway

            dependencies = {
                -- You will not need this if you installed the
                -- parsers manually
                -- Or if the parsers are in your $RUNTIMEPATH
                "nvim-treesitter/nvim-treesitter",

                "nvim-tree/nvim-web-devicons"
            }
        },
```

using the exact recomended installation from the readme, didn't even bother removing the comments

**Comment by 4rtemis-4rrow** [comment]
and according to lazy, it has been loaded at start

**Comment by OXY2DEV** [comment]
That's weird. Does changing mode do anything?

Or if you type something does anything happen?

**Comment by 4rtemis-4rrow** [comment]
no, and no

I tried normal mode, tried insert, visual, visual line, visual block, everything

how comes there is a bug affecting only me? this is genuinely weird

I also tried uninstalling markview and reinstalling it, thinking that something might have changed it's code locally, no effect

**Comment by 4rtemis-4rrow** [comment]
what's even weirder is that things like code blocks are being rendered appropriately, as can be seen from the screenshot

**Comment by OXY2DEV** [comment]
Well, then there's only one thing to do.

You gotta have to disable everything other than `markview` and see if it's caused by another plugin.

**Comment by 4rtemis-4rrow** [comment]
> > what's even weirder is that things like code blocks are being rendered appropriately, as can be seen from the screenshot
> 
> They are not actually. That's just what the `conceallevel` does.

intresting, thanks

**Comment by OXY2DEV** [comment]
Did you find what was causing the issue?

**Comment by 4rtemis-4rrow** [comment]
I wish, and if I did, I'd have posted a comment explaining it, and closed the issue

**Comment by OXY2DEV** [comment]
> I wish, and if I did, I'd have posted a comment explaining it, and closed the issue

You could just simple use `gcc` to comment the other plugin's config table and quickly check if something changes.

Or just paste `enabled = false` in all the plugin files(if you use plugins/something.lua)

**Comment by 4rtemis-4rrow** [comment]
> > I wish, and if I did, I'd have posted a comment explaining it, and closed the issue
> 
> You could just simply use `gcc` to comment the other plugin's config table(if you use `plugins.lua` or `lazy.lua`) and quickly check if something changes.
> 
> Or just paste `enabled = false` in all the plugin files(if you use `plugins/something.lua`)

I did the first method, I commented everything relating to any plugin out, even keymaps, left nothing except markview, and nothing, not a single line of markdown rendered

**Comment by OXY2DEV** [comment]
Well, remove everything in the `config` part. It's definitely doing something weird.

**Comment by HudsonMC16** [comment]
I ran into this issue also, and turns out it was because I didn't have an html grammar installed, which was weird. Run `:TSInstall html` and see if it starts working.

**Comment by 4rtemis-4rrow** [comment]
bruh why did that actually fix it, lol

thanks m8
