### ISSUE TITLE
Wikilinks Problem

### ISSUE THREAD

**Issue by andyl** [OXY2DEV/markview.nvim#104]
**Describe the bug**

Wikilinks are a link convention used for internal naviation.  The link referenced is surrounded by double square brackets.  For example `[[MyPage]]`. 

I use Wikilinks in my markdown text.  When I enable Markview, everything is OK - the outer square brackets are stripped from the wikilink, no problem.  When I disable Markview, the outer square brackets are not restored.  Toggling Markview on and off does not fix the problem. 

**Neovim version**

0.10.1 on Xubuntu 22.04

**Are you using a distro?**

No

**Configuration table**

I tried `links = { enable = false }` - it didn't work

**Comment by OXY2DEV** [comment]
This not done by the plugin. It is done by `tree-sitter`.

The plugin should set `conceallevel=0` to prevent this from happening so check what's your `conceallevel` after disabling the plugin.

**Comment by andyl** [comment]
After more investigation, the problem only seems to appear when I do `:lua Markview <enable|disable|toggle>All`.  If I omit the `All` modifier and just do `<enable|disable|toggle>`, things seem OK.    I can live with this, but I suspect there is a bug in here that may affect others.  This is hard to diagnose!
