### ISSUE TITLE
Possible to start disabled

### ISSUE THREAD

**Issue by willcl-ark** [OXY2DEV/markview.nvim#105]
I'm wondering if it's possible to start the plugin in disabled mode? I'm loading with Lazy, and have a keybind to toggle, but would prefer it to start disabled if that's an option (that I'm not seeing). Otherwise, perhaps it's a feature request :)

Thanks for the neat plugin!

**Comment by OXY2DEV** [comment]
Have you tried this?
```lua
-- Just in case it doesn't load before the command
require("markview").setup();

vim.cmd("Markview disable all");
```

Or you can just directly set `require("markview").state.enable = false`.

**Comment by OXY2DEV** [comment]
I am going to close this as you can do this.
