### ISSUE TITLE
Question/Request: Is there an option to not indent already indented multiline text

### ISSUE THREAD

**Issue by devboy** [OXY2DEV/markview.nvim#107]
I did not want to report this as a bug as it might not be one.

I use a markdown formatter which already indents multiline list items, then markview actually indents them even further resulting in the screenshots i posted.

Is there an option to handle this in the settings which I missed?

![Screenshot 2024-08-15 at 18 32 21](https://github.com/user-attachments/assets/df3148c5-8d6a-426f-abfd-06d6236ff82b)
![Screenshot 2024-08-15 at 18 32 13](https://github.com/user-attachments/assets/9891462c-61e3-4b0a-a00e-3ccc466ae623)

**Comment by OXY2DEV** [comment]
I am more curious about why the list items aren't indented by the formatter as most *actual* previewers don't care about the whitespaces.

> Is there an option to handle this in the settings which I missed?

There is not simply because there wasn't an easy way to check for that. But I will probably have to revise the logic to see if it's even possible.

**Comment by devboy** [comment]
> I am more curious about why the list items aren't indented by the formatter as most actual previewers don't care about the whitespaces.

I am using prettier with default settings here.

**Comment by OXY2DEV** [comment]
>[!Caution]
> This will not work with block elements(e.g. table, block quotes, code blocks etc.) as they can't have a high number of spaces before them.

![Screenshot_2024-08-18-15-36-40-061_com termux-edit](https://github.com/user-attachments/assets/15fe4dc7-f93b-4eb3-9718-51207b0791bb)
