### ISSUE TITLE
suggestion: make it work with LSP hover docs

### ISSUE THREAD

**Issue by vxpm** [OXY2DEV/markview.nvim#11]
this plugin is great, and it would be very useful if it could work inside LSP hover docs. i'm not sure how exactly it would work, but noice.nvim is able to do something similar - so it is definitely possible.

**Comment by OXY2DEV** [comment]
> this plugin is great, and it would be very useful if it could work inside LSP hover docs. i'm not sure how exactly it would work, but noice.nvim is able to do something similar - so it is definitely possible.

Sorry for the late reply.

By default, the plugin skips though buffer with `nofile` buftype.

You can change it by setting `buf_ignore = {}` in your setup.

Another thing is LSP hover windows have `wrap` in them. So you should disable it.

**Comment by OXY2DEV** [comment]
I will be closing this issue now.

Reasons:
- Markview.nvim can be made to work with hover docs by changing the `wrap` settings of hover docs and changing the value of `buf_ignore`.
- Wrapped lines are not supported by this plugin.

**Comment by Appalled** [comment]
> I will be closing this issue now.
> 
> Reasons:
> 
> * Markview.nvim can be made to work with hover docs by changing the `wrap` settings of hover docs and changing the value of `buf_ignore`.
> * Wrapped lines are not supported by this plugin.

Thanks for making such an awesome plugin.  I follow your guide and it only works after jumping to the hover floating window. Is it possible to render markdown just after activating the hover window?

press 'K'

![Image](https://github.com/user-attachments/assets/65584b3f-79d4-4d16-b1ab-e17e6ffdd6f6)

press 'K' again

![Image](https://github.com/user-attachments/assets/c7bf17fa-5365-48d0-8c86-3a0549022d93)

my config
```
{
        "OXY2DEV/markview.nvim",
        version = "*",
        lazy = false,

        -- For blink.cmp's completion source
        dependencies = {
            "saghen/blink.cmp",
        },
        opts = {
            preview = {
                enable = true,
                filetypes = { "markdown", "md", "rmd", "quarto" },
                ignore_buftypes = {},
                ignore_previews = {},

                modes = { "n", "no", "c" },
                hybrid_modes = {},
                debounce = 50,
                draw_range = { vim.o.lines, vim.o.lines },
                edit_range = { 1, 0 },

                callbacks = {},

                splitview_winopts = { split = "left" },
            },
            markdown = {
                list_items = {
                    enable = true,

                    indent_size = 1,
                    shift_width = 2,
                },
            },
        },
    }
```

**Comment by OXY2DEV** [comment]
> it only works after jumping to the hover floating window.

That's due to changes to when the plugin attaches. Before, `BufAdd` was used but now `BufWinEnter` is used(this was done to add text wrap support).

If you use `vim.lsp.buf.hover()`(`K`). Then you can use an autocmd to detect when the hover window is open and show the preview immediately.

Or you can use something like [this](https://gist.github.com/OXY2DEV/645c90df32095a8a397735d0be646452).

**Comment by Appalled** [comment]
> > it only works after jumping to the hover floating window.
> 
> That's due to changes to when the plugin attaches. Before, `BufAdd` was used but now `BufWinEnter` is used(this was done to add text wrap support).
> 
> If you use `vim.lsp.buf.hover()`(`K`). Then you can use an autocmd to detect when the hover window is open and show the preview immediately.
> 
> Or you can use something like [this](https://gist.github.com/OXY2DEV/645c90df32095a8a397735d0be646452).

Thanks, now the hover correctly calls markview for rendering. The only remaining issue is with the formatting of the documentation output from Python's LSP itself. I'll try to figure out how to resolve that. For now substituting '&nbsp;' for' ' is not enough.

![Image](https://github.com/user-attachments/assets/1d6e5628-84ef-4fc1-b42c-04ee7aac59c2)
