### ISSUE TITLE
No syntax highlighting in code blocks + seeing the backticks in them

### ISSUE THREAD

**Issue by iguanacucumber** [OXY2DEV/markview.nvim#110]
**Have you done all of these?**

- [x] I am using the latest version of the plugin.
- [x] I have checked the wiki.
- [x] I have checked previous issues(even closed ones).

**Describe the bug**
I am seeing backticks in code blocks ( inline or multiline ) when they should be hidden by the preview and there's no syntax highlighting in code blocks

**Neovim version**

```bash
nvim --version
# NVIM v0.10.0
```

**Are you using a distro?**
No

**To Reproduce**
Steps to reproduce the bug:

1.  Install `markview.nvim`.
2.  Open a `markdown` document.
3.  Go to a code block ( inline or mutiline )

**Configuration table**
i'm using the defaults
``` lua
{
  "OXY2DEV/markview.nvim",
  lazy = false,
  dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.icons" }
},
```

**Expected behavior**

in the screenshots from the README.md of this repo we can that there's syntax highlighting in the code blocks, and we can't see backticks in them:
![screenshot of a working markview.nvim](https://github.com/OXY2DEV/markview.nvim/blob/images/Main/plugin_showcase_landscape.jpg?raw=true)

**Actual behavior**
i can see backticks inside the code blocks and there's no syntax highlighting:
![screenshots of "broken" code blocks](https://github.com/user-attachments/assets/415216d3-eb56-4370-a7b4-9f82ad797392)

**Additional context**
1. Having 10 or 80 plugins loaded does not change anything. So this issue doesn't come from a conflict with another plugin.
2. i have the `lua`, `html`, `markdown` and `markdown_inline` treesitter parsers installed, as well as the `lua_ls` LSP installed.

**Comment by OXY2DEV** [comment]
Hiding ` isn't done by the plugin, it's done by `tree-sitter` & vim's `syntax files`.

So, either you have some config that changes it's behavior or have some `syntax` files that are overwriting the default ones.

> This can't be fixed by me as detecting `syntax` isn't really possible for the plugin.

**Comment by OXY2DEV** [comment]
I can see that the Tree-sitter parser isn't being loaded so try to see if there's something preventing it.

**Comment by iguanacucumber** [comment]
the parsers are loaded, i just forgot to enable hightlighting in the TS config:
``` lua
require("nvim-treesitter.configs").setup({
  highlight = { enable = true },
})
```
