### ISSUE TITLE
Missing HTML

### ISSUE THREAD

**Issue by AndreM222** [OXY2DEV/markview.nvim#111]
First of all incredible work.

- [x] I am using the latest version of the plugin.
- [x] I have checked the wiki.
- [x] I have checked previous issues(even closed ones).

**Describe**
For some situations I like to use some html stuff for the markdown typing like `<p>, <img>, <h1>, <details>, summary>`, etc. but does are still not supported

**Neovim version**
0.10.1

**Screenshots**
This are some examples
![image](https://github.com/user-attachments/assets/e09dfd63-7a01-4036-8f40-39ce94703d54)
![image](https://github.com/user-attachments/assets/73441a73-5c4b-4b55-ab0b-3a7eae9d544c)

**Comment by OXY2DEV** [comment]
Though this would be nice to add unfortunately, `html` is quite lax with it's syntax.

For example,
```html
<p>text</p>

<p>
text
</p>

<p>
text</p>
```

All do the exact same thing. So, I can't just render it as an inline element or a block element.

Another issue would be that `tree-sitter` does not identify individual tags. So, every single tag is just `(html_tag)` meaning recognizing tags is almost impossible.

Another issue would be `nesting`. If you are using `html` then you are most likely going to be using nested tags and they don't always work.

Plus, to render things I would have to first remove things(e.g. `<`, `>`) which means more `lua patterns` and it's not powerful enough to do that.

**Comment by OXY2DEV** [comment]
As a workaround to your issue you can use [this wiki page](https://github.com/OXY2DEV/markview.nvim/wiki/Html) to customize tags.

For example you can try something like this,
```lua
html = {
  tags = {
    default = { conceal = false, hl = nil },
    configs = {
      H1 = { conceal = true, hl = "MarkviewHeading1" }
    }
  }
}
```

It's not *perfect* but it should be a nice visual indicator.

>[!Tip]
> You may want to copy the original values too if you use them.

For `<summary>`, you can use a custom foldtext.

![Screenshot_2024-08-18-16-06-41-263_com termux-edit](https://github.com/user-attachments/assets/c8e36df3-3949-4a3b-be75-fe68fd350e3c)
