### ISSUE TITLE
cursorcolumn highlights the wrong column 

### ISSUE THREAD

**Issue by yangmillstheory** [OXY2DEV/markview.nvim#112]
**Have you done all of these?**

- [x] I am using the latest version of the plugin.
- [x] I have checked the wiki.
- [x] I have checked previous issues(even closed ones).

**Describe the bug**

https://github.com/user-attachments/assets/916059b1-15c5-46dc-9549-d8cac650fa0d

Note that this happens on lines even without Japanese characters.

https://github.com/user-attachments/assets/5e9b00f6-053e-4269-ba8e-9688ed632cae

**Neovim version**

```bash
┌─ [~/c/jp-tools] git:(master) ✗
└─➤  nvim --version                                                                                         [5:12:54 PM]
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
Run "nvim -V1 -v" for more info
```

**Are you using a distro?**
No

**To Reproduce**
Steps to reproduce the bug:

1.  Install `markview.nvim`.
2.  Open a `markdown` document.
3. `set cursorcolumn`. Pop in and out of insert mode.

**Configuration table**

```lua
local markview = require("markview");
local presets = require("markview.presets");

markview.setup({
  headings = presets.headings.glow_labels,
  list_items = {
    enable = true,
    shift_width = 2,
    indent_size = 2,
  }
});

vim.cmd("Markview enableAll");
```

**Expected behavior**
Cursor column should highlight the correct column.

**Actual behavior**
Cursor column is more to the right than it should be.

**Screenshots**
See above.

**Additional context**
E.g. other plugins that you use with this one.

**Comment by OXY2DEV** [comment]
That's a side effect of using `conceal`.

![Screenshot_2024-08-19-14-27-05-931_com termux-edit](https://github.com/user-attachments/assets/38506751-847b-4f0f-90a2-8d9cc746fa1a)

`cursorcolumn` shows the column on the actual text, not the one shown when the plugin is active.

You can either use `hybrid_mode` or just toggle the `cursorcolumn` using the `on_mode_change` callback.

**Comment by yangmillstheory** [comment]
Is there a way to apply `hybrid_mode` only to the current line? Right now it applies to groups of bullet points.

https://github.com/user-attachments/assets/4905d3f5-c0ea-4fb3-8f4e-347555d5b180

**Comment by OXY2DEV** [comment]
Unfortunately, no.

Since the whole point is to see what the structure of the document is so you don't end up doing things like adding 4 spaces instead of 2 because of seeing the preview.

```md
    ◈ Item 1
      - Item 2
^^^^^^ This won't work
```

**Comment by yangmillstheory** [comment]
I see, thank you. And thanks in general for this great plugin. It's solving a pretty difficult problem.
