### ISSUE TITLE
Changing mode breaks cocealing when `mode` is set

### ISSUE THREAD

**Issue by flexagoon** [OXY2DEV/markview.nvim#114]
**Have you done all of these?**

- [x] I am using the latest version of the plugin.
- [x] I have checked the wiki.
- [x] I have checked previous issues(even closed ones).

**Describe the bug**

**Neovim version**

```bash
NVIM v0.11.0-dev+599-g8df6736ca
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
```

**Are you using a distro?**
No

**To Reproduce**
Steps to reproduce the bug:

1. Install `markview.nvim`.
2. Set the `mode` field in the config to any value.
3. Open a markdown file.
4. Change to any mode except normal

**Configuration table**

If you have configured the plugin then you **must** share your config.

```lua
require("markview").setup({
    modes = { "n", "i", "no", "c" },
});
```

**Expected behavior**
If the mode is in the `modes` table, concealing is enabled, otherwise, it's disabled until you leave that mode

**Actual behavior**
Concealing gets disabled even when the mode is in the list, and it doesn't get re-enabled when you enter normal mode again

**Comment by OXY2DEV** [comment]
Are you talking about this?

![Screenshot_2024-08-20-08-05-12-897_com termux-edit](https://github.com/user-attachments/assets/798f85d4-b81c-4773-a071-aadc8e8ccc8e)

This has nothing to do with the `modes` as it's set using `callbacks`.

**Comment by flexagoon** [comment]
No, I'm talking about all rendering getting completely disabled

**Comment by OXY2DEV** [comment]
Fixed. Created new release.
