### ISSUE TITLE
[FEATURE REQUEST] What about adding some diagrams ?

### ISSUE THREAD

**Issue by Kazppa** [OXY2DEV/markview.nvim#116]
Hello, first of all great work and great plugin !

What do you think about supporting a diagram tool like mermaid ?
Do you think it would be technically doable to integrate a diagram as an image ?

**Comment by OXY2DEV** [comment]
[diagram.nvim](https://github.com/3rd/diagram.nvim) should be able to do that.

The reason why I don't want to add it to this plugin is,
A. It requires external tools.
B. I can't really test images in the terminal(Termux doesn't support images and monet is too slow for rendering images).
C. It's probably something a dedicated plugin(in this case `image.nvim`) should handle.
