### ISSUE TITLE
[Question/Feature request] Custom checkboxes

### ISSUE THREAD

**Issue by malko42** [OXY2DEV/markview.nvim#117]
Hello I tend to use non-standard checkboxes while taking notes (e.g. [~] for in progress or [o] for cancelled tasks).
Until now I was using [obsidian.nvim](https://github.com/epwalsh/obsidian.nvim/) to make them pretty but then I stumbled this beautiful plugin: thank you for your work, it really makes my notes enjoyable.

I had a quick look at the doc and code and I couldn't find a way to handle custom checkboxes.
I see [here](https://github.com/OXY2DEV/markview.nvim/blob/169faa8b99f06b5145a4114864210029fa2e84e0/lua/markview/parser.lua#L528) that you have a special case for [-] (to not treat it as a list item I suppose?)

How  difficult would it be to provide a configuration looking like this
```
checkboxes = {
    enable = true,

    checked = {
        text = "✔", hl = "TabLineSel"
    },
    unchecked = {},
    pending = {},
    custom = {
			{
				capture_group = "[o]",
				text = "󰩹",
				hl = "TabLineSel"
			}
		}
}
```
and have Markview handle those custom checkboxes ?

**Comment by OXY2DEV** [comment]
![Screenshot_2024-08-21-19-52-01-877_com termux-edit](https://github.com/user-attachments/assets/124f8f0c-e147-433b-92d2-1c6317f757e0)

**Comment by OXY2DEV** [comment]
Don't forget to check the [wiki page](https://github.com/OXY2DEV/markview.nvim/wiki/Checkboxes#-custom-checkbox-configuration).

**Comment by Chaitanyabsprip** [comment]
how do you get the cancelled checkbox? @OXY2DEV

**Comment by OXY2DEV** [comment]
> how do you get the cancelled checkbox? @OXY2DEV

```md
- [-] Cancelled
```
