### ISSUE TITLE
code block show abnormal in mini buffer width

### ISSUE THREAD

**Issue by nfwyst** [OXY2DEV/markview.nvim#120]
code line show abnormal that every line has extra blank line in preview mode when the buffer width is not big enough

**Comment by nfwyst** [comment]
<img width="849" alt="截屏2024-08-24 09 41 59" src="https://github.com/user-attachments/assets/14031057-9ae7-4cb4-be8d-cb3bfdd2676a">
<img width="817" alt="截屏2024-08-24 09 42 27" src="https://github.com/user-attachments/assets/567e37d5-4ed5-42dc-8938-a34cb6df0b99">

**Comment by OXY2DEV** [comment]
This has nothing to do with the plugin. That's just how `wrap` works.

**Comment by nfwyst** [comment]
Yes, thank you

**Comment by OXY2DEV** [comment]
Are you using `wrap`?

**Comment by mycf** [comment]
> Are you using `wrap`?

using wrap is ok, I just don't think that makes sense

It would be better to use the code below 

  vim.api.nvim_buf_set_extmark(bufnr, M.namespace, start_row + 1, 0, {
    end_col = 0,
    end_row = end_row - 1,
    hl_group = c.codeblock_highlight,
    hl_eol = true,
  })

**Comment by OXY2DEV** [comment]
Highlighting is done via `nvim_buf_add_highlight()`.

Are you sure that code works? It doesn't seem to be producing a different result.

**Comment by mycf** [comment]
yes,You can see 
Highlighting  is no width limit
<img width="1395" alt="image" src="https://github.com/user-attachments/assets/f89d2ff9-9299-40fa-b2b3-35976f1be44b">
<img width="769" alt="image" src="https://github.com/user-attachments/assets/feebb799-3dbe-405d-a718-5d2e2c96276b">
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/ed246c48-39ff-4b25-ad00-b5e8cce4bc59">
<img width="1409" alt="image" src="https://github.com/user-attachments/assets/e3432e85-056c-40e2-bbb8-a13b7cd2956b">

**Comment by OXY2DEV** [comment]
I don't this approach is correct.

As code blocks don't need to start from the 1st column.

Plus, this seems to break the highlighting of the lines inside.

---

You can always use the `simple` style for code blocks(if you don't care about the icons) which highlights the entire line.
