### ISSUE TITLE
Options to set different icons for external (http/https) and relative file links.

### ISSUE THREAD

**Issue by dzintars** [OXY2DEV/markview.nvim#121]
This should be more like an discussion.
Is there possibility to set different icon for the external links `[example](https://example.com)` and internal links `[my other note](other-note.md)`?

So that they result in:
![image](https://github.com/user-attachments/assets/0ed9fee0-3057-4095-8596-ac66011eaff0)

**Comment by OXY2DEV** [comment]
You can do something like this now.

```lua
hyperlinks = {
  custom = {
    {
       match = "%.md"
       icon = "📜 "
    }
  }
}
```

**Comment by dzintars** [comment]
WOAH! Thank you so much! I was not even expecting that much of involvement. 😲 💪 🎉

**Comment by mawkler** [comment]
@OXY2DEV Is it possible to overwrite a default icon for some `match` pattern?

For instance if I wanted to change the icon used in this built-in `match`?

```lua
{
  match = "https://(.+)$",
  
  icon = "󰞉 ",
  hl = "MarkviewHyperlink",
}
```

I tried adding it to to my `hyperlinks.custom` table, but it seems to still use the built-in icon.

**Comment by mawkler** [comment]
@OXY2DEV Do you think it could fall back to setting `hl` to `links.hyperlinks.hl` if no `hl` is set for a custom icon? Currently it seems to just not receive a highlight.

**Comment by OXY2DEV** [comment]
> @OXY2DEV Do you think it could fall back to setting `hl` to `links.hyperlinks.hl` if no `hl` is set for a custom icon? Currently it seems to just not receive a highlight.

Custom links now inherite values(e.g. icon & hl) from the default ones.

**Comment by mawkler** [comment]
Awesome, thank you!

**Comment by dzintars** [comment]
For anyone reading this after. This allows you to do all kind of neat things:
![image](https://github.com/user-attachments/assets/66d1702b-91ca-4382-90e3-f510bc680ddd)
Use [Nerd Fonts Cheat Sheet](https://www.nerdfonts.com/cheat-sheet) to find a nice icon.

P.S. I'm not an regex expert. :) Nor I'm willing to become one. 😄

**Comment by rodhash** [comment]
> You can do something like this now.
> 
> ```lua
> hyperlinks = {
>   custom = {
>     {
>        match = "%.md$"
>        icon = "📜 "
>     }
>   }
> }
> ```

Hello @OXY2DEV 

Would be possible to have this HL applied only to the icon? Or perhaps is there another approach for this?
```lua
              { match_string = "stackexchange%.com", icon = " ", hl = nil },
```


Thanks for this awesome plugin.

**Comment by OXY2DEV** [comment]
> > You can do something like this now.
> > ```lua
> > hyperlinks = {
> >   custom = {
> >     {
> >        match = "%.md$"
> >        icon = "📜 "
> >     }
> >   }
> > }
> > ```
> 
> Hello @OXY2DEV
> 
> Would be possible to have this HL applied only to the icon? Or perhaps is there another approach for this?
> 
> ```lua
>               { match_string = "stackexchange%.com", icon = " ", hl = nil },
> ```
> 
> Thanks for this awesome plugin.

Yes, you just add `icon_hl = "whateverYouWant"` to the table.

**Comment by rodhash** [comment]
Awesome! sorry didn't see this in the docs, works great

**Comment by OXY2DEV** [comment]
> Awesome! sorry didn't see this in the docs, works great

Pretty much all the inline stuff(e.g. code blocks, hyperlinks, images, emails etc.) have these properties,

- corner_left
- padding_left
- icon
- padding_right
- corner_right

- corner_left_hl
- padding_left_hl
- icon_hl
- padding_right_hl
- corner_right_hl

I just wasn't sure whether they were useful in normal circumstances which is why they are missing in the docs.

> They will be added to the docs in the next update though.
