### ISSUE TITLE
Hyperlinks are not clickable anymore

### ISSUE THREAD

**Issue by ragu-manjegowda** [OXY2DEV/markview.nvim#122]
**Have you done all of these?**

- [x] I am using the latest version of the plugin.
- [x] I have checked the wiki.
- [x] I have checked previous issues(even closed ones).

**Describe the bug**
Hyperlinks not available for mouse click.

**Neovim version**

```bash
nvim --version
# Output
v0.10.1
```

**Are you using a distro?**
No

**To Reproduce**
Steps to reproduce the bug:

1.  Install `markview.nvim`.
2.  Open a `markdown` document.

**Configuration table**

If you have configured the plugin then you **must** share your config.

```lua
require("markview").setup({
        modes = { "c", "n", "no", "v" },
        callbacks = {
            on_enable = function(_, win)
                vim.wo[win].conceallevel = 2;
                vim.wo[win].concealcursor = "n";
            end
        }

});
```

**Expected behavior**
`mouse click` should open url in browser

**Actual behavior**
No mouse click available

**Screenshots**
None

**Additional context**
None

**Comment by OXY2DEV** [comment]
Clicks are provided by Neovim. Not by this plugin.

So, unless you changed you terminal settings or neovim's settings it shouldn't be affected by this plugin.
