### ISSUE TITLE
How to set header align

### ISSUE THREAD

**Issue by hyawara** [OXY2DEV/markview.nvim#124]
![image](https://github.com/user-attachments/assets/38ea6716-2efb-4d4d-a2c9-f8c91c603c5f)

Is there a method to reset the title text and align it to the center?

**Comment by OXY2DEV** [comment]
Which type of heading?

```md
# Atx heading

Setext heading
----------------------------------
```

**Comment by hyawara** [comment]
> Which type of heading?
> 
> ```
> # Atx heading
> 
> Setext heading
> ----------------------------------
> ```

# Atx heading

**Comment by hyawara** [comment]
> Which type of heading?
> 
> ```
> # Atx heading
> 
> Setext heading
> ----------------------------------
> ```

```md
# Atx heading
```

**Comment by hyawara** [comment]
I have attempted to add spaces to the header icon in this manner, but I am uncertain about the length of the current text and unable to precisely center it

![image](https://github.com/user-attachments/assets/2b3d61e9-d607-4e98-8d3c-431f25fb0444)

![image](https://github.com/user-attachments/assets/4f4dd612-7e11-4f31-b209-2975ffccae34)

**Comment by OXY2DEV** [comment]
You can do this now.

```lua
headings = {
  -- The width of your statuscolumn, mine is 9
  textoff = 9,

  heading_1 = {
    style = "label",
    align = "center"

    -- Other options
  }
}
```
