### ISSUE TITLE
How to generate a horizontal line below the title?

### ISSUE THREAD

**Issue by hyawara** [OXY2DEV/markview.nvim#125]
How can I automatically generate a horizontal line below the title? Currently, for virtual text like the one I add, I achieve this through autocmd.

![image](https://github.com/user-attachments/assets/480cd183-e2c3-4e75-9ea4-95316fcb05f6)

code:

```lua
local ns = vim.api.nvim_create_namespace('markdown_title_ext_line')
local title_line = string.rep('-', vim.fn.winwidth(0))
local pattern = '^(#+.*%s)'
vim.api.nvim_create_autocmd({ 'BufEnter', 'BufWinEnter', 'TextChanged', 'TextChangedI' }, {
    group = vim.api.nvim_create_augroup('set_markdown_title_line_group', { clear = true }),
    pattern = { '*.md' },
    callback = function(args)
        local buf = args.buf
        vim.api.nvim_buf_clear_namespace(buf, ns, 0, -1)
        local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
        for i, line in ipairs(lines) do
            if line:match(pattern) then
                vim.api.nvim_buf_set_extmark(buf, ns, i - 1, 0, {
                    virt_lines = {
                        -- 每一行的文本是哪些
                        {
                            -- 每一行中，不同的文本块儿是哪些，可以使用不同的颜色显示
                            {
                                title_line,
                                'Comment',
                            },
                        },
                    },
                    invalidate = true,
                })
            end
        end
    end,
})

```

**Comment by OXY2DEV** [comment]
Only `setext headings`(headings that use `=` or `-`) get a border under them.

Not every renderer adds a border to the headings so it is not done by the plugin.

Also, adding virtual lines to the screen leads to text moving when switch between the raw text & render. This can be quite distracting.

**Comment by OXY2DEV** [comment]
Also, you do realize that you can simply use `tree-sitter` to add the border without using a pattern.

Tree-sitter should be significantly faster than manually matching lines.

**Comment by hyawara** [comment]
Thank you for your quick reply. I will try it. Thank you
