### ISSUE TITLE
header align bug

### ISSUE THREAD

**Issue by hyawara** [OXY2DEV/markview.nvim#126]
First open file, header like this:

![image](https://github.com/user-attachments/assets/40d86e66-3cd3-4cd6-b376-702049b627cd)

and after the buffer is switched again, the buffer becomes normal

![image](https://github.com/user-attachments/assets/f99cab7c-01af-4627-bb1b-ba22d7a88cd7)

header config:

```lua
            headings = {
                enable = true,
                shift_width = 0,
                textoff = 9,
                heading_1 = {
                    style = 'label',
                    align = 'center',
                    hl = 'CursorLineNr',
                    icon = '',
                    sign = '',
                    sign_hl = 'CursorLineNr',
                },
                heading_2 = {
                    style = 'label',
                    align = 'center',
                    hl = 'Character',
                    icon = '',
                    sign = '',
                    sign_hl = 'Character',
                },
                heading_3 = {
                    style = 'label',
                    align = 'center',
                    hl = 'DiagnosticInfo',
                    icon = '',
                    sign = '',
                    sign_hl = 'DiagnosticInfo',
                },
                heading_4 = {
                    style = 'label',
                    align = 'center',
                    hl = 'Identifier',
                    icon = '',
                    sign = '',
                    sign_hl = 'Identifier',
                },
                heading_5 = {
                    style = 'label',
                    align = 'center',
                    hl = 'Identifier',
                    icon = '',
                    sign = '',
                    sign_hl = 'Identifier',
                },
                heading_6 = {
                    style = 'label',
                    align = 'center',
                    hl = 'Identifier',
                    icon = '',
                    sign = '',
                    sign_hl = 'Identifier',
                },
            },

```

**Comment by OXY2DEV** [comment]
You don't happen to use a file-tree plugin, do you?

The plugin gets the width of the **current window**(as it's impossible to get the width of the window containing the buffer since multiple windows with various sizes can have the same buffer). So, if you opened it via some other plugin it will look like that.

**Comment by hyawara** [comment]
Yes, i use the neo-tree plugin.

I understand, thank you

**Comment by OXY2DEV** [comment]
It should work now. Can you check again?

**Comment by hyawara** [comment]
> @hyawara, It should work now. Can you check again?

Give me a second. I'll try. I'll get back to you

**Comment by hyawara** [comment]
https://github.com/user-attachments/assets/1f588c5f-8155-4ab1-8af7-567f641af318

I need to move it to make it work.

But it worked out. You were very efficient, thanks.

**Comment by OXY2DEV** [comment]
Does it work now?

**Comment by hyawara** [comment]
There are still some problems @OXY2DEV 


https://github.com/user-attachments/assets/5c848f0c-643c-4c39-93c3-911ac74dcff0

**Comment by OXY2DEV** [comment]
It should be fixed now.

**Comment by hyawara** [comment]
Do you know how to listen for buffer window size changes? I think it should be the problem.

https://github.com/user-attachments/assets/8a3ea436-8106-48fa-aa70-6b132f0d3076

**Comment by OXY2DEV** [comment]
`WinResized` won't be used by the plugin.

For example, you have a file opened in a window and hit `:vsp`.

Now, you have 2 windows containing the same buffer. Now if you resize one of them that window will have the correct alignment but the other window will have an incorrect alignment.

> There's no relation between `buffers` & `windows`. So, there's no good way to use `WinResize` to update the buffer.

---

Also, someone famous once said, "If you always have your file browser open, I have a lot of questions and the only important one is, 'Why?'"

So, there's no point in adding something for every *niche* case.

**Comment by hyawara** [comment]
Could you provide me with a copy of your nvim configuration for my reference?  thank you

**Comment by OXY2DEV** [comment]
[OXY2DEV/nvim](https://github.com/OXY2DEV/nvim)
