### ISSUE TITLE
Is there a way do ignore linebreaks?

### ISSUE THREAD

**Issue by dzintars** [OXY2DEV/markview.nvim#134]
I do use:
```lua
vim.opt.showbreak = '↪ '
vim.opt.linebreak = true
```
But if "feels" a little bit messy in some corner cases. See the images:

![image](https://github.com/user-attachments/assets/b202ac16-afe7-4303-b469-0f4796808243)

As you see, there is not much actual text. Just the link is pretty long.
When it gets rendered with MarkView, it keeps the line break:

![image](https://github.com/user-attachments/assets/dd7e3ae3-d457-4aaa-b4fb-1ee4102acecf)

Instead, I would expect, that break line gets ignored in this case. Automatically or by some setting.

**Comment by OXY2DEV** [comment]
The plugin only *hides* the text. The text is still there.

So, it makes sense why the line break is there. You can actually see that the text is still there if you use the `cursorcolumn` option.

I am not aware of any option that deals with this.

**Comment by dzintars** [comment]
I got you. Makes sense. OK. Closing. Tnx for the quick response.
