### ISSUE TITLE
Feature: option to position link icons at the start/end

### ISSUE THREAD

**Issue by mcchrish** [OXY2DEV/markview.nvim#139]
<img width="251" alt="image" src="https://github.com/user-attachments/assets/dbb53222-e28b-448a-8aad-82eb4d047289">

Makes for example a list of links + non-links look nicer.

**Comment by OXY2DEV** [comment]
You can already do this.
Just set the icon in either `corner_right` or `padding_right`.

Check the [docs](https://github.com/OXY2DEV/markview.nvim/wiki/Links#-link-configuration).
