### ISSUE TITLE
todo-comments, dont show in normal mode.

### ISSUE THREAD

**Issue by Landixbtw** [OXY2DEV/markview.nvim#14]
When in Normal mode TODO: FIX: WARN: etc. Dont show. The text is colored correct.
https://github.com/folke/todo-comments.nvim
![image](https://github.com/OXY2DEV/markview.nvim/assets/68870626/15891433-d14e-4cf3-a5aa-acb4b1171748)

EDIT: 
It should look like this (This is in insert mode)
![image](https://github.com/OXY2DEV/markview.nvim/assets/68870626/b4b744e6-ab29-43b7-8a4e-76354e37c4e1)

**Comment by OXY2DEV** [comment]
This will be fixed in the next update.

![Screenshot_2024-07-01-14-26-29-630_com termux-edit](https://github.com/OXY2DEV/markview.nvim/assets/122956967/974efc4d-fb71-4634-98a2-46b995a8610c)
