### ISSUE TITLE
Disable latex shoud be default

### ISSUE THREAD

**Issue by yadex** [OXY2DEV/markview.nvim#140]
![grim20240909-091432](https://github.com/user-attachments/assets/b9d4ea10-0f7f-49c0-81e0-6dff9870fede)
It's a markdown preview not a latex plugin, i think 99% of users don't need this feature.

**Comment by mmirus** [comment]
Agree, having this notice pop up every time I launch neovim is quite obnoxious.

@yadex why did you close this issue? Were you able to disable the notice somehow?
