### ISSUE TITLE
Conceal checkbox completely and not separately as bulletpoint and checkbox

### ISSUE THREAD

**Issue by kusnezoff-alexander** [OXY2DEV/markview.nvim#142]
**Describe the bug**

Currently a checkbox written as `- [  ]`/`- [x]`/... is rendered as if it was a separate bulletpoint and checkbox:

**Neovim version**

```bash
> nvim --version
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**To Reproduce**
Steps to reproduce the bug:

1.  Install `markview.nvim`.
2.  Open a `markdown` document.
3. Write some checkboxes

**Configuration table**

If you have configured the plugin then you **must** share your config.

```lua
   require("markview").setup({
	list_items = {
		enable = true,
		shift_width = 2,

		marker_minus = {"•"},
		marker_plus = {"•"},
		marker_star = {"•"},
		marker_dot = {"•"}
	},
	tables = {
		enable = true,
		use_virt_lines = true, -- so don't need to add spaces for table-outline to match inner text

		text = {
			{
				--    Main parts    Seperators
				"╭", "─", "╮",      "┬",
				"├", "│", "┤",      "┼",
				"╰", "─", "╯",      "┴",

				--    Alignment indicators
				--   Left   right     center
				"╼",     "╾",    "╴", "╶"
			}},
	},
	checkboxes = {
		enable = true,

		checked = { text= "", hl = "MarkviewCheckboxChecked" },
		unchecked = { text = "󰄱", hl = "@text.todo" },
		pending = { text = "󰰱", hl = "@text.todo" },
		custom = {
			{ match=">", text="", hl="@text.todo" },
			{ match="!", text="", hl="@text.todo" },
		}
	},

	-- use "Hybrid-Mode" for live-rendering
	modes = { "n", "i", "v", "V", "no", "c" },
	hybrid_modes = { "i" },

});

```

**Expected behavior**

All components of a checkbox `- [ ]` (bulletpoint *and* brackets) are replaced by the configured text:
![image](https://github.com/user-attachments/assets/2020b47a-0a20-4f0c-9056-6e624e3134d4)

**Actual behavior**

Only `[ ]` is replaced by the configured text, but I expect the complete checkbox (including the bulletpoint) to be replaced like this:
![image](https://github.com/user-attachments/assets/5929d693-b549-4aca-bd53-69810868bf2a)

**Comment by MunsMan** [comment]
@OXY2DEV is there an option to display the bullet point for checkboxes?
