### ISSUE TITLE
Add `min-width` to latex-codefences

### ISSUE THREAD

**Issue by kusnezoff-alexander** [OXY2DEV/markview.nvim#143]
It would be nice if the option `min-width` could also be set for latex-codefences (just like in codeblocks).

Example:
![image](https://github.com/user-attachments/assets/483a5b11-5524-43f2-8492-49a97242a62a)
 - latex inside `$$` takes up the whole width, while inside ``` it takes up the width set by `min_width` (=70 in my case)

**Comment by OXY2DEV** [comment]
This is not possible at the moment.

Unless `Neovim` allows getting the width of the line based on the shown contents(instead of the underlying text) I can't get the width of the text and therefore can't create a box around the text.
