### ISSUE TITLE
Conceal escaped char

### ISSUE THREAD

**Issue by kusnezoff-alexander** [OXY2DEV/markview.nvim#144]
Conceal characters prefixed with an escape-char `\`.
For example:
- `\$` -> `$`
- `\\` -> `\`

Maybe even add an option to enable/disable this behavior?

**Comment by OXY2DEV** [comment]
![Screenshot_2024-09-09-20-04-05-216_com termux_1](https://github.com/user-attachments/assets/e0ccf872-8b8e-4933-96eb-8b782cc89daf)

I also fixed a bug that didn't let escape characters to be counted in tables.

![Screenshot_2024-09-09-20-03-43-558_com termux_1](https://github.com/user-attachments/assets/ee195ecf-3616-4086-b594-1d876348fd85)
