### ISSUE TITLE
🐞 Bug:  LaTeX subscripts are rendered hiding the next character.

### ISSUE THREAD

**Issue by moshpirit** [OXY2DEV/markview.nvim#148]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

When using subscripts (eg: $\beta_1$), the next character to the latest `$` gets hidden:

![](https://i.imgur.com/qBca6xB.png)

### Steps to reproduce the issue:

1.  Open nvim 
2. Paste this:
```
$\beta_1$, this comma is not being shown 
$\beta_1$, this comma is not being shown 
```

### Expected behavior:

The comma is being shown

### Neovim version:
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128

**Comment by OXY2DEV** [comment]
Brackets are only added if you use `_{}` as `_n` can only have a single number which kinda beats the purpose of `()`

**Comment by moshpirit** [comment]
Hi! Thanks for replying! Maybe I'm not understanding you correctly or not explaining myself as I should, but my point is that it should not hide the following character when using `_n`, it's not about adding parenthesis `()`. I'm using `_n` with a single number, and no bracket is being added; yet it's interpreted as it would when rendered because it hides the following character (in this example, the comma).
