### ISSUE TITLE
- [ ] Doesnt show correctly

### ISSUE THREAD

**Issue by Landixbtw** [OXY2DEV/markview.nvim#15]
When using - [ ] to make a checkbox. The plugin renders the - as  a dot.
![image](https://github.com/OXY2DEV/markview.nvim/assets/68870626/1fbcd203-b9b8-4f2c-b7d1-78ada045a5b5)

**Comment by OXY2DEV** [comment]
This comes from `list_item`, option to disable it will be provided in the next update.

**Comment by Landixbtw** [comment]
Ill close this issue then aswell, thanks. Great plugin
