### ISSUE TITLE
✨ Feature: Add a setup option to disable automatic preview

### ISSUE THREAD

**Issue by louis-vinchon** [OXY2DEV/markview.nvim#151]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

I don't want the preview to be automatically triggered whenever I open a markdown buffer. I want to manually trigger it.

I have not found such option in the documentation so I tried to disable it with this config:
```lua
require("markview").setup({
  modes = {},
})
```

But this is not working reliably:
- It works when directly opening a file from the terminal with `nvim file.md`.
- It doesn't work when:
  - opening it in Neovim from a file explorer like nvim-tree
  - opening it in Neovim from the command line with `:e file.md`

When it doesn't work, it looks like it's in hybrid mode.

Can we get a simple ON / OFF flag in the setup options to disable the automatic preview?

Thank you.

**Comment by OXY2DEV** [comment]
Why not just use `vim.cmd("Markview disableAll")` in your config (after loading the plugin)?

Then just use `Markview toggle` to show/hide the preview.
