### ISSUE TITLE
✨ Feature: Explain Dev-Icons dependency in ReadME.md

### ISSUE THREAD

**Issue by GNOMES** [OXY2DEV/markview.nvim#153]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [ ] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [X] Other

### Description:

Currently there is not much information from the README about the nvim-web-devicons dependency. 

Running a grep on the repo I see that it is called in renderer.lua, and a few other places.

I ask as trying Markview without Nvim-web-devicons doesn't seem functionally impacted. This is at least on the handful of relatively simple markdown files.

What features of Markview are hindered/lacking when devicons is not installed?

**Comment by OXY2DEV** [comment]
![Screenshot_2024-09-18-20-09-56-674_com termux-edit](https://github.com/user-attachments/assets/8332f4e6-8255-4ea2-962b-73415ced91f3)

It's used for icons in code blocks.
