### ISSUE TITLE
✨ Feature: Always keep code block highlight

### ISSUE THREAD

**Issue by andy941** [OXY2DEV/markview.nvim#154]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Not sure if there is a combination of options to do this already but would it be possible to keep the highlight in the code block during hybrid mode? The flashing is very distracting. 
![image](https://github.com/user-attachments/assets/6ab80cdb-8153-4dff-871b-cda08b28b79d)

My config:

``` lua
require("markview").setup({
	filetypes = { "markdown", "quarto", "rmd", "codecompanion" },
	modes = { "n", "i", "c", ":", "no", "io", "co" },
	hybrid_modes = { "i", "n" },

	-- This is nice to have
	callbacks = {
		on_enable = function(_, win)
			vim.wo[win].conceallevel = 2
			vim.wo[win].concealcursor = "nc"
		end,
	},

	code_blocks = {
		style = "simple",
		sign = false,
	},
})

```

Thanks for the plugin, it's amazing!

**Comment by OXY2DEV** [comment]
> The flashing is very distracting.

Do you mean the one that occurs when you leave a code block?

> would it be possible to keep the highlight in the code block during hybrid mode?

That might not work well. If the decorations aren't cleared you might just end up with hundreds of decorations on some lines without even knowing which would make fixing issues a lot harder(since you can't directly see what's causing the issue).

**Comment by OXY2DEV** [comment]
> Yes the highlight for the whole block goes away when the cursor is inside it, but I understand if that is too complicated to implement.

Currently it's not possible, but it should be possible in the next update.

**Comment by OXY2DEV** [comment]
You can now do this.

```
require("markview").setup({
  ignore_nodes = { "fenced_code_block" }
});
```

This will prevent the decorations from disappearing when inside of code blocks.

---

If you don't line seeing ``` when scrolling over the start & end of the code block, you can set up an `autocmd` to set the value of `concealcursor` to whatever you prefer when on those lines.
