### ISSUE TITLE
🐞 Bug: Always automatically set concealcursor=nc if mode changed

### ISSUE THREAD

**Issue by yingmanwumen** [OXY2DEV/markview.nvim#155]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

The configuration before:

```lua
      callbacks = {
        on_enable = function(_, _)
          vim.wo.conceallevel = 3
          vim.wo.concealcursor = ""
        end,
    }
```

This works when it enters buffer first time.

But when entering command mode and then returning to normal mode, this plugin will automatically set concealcursor to `nc`, and I cannot set concealcursor to other values via command mode anymore, because whatever I set, it always falls to `nc`.

And apperantly, we should be able to ajust `concealcursor` via command.

I have to write my configuration like this:
```lua
      callbacks = {
        on_enable = function(_, _)
          vim.wo.conceallevel = 3
          vim.wo.concealcursor = ""
        end,
        on_mode_change = function(_, _)
          vim.wo.conceallevel = 3
          vim.wo.concealcursor = ""
        end,
      },
```

I don't think this is an elegant solution though :)

### Steps to reproduce the issue:

- set concealcursor to `""` in `on_enable` in `callbacks`
- open any markdown file
- enter command mode by `:`
- input `set concealcursor`
- `concealcursor` is set to `nc`
- input `:set concealcursor=` again
- the `concealcursor` is still `nc`

### Expected behavior:

The option `concealcursor` should be set to any value we need via command mode in a markdown file.

### Neovim version:

```bash
$ nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by OXY2DEV** [comment]
> The option concealcursor should be set to any value we need via command mode in a markdown file.

Why do you need to manually set the value of `concealcursor`?

**Comment by yingmanwumen** [comment]
> Why do you need to manually set the value of `concealcursor`?

Cause I found that  the previous option value was modified unexpectedly though my configuration was the same as documents :) 

So we may fix the document by adding a `on_mode_change` callback just like what I did above? [The current code example](https://github.com/OXY2DEV/markview.nvim?tab=readme-ov-file#-hybrid-mode) in docuement doesn't contain it

**Comment by OXY2DEV** [comment]
> The current code example in docuement doesn't contain it.

That's because it was more of a temporary solution.

In the next update, you won't need to change the `callbacks` to use hybrid mode.
