### ISSUE TITLE
✨ Feature: Concealing aliases

### ISSUE THREAD

**Issue by gbelouze** [OXY2DEV/markview.nvim#157]
### The nature of the feature:

- [X] Parser(syntax, conceal etc. related)
- [ ] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

First of all thanks for this great plugin.

Obsidian has a [syntax for aliases](https://help.obsidian.md/Linking+notes+and+files/Aliases). It is also supported for instance by [Markdown-oxide](https://github.com/Feel-ix-343/markdown-oxide).

## Suggestion
Backlinks such as `[[Jane Doe|Jane]]` could be concealed to just `[Jane]` (currently it is concealed to `[Jane Doe|Jane]`). I assume most people (myself included) use aliases to not have to look at the full link.

**Comment by OXY2DEV** [comment]
![internal link](https://github.com/user-attachments/assets/69de0239-4821-4a0a-aa2c-d6f61fc76797)
