### ISSUE TITLE
✨ Feature: Disable signs

### ISSUE THREAD

**Issue by kusnezoff-alexander** [OXY2DEV/markview.nvim#158]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Is there a way of disabling signs (`MarkviewHeading1Sign`,`MarkviewHeading2Sign`, codeblocks,...) which are shown to the left of linenumbers?

**Comment by OXY2DEV** [comment]
You can add this to your setup function.
```lua
headings = {
 heading_1 = { icon = "" },
 heading_2 = { icon = "" }
},
code_blocks = { sign = false }
```

**Comment by kusnezoff-alexander** [comment]
Thanks for your fast reply!

`code_blocks = { sign = false }` works, but `heading_2 = { icon = "" }` refers to the symbol added right before the Heading-Text, and not the sign *left* to the linenumber?

**Comment by OXY2DEV** [comment]
> Thanks for your fast reply!
> 
> `code_blocks = { sign = false }` works, but `heading_2 = { icon = "" }` refers to the symbol added right before the Heading-Text, and not the sign _left_ to the linenumber?

Oops, my bad. It's supposed to be `sign = ""`.
