### ISSUE TITLE
Refresh styling after LSP format

### ISSUE THREAD

**Issue by 22ispencer** [OXY2DEV/markview.nvim#16]
I noticed that after running `vim.lsp.buf.format()` that the styling of the newly formatted lines was no longer visible until I refreshed by entering and exiting insert mode. I don't know if there's a hook or something to re-apply the styling afterwards or not.

**Comment by OXY2DEV** [comment]
I still have not found a reliable way to do this. So, unfortunately this will be put on hold.

**Comment by OXY2DEV** [comment]
I will be closing this issue now.

Reasons:
- Plugin now uses `TextChanged` event and therefore should work as normal.
- Can't test markdown formatters due to lack of platform support.
