### ISSUE TITLE
✨ Feature: Strkethrough text of a checked Checkbox

### ISSUE THREAD

**Issue by kusnezoff-alexander** [OXY2DEV/markview.nvim#160]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Add option to strkethrough text following a checked Checkbox

**Comment by OXY2DEV** [comment]
Something like this?
![Screenshot_2024-09-28-08-48-43-131_com termux-edit](https://github.com/user-attachments/assets/1df77a27-fdaf-47ff-ac99-95adbf928fde)

**Comment by kusnezoff-alexander** [comment]
@OXY2DEV Yes, exactly :+1:
