### ISSUE TITLE
🐞 Bug: Issue with nested callouts when adding titles

### ISSUE THREAD

**Issue by mayerstrk** [OXY2DEV/markview.nvim#161]
### Before reporting:

- [x] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

![image](https://github.com/user-attachments/assets/4d14fb2c-21a3-4b80-99eb-9759487f4f2e)
![image](https://github.com/user-attachments/assets/cde1be68-a67e-4abb-b865-46b0dac86195)

Issue when adding titles to nested callouts

### Steps to reproduce the issue:

nvim

### Expected behavior:

You know, keep the highlight

### Neovim version:

v.0.10.1

**Comment by OXY2DEV** [comment]
This is a tree-sitter bug.
