### ISSUE TITLE
🐞 Bug: "Neovim version 0.10+ required" message when on Neovim v0.10.0

### ISSUE THREAD

**Issue by vi013t** [OXY2DEV/markview.nvim#164]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

When opening Neovim on markdown file, I very quickly get a flash of the error `[ markview.nvim ]: Neovim version 0.10+ required!` even though my Neovim version is v0.10.0 according to `nvim -v`. Markview then doesn't apply at all.

![image](https://github.com/user-attachments/assets/70e04005-5a41-453a-82d1-1507db117671)

![image](https://github.com/user-attachments/assets/93fddd4f-233f-4df5-a391-75878bb9fcdb)

I'm on Windows 11, and I only have one Neovim installation in my `$PATH` (and on my system in general), as checked with `where nvim`:

![image](https://github.com/user-attachments/assets/71323920-8368-437d-beb9-abeeee2d2a5a)

I have all the other usual requirements, i.e., treesitter parsers for `html`, `markdown`, and `markdown_inline`, no other markdown plugins, I'm using the `main` branch of `markview.nvim`, and my configuration (through `lazy`) is very simply:

```lua
{
	"OXY2DEV/markview.nvim",
	dependencies = {
		"nvim-treesitter/nvim-treesitter",
		"nvim-tree/nvim-web-devicons",
	},
	opts = {
		hybrid_modes = { "n" },
	},
	ft = "markdown",
}

```

### Steps to reproduce the issue:

Open `nvim` on a markdown file.

### Expected behavior:

Markview should function because I'm on version 0.10+.

### Neovim version:

NVIM v0.10.0 / Build type: Release / LuaJIT 2.1.1713484068

**Comment by OXY2DEV** [comment]
You shouldn't use 0.10.0(instead use 0.10.1).

`vim.tbl_islist()` was properly deprecated in 0.10.1 so, 0.10 can sometimes cause errors.
