### ISSUE TITLE
🐞 Bug: Checkboxes not working

### ISSUE THREAD

**Issue by BearDad** [OXY2DEV/markview.nvim#170]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

i substituted the lazyextras markdown plugin for this one but checkboxes ain't working

as you can see pretty much everything works besides the checkboxes
![image](https://github.com/user-attachments/assets/f39c185e-4d4f-483c-a9db-2f2985f734c9)

### Steps to reproduce the issue:

1. nvim
2. install lazyvim
3. install all parsers
4. install markdownview
5. write a test sheet with everything the plugin offers

### Expected behavior:

markview should've rendered the checkboxes 

### Neovim version:

NVIM v0.10.1

**Comment by realhackcraft** [comment]
I experienced a similar issue recently but it fixed itself (I think I used a preset for checkboxes)

**Comment by OXY2DEV** [comment]
For `[X]`, `[ ]` you need to have some text after them.

Old checkboxes such as `[~]`, `[o]` are no longer available.

Use this if you use the old checkboxes.
```lua
{
  checkboxes = require("markview.presets").checkboxes.legacy
}
```
