### ISSUE TITLE
🐞 Bug: Links not usable

### ISSUE THREAD

**Issue by tilupe** [OXY2DEV/markview.nvim#173]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

When in Reading mode, I can't use any links. Over file links I tried to use Enter (<CR>) or `gf` but with Enter I only jump one line and with `gf` it says it can't find the file "name of the link". Over hyperlinks to websites I tried also `gx` which won't work either.
 Then I tried to enable hybrid-Mode so that I can at least use `gf` but It didn't change anything for me. I assumed to see the not rendered text on the line I am on. But that was not the case.
 
 Not sure if I missed a command or config that would allow that.

### Steps to reproduce the issue:

I just used the default config from the README

### Expected behavior:

Links are usable with either "Enter" (<CR>) or with a configurable keystroke.

### Neovim version:

0.10.1

**Comment by OXY2DEV** [comment]
You can use this to open links,
```vim
:MarkOpen
```

Or use `gx`.

**Comment by OXY2DEV** [comment]
> When I use :MarkOpen on a file-link it will opens the file in a text editor.

It will open the file in whatever you set your default app for.

> Did you intend that for file-links

I didn't really do any extra implantation. Whatever is opened is determined by `Neovim`.

But I do plan on supporting `internal links`(from obsidian), ID links and opening text files inside Neovim.

**Comment by AndreM222** [comment]
THanks brother

**Comment by UtkarshVerma** [comment]
The current latest release v24.0.0 doesn't have this. I see the readme mentioning v25.0.0 as the latest version which isn't the case. @OXY2DEV Did the release pipeline fail?

**Comment by OXY2DEV** [comment]
> The current latest release v24.0.0 doesn't have this. I see the readme mentioning v25.0.0 as the latest version which isn't the case. @OXY2DEV Did the release pipeline fail?

That's just me commiting to the wrong branch.
