### ISSUE TITLE
[QUESTION] How do I override the highlight groups?

### ISSUE THREAD

**Issue by realhackcraft** [OXY2DEV/markview.nvim#174]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

I would like to override the highlight groups to make them work with NvChad. I have tried a highlight group of `markdownHx` and `@markup.heading.x.markdown`(where x is 1-6), but neither changed the color of the headings.

![Screenshot 2024-10-10 at 10 03 30](https://github.com/user-attachments/assets/c047d30f-0cd3-45a6-a49e-895a0b5c70e1)

### Steps to reproduce the issue:

N/A

### Neovim version:

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713773202 Run "nvim -V1 -v" for more info

**Comment by OXY2DEV** [comment]
Use your colorscheme's options to set the highlight groups. As long as the colorscheme loads before this plugin it will be used.

---

Also, why do you need to change the value of the highlight groups?

Just change the highlight group used for a specific thing in the plugin to what you want.

**Comment by realhackcraft** [comment]
I'm trying to add support for Markview in base46 colorschemes from nvchad.

**Comment by realhackcraft** [comment]
Right now, all the headings have the color of `@markup.heading` instead of `@markup.heading.x.markdown`.
![Screenshot 2024-10-10 at 11 13 56](https://github.com/user-attachments/assets/17e91a73-a904-4bb8-b6d4-31075a5e87ac)

**Comment by realhackcraft** [comment]
I'm loading the color scheme non lazily, but the hlgroups for markdown headings are only loaded right before `require("markview").setup()`.

**Comment by realhackcraft** [comment]
So the headings should be available before markview is loaded

**Comment by realhackcraft** [comment]
For reference, the issue I created in base46's repo is NvChad/base46#347

**Comment by Samar-exe** [comment]
# Solution
I use NvChad too and was having the same issue, I solved it by adding new highlight groups in the chadrc file: 

  ``` lua
hl_add = {
    ["MarkviewHeading1"] = {fg = "black", bg = "red"},
    ["MarkviewHeading2"] = {fg = "black", bg = "orange"},
    ["MarkviewHeading3"] = {fg = "black", bg = "green"},
    ["MarkviewHeading4"] = {fg = "black", bg = "blue"},
    ["MarkviewHeading5"] = {fg = "darker_black", bg = "teal"},
    ["MarkviewHeading6"] = {fg = "black", bg = "purple"},
  }
```
Here is how it looks now: 
![2024-10-12_00-25-43](https://github.com/user-attachments/assets/57b2f6fb-802e-4774-bbc4-d9d8aa755242)


Also make sure that you are setting up the highlights when loading the markview plugin: 
```lua
  markview.setup {
        headings = {
          enable = true,
          shift_width = 1,
          heading_1 = {
            style = "icon",
            hl = "MarkviewHeading1",
          },
          heading_2 = {
            style = "icon",
            hl = "MarkviewHeading2",
          },
          heading_3 = {
            style = "icon",
            hl = "MarkviewHeading3",
          },
          heading_4 = {
            style = "icon",
            hl = "MarkviewHeading4",
          },
          heading_5 = {
            style = "icon",
            hl = "MarkviewHeading5",
          },
          heading_6 = {
            style = "icon",
            hl = "MarkviewHeading6",
          },
        }
```

**Comment by realhackcraft** [comment]
I'm aware of that, but it doesn't look good with the slanted or arrow heading styles. I'm also trying to make an integration directly into NvChad base46 so that other people don't have to use this hack.

**Comment by realhackcraft** [comment]
@OXY2DEV can you confirm which hl groups affect the heading color? I think there are multiple per heading level and there's a priority thing.

**Comment by OXY2DEV** [comment]
> @OXY2DEV can you confirm which hl groups affect the heading color? I think there are multiple per heading level and there's a priority thing.

Yes, there are. It would first check `markdownH<n>`, then `@markup.heading.<n>.markdown` and then `@markup.heading`.

> <n> is the heading level.

**Comment by OXY2DEV** [comment]
> I'm aware of that, but it doesn't look good with the slanted or arrow heading styles. I'm also trying to make an integration directly into NvChad base46 so that other people don't have to use this hack.

Isn't integrations usually done by adding the highlight groups for the plugin?

**Comment by Samar-exe** [comment]
> Isn't integrations usually done by adding the highlight groups for the plugin?

Yes, but for some reason the MarkviewHeadingN is being linked to @markup.heading via Treesitter.

**Comment by Samar-exe** [comment]
> Isn't integrations usually done by adding the highlight groups for the plugin?
 Yes, but for some reason the MarkviewHeadingN is being linked to @markup.heading via Treesitter thus making all the headings of the same color.

**Comment by realhackcraft** [comment]
Samar-exe is talking about `MarkviewHeading1`, which I think is auto generated based on `markdownH1`. I tried changing `MarkviewHeading1`, but with my config of having a slanted heading, the last triangle is not changed.

![Screenshot 2024-10-11 at 23 07 03](https://github.com/user-attachments/assets/0441c5f2-ea0c-4d43-a103-d8515f7f0f50)

`:Telescope highlights`
![Screenshot 2024-10-11 at 23 08 44](https://github.com/user-attachments/assets/cd294070-5679-4d01-b633-d4ef21a51514)

> Isn't integrations usually done by adding the highlight groups for the plugin?

Yes, but I'm trying to add the highlight groups for `markdownH<n>` and `@markup.heading.<n>.markdown`, and letting markview generating the background colors and all the associated highlight groups. To my limited understanding of this plugin's code, it's able to generated `MarkviewHeading1` with the appropriate fg and bg colors.

**Comment by OXY2DEV** [comment]
> tried changing MarkviewHeading1, but with my config of having a slanted heading, the last triangle is not changed.

Because the last one comes from `MarkviewHeading1Sign`.

**Comment by realhackcraft** [comment]
I tried to also add hl groups to `MarkviewHeading<n>Sign` which fixed the last char for me. 

![Screenshot 2024-10-11 at 23 20 09](https://github.com/user-attachments/assets/a9a62780-2970-4d24-ab49-ffba1bc73e6a)

However, it doesn't generate the background color, which I have to add with a generate background function (that would duplicate the code in this plugin).

I think having markview generate the hl groups that it needs based on the fg color from `markdownH1` makes more sense.

**Comment by OXY2DEV** [comment]
Are you using a transparent theme? Or does the `Normal` highlight group doesn't have any background color?

> I think having markview generate the hl groups that it needs based on the fg color from markdownH1 makes more sense.

It leaves edge cases as now I will need to also check the luminosity of the color before darkening/lightening it for the background color.

And it gives visibility issues on very bright/dark colors.

**Comment by realhackcraft** [comment]
The screenshots I took where with transparency.

After you posted that, I tried to run it with a background color and there is still no background highlight.

https://github.com/user-attachments/assets/364219ee-1f59-43f5-8081-a4c183ca586a

**Comment by Samar-exe** [comment]
> and there is still no background highlight.

have you set the `bg` property in your chadrc?

**Comment by OXY2DEV** [comment]
I think you are mixing things up a bit.

Here's how you should be doing,

#### Option 1: Modifying the tree-sitter highlight groups.

Most colorchemes provide some way to override the default colors. Use it to change the colors.

And make sure your colorscheme loads **first**(if you use lazy, just set it's priority to 1000).

```lua
custom_groups = {
  ["markdownH1"] = { fg = "#A3E6A1" }
}
```

#### Option 2: Directly modify the plugin's highlight groups.

Again, it is better to do it in your colorscheme.

```lua
custom_groups = {
  ["MarkviewHeading1"] = { fg = "#A3E1A6", bg = "#556677" },
  ["MarkviewHeading1Sign"] = { fg = "#A6E3A1" }
}
```

Again, make sure the colorscheme loads **first**.

**Comment by realhackcraft** [comment]
I understand that. Option 1 is what I'm trying to accomplish, and options 2 is what I got to work, but I dislike this approach.

I have just found something interesting that has to do with base46, where if I load the hl groups specific to markview in init.lua, the `markdownH1` gets loaded and auto generates `markviewHeading1` and the corresponding hl groups, but not when I load it in the config of markview.

```lua
  config = function()
    dofile(vim.g.base46_cache .. "markview") -- this loads the hl groups

    require("markview").setup({})
  end,

```

**Comment by OXY2DEV** [comment]
> where if I load the hl groups specific to markview in init.lua

Isn't that how you are supposed to do it(unless you set it inside the config of the colorscheme itself)?

DO NOT SET THE COLORSCHEME INSIDE THE `config` OF `markview`.

Unless you include the colorscheme plugin as a dependency of `markview` this will NOT work.

**Comment by realhackcraft** [comment]
> DO NOT SET THE COLORSCHEME INSIDE THE config OF markview.

I know, but `dofile(vim.g.base46_cache .. "markview")` is just loading the **hl groups** in the config. Base46 delegates the loading of plugin-specific hl groups to different integration files.

- Base46 is the colorscheme plugin, loaded non-lazily
- `dofile(vim.g.base46_cache .. "markview")` loads the hl groups specific to markview
- Because I load markview lazily, it is guaranteed that base46 is loaded before markview

**Comment by realhackcraft** [comment]
@Samar-exe I have added markview integration into base46. To use it, add

```lua
M.base46 = {
  integrations = {
  "markview"  
  }
}
```

Run ":lua require("base46").compile()"

Then add 

```lua
dofile(vim.g.base46_cache .. "markview")
```

In your init.lua

This will also make the headings look better (IMO) because it adds the color to the text and a blends the heading's fg color with the buffer's bg color to make the color for the background of the heading. It would basically look exactly like what markview.nvim would look like with any other colorscheme tool.
