### ISSUE TITLE
🐞 Bug: Invalid buffer id

### ISSUE THREAD

**Issue by windowsrefund** [OXY2DEV/markview.nvim#175]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

This may be somewhat tricky as the issue comes up when using `:GpChatDelete` from the [gp.nvim](https://github.com/Robitx/gp.nvim) plugin. That said, I'll do my best to provide the sequence of events leading up to this error:

```
Error executing vim.schedule lua callback: ....local/share/nvim/lazy/markview.nvim/plugin/markview.lua:128: Invalid buffer id: 18
stack traceback:
        [C]: in function '__index'
        ....local/share/nvim/lazy/markview.nvim/plugin/markview.lua:128: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

- Start nvim
- Run `:GpChatNew`

Now we have 2 buffers open; our original and the buffer used by the chat (which renders in markdown)

```
:ls
 14 #h + "[No Name]"                    line 1
 20 %a   "~/.local/share/nvim/gp/chats/2024-10-10.14-48-17.970.md" line 13
```

Now delete the chat buffer with `:GpChatDelete`

### Steps to reproduce the issue:

See above

### Expected behavior:

I don't know and it may be more appropriate to raise this in the gp.nvim repo. Figured I'd start here based on what's generating the error.

### Neovim version:

v0.10.1

**Comment by johnend** [comment]
I have the same error show when using preview in Oil buffers. If I move the cursor down to a `.md` file and preview it, and then navigate to another file with preview still open I get a similar error as described above (only when moving away from a previewed file).

![image](https://github.com/user-attachments/assets/13b3d30c-0c44-4fad-bdc3-30c6308614cc)

**Comment by OXY2DEV** [comment]
Does the error still occur when using the `dev` branch?

**Comment by windowsrefund** [comment]
dev doesn't install

**Comment by OXY2DEV** [comment]
> dev doesn't install

How did you try to install it? What error did you encounter?

**Comment by windowsrefund** [comment]
Latest release addresses both scenarios mentioned above. Thank you for your help.
