### ISSUE TITLE
✨ Feature: Support concealing basic math TeX-symbols

### ISSUE THREAD

**Issue by kusnezoff-alexander** [OXY2DEV/markview.nvim#176]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Would it be possible to support concealment of basic TeX math-symbols (see [this link](https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols))?

**Comment by OXY2DEV** [comment]
Isn't this already available?
![Screenshot_2024-10-11-17-12-33-058_com termux-edit](https://github.com/user-attachments/assets/c33ce2fd-e514-45c0-a257-f064c44fb318)

**Comment by kusnezoff-alexander** [comment]
Not completely, I think. For instance `\oplus` is not supported yet
