### ISSUE TITLE
🐞 Bug: Why some latex symbols aren't rendering?

### ISSUE THREAD

**Issue by woquchonglang** [OXY2DEV/markview.nvim#178]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

the latex only can render some code , but my code in obsidian can be render completely
![swappy-20241012-181659](https://github.com/user-attachments/assets/79bec2d1-c0c4-4b2e-9cbf-7eb805964f7b)
![swappy-20241012-183224](https://github.com/user-attachments/assets/1c1b5691-2c50-4de2-accb-d94fc5166c2c)

### Steps to reproduce the issue:

everything is new

### Neovim version:

10.2

**Comment by OXY2DEV** [comment]
All LaTeX symbols aren't supported yet.

See #176.
