### ISSUE TITLE
Color broken in light background

### ISSUE THREAD

**Issue by nanozuki** [OXY2DEV/markview.nvim#18]
- commit: `f60219dce7283192d549f21847fcf8537bf6d260`
- config: default config
- file in image: https://github.com/folke/lazy.nvim/blob/4ea9fe060042f345960ad0c01aa7bca91405e10a/README.md

Not sure if this is a problem in #13. I found color changed in recent update, many highlight like headlines, codes are dark background in light color scheme.

<img width="689" alt="图片" src="https://github.com/OXY2DEV/markview.nvim/assets/4208028/d8c422d8-98fb-4966-bb73-f472d26c2783">

<img width="679" alt="图片" src="https://github.com/OXY2DEV/markview.nvim/assets/4208028/7bcba449-6d2a-4ccd-bca3-e0d18514a7f7">

**Comment by OXY2DEV** [comment]
> * commit: `f60219dce7283192d549f21847fcf8537bf6d260`
> * config: default config
> * file in image: https://github.com/folke/lazy.nvim/blob/4ea9fe060042f345960ad0c01aa7bca91405e10a/README.md
> 
> Not sure if this is a problem in #13. I found color changed in recent update, many highlight like headlines, codes are dark background in light color scheme.
> 
> <img alt="图片" width="689" src="https://private-user-images.githubusercontent.com/4208028/344846724-d8c422d8-98fb-4966-bb73-f472d26c2783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODQ0NDgsIm5iZiI6MTcxOTg4NDE0OCwicGF0aCI6Ii80MjA4MDI4LzM0NDg0NjcyNC1kOGM0MjJkOC05OGZiLTQ5NjYtYmI3My1mNDcyZDI2YzI3ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDEzNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJmODM4MWRiZmE3OWE4Mzg1Y2U5ODZhNmNiNWRlOWNkMjdhNDEyNWIyYmIyNDJhNDM2YmNlZGU1YTFiYmE1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H8f8wb99IyNrhBuROwdWFCdMqTzxa6PwO6MTToJcNc8"> <img alt="图片" width="679" src="https://private-user-images.githubusercontent.com/4208028/344846748-7bcba449-6d2a-4ccd-bca3-e0d18514a7f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODQ0NDgsIm5iZiI6MTcxOTg4NDE0OCwicGF0aCI6Ii80MjA4MDI4LzM0NDg0Njc0OC03YmNiYTQ0OS02ZDJhLTRjY2QtYmNhMy1lMGQxODUxNGE3ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDEzNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdiNWU0YTk0NjljOTY3YjMwNjNkM2I0YWEzY2I4OTc0OTk1ZmU2YmU3ZWE4ZDZiYjE4YTliYzliZGJmYzlkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u1movvqh5xMpMncqNEOic-IzHU46TiQyLMP9oE_H8qs">

That's because they were `hard coded`.

You can just change the `code_block`, `code_block_border` and `inline_code_block` highlight groups to whatever you want.
