### ISSUE TITLE
✨ Feature: Set foldcolumn for split window

### ISSUE THREAD

**Issue by windowsrefund** [OXY2DEV/markview.nvim#180]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [ ] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [X] Other

### Description:

Greets. Normally, I set `foldcolumn=auto`. When splitting, I don't want to see the column in the window used to render the markdown. I tried passing `foldcolumn = 0` via `split_conf` but it seems that parameter isn't meant to be used for such purposes.

**Comment by OXY2DEV** [comment]
Use the `split_enter` callback. See [wiki](https://github.com/OXY2DEV/markview.nvim/wiki/Plugin-options).

```lua
{
  callbacks = {
    split_enter = function (_, win)
      -- Whatever you want to set
    end
  }
}
```

> As the preview buffer is a `nofile` buffer if you use a plugin for the statuscolumn, it may ignore the preview window.
> In that case you will have to manually set it.
