### ISSUE TITLE
✨ Feature: Be able to change markview theme

### ISSUE THREAD

**Issue by barcell1** [OXY2DEV/markview.nvim#181]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Would like to be able to change markview entire theme for everforest for example. I know that is possible to individually tweak every color of markview, but an entire change like other plugins do would be ideal

Thanks in advance. Great plugin so far !

**Comment by OXY2DEV** [comment]
Shouldn't this be opened in the `everforest` repo?

Colorscheme specific changes are handled by colorschemes and not by the plugins.

**Comment by barcell1** [comment]
didnt know, thanks !
