### ISSUE TITLE
✨ Feature: Support Highlight concealling

### ISSUE THREAD

**Issue by barcell1** [OXY2DEV/markview.nvim#184]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Possibility to add a highlight in markdown like Pkms (like obsidian do) using ==text here== would turn the background yellow and the text bold black and would hide the ==== .

Obsidian.nvim implement this on its plugin , but since im using your ui rendering, i disable the obsidian.nvim ui rendering

**Comment by barcell1** [comment]
bro, just to clarify , is 2 == on the both sides (to be compatible with overall pkms on the market), like ==highlight== , i saw that you did a commit but with 3 === in both sides

And thanks in advance, awesome plugin !

**Comment by OXY2DEV** [comment]
I for some reason implemented `===text===` instead of `==text==`.

It should be working like `*text*` now.

![Screenshot_2024-11-19-13-04-33-183_com termux-edit](https://github.com/user-attachments/assets/a41b77ad-a9b5-40cf-aa40-f92bb1d752cf)

**Comment by barcell1** [comment]
bro sorry i though it was working but looks like was obsidian plugin or some custom css , i ditched the obsidian plugin and clean some css, im only using your plugin now, and cant make this work neither on main or dev branch

**Comment by OXY2DEV** [comment]
What have you tried?

It's working fine for me.

**Comment by barcell1** [comment]
yes, and just to be sure this feature is on main or dev only ?

**Comment by OXY2DEV** [comment]
Only on `dev`.

**Comment by OXY2DEV** [comment]
```lua
require("markview").setup({
  markdown_inline = {
    highlights = {
      default= {
        --- Change this to whatever you use.
        hl = "HighlightGroup"
      }
    }
  }
});
```

**Comment by barcell1** [comment]
> ```lua
> require("markview").setup({
>   markdown_inline = {
>     highlights = {
>       default= {
>         --- Change this to whatever you use.
>         hl = "HighlightGroup"
>       }
>     }
>   }
> });
> ```

bro sorry, im too noob rsrsrs i see the highlightgroup , and tried with chatgpt to change the fg and bg color but we cant make to work rsrsr

**Comment by OXY2DEV** [comment]
That's not how you change `fg` & `bg`.

Use this,
```lua
vim.api.nvim_set_hl(0, "customHl", {
  fg = "red"
});

require("markview").setup({
  markdown_inline = {
    highlights = {
      default= {
        hl = "customHl"
      }
    }
  }
});
```

**Comment by OXY2DEV** [comment]
> may i ask which markdown Formatter do you use ? 

I don't use any formatters.

> sometimes it breaks my bullets, 

Because, you are supposed to add an empty line between list items.

Most modern markdown viewers won't complain about it so people tend to not add them there.

**Comment by barcell1** [comment]
thanks bro, really help

**Comment by OXY2DEV** [comment]
> do you recommend stay in dev branch of this plugin ?

Until I finish the updating the plugin you can stay in `dev`. Afterwards, it's better to stay in `main`.

**Comment by barcell1** [comment]
gonna close here, working as expected, thanks !
