### ISSUE TITLE
🐞 Bug: Plugin conflict perhaps?

### ISSUE THREAD

**Issue by altanbgn** [OXY2DEV/markview.nvim#186]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

![bug](https://github.com/user-attachments/assets/833c9fd7-0f11-494b-91d5-f726859036ad)

This might be more of a question kind of approach but according to the screenshot, this doesn't look like the plugin preview. I was wondering why it looks like this considering I did everything according to the docs. (Perhaps I missed something idk).

Is there any possible plugin conflict with this?

### Steps to reproduce the issue:

I actually don't know how to reproduce but here is my [dotfile](https://github.com/altanbgn/dotfiles). I have no idea what plugin is conflicting that might be causing this.

### Neovim version:

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1727870382 Run "nvim -V1 -v" for more info

**Comment by OXY2DEV** [comment]
Did you modify the `markdown_inline/highlights.scm` or `markdown/highlights.scm` file?

**Comment by altanbgn** [comment]
> Did you modify any files like these, `markdown_inline/highlights.scm` or `markdown/highlights.scm`?

Nope, I only installed markdowns with `TSInstall markdown` `TSInstall markdown_inline` etc

**Comment by OXY2DEV** [comment]
You don't happen to use NixOS, do you?

**Comment by altanbgn** [comment]
Nope I am on arch, I tried `rm -rf` on treesitter and reinstalled and its the same.

**Comment by OXY2DEV** [comment]
Try these steps,

1. Disable `markview.nvim`.
2. Open any markdown file.
3. Run this command `:set conceallevel=2`.
4. See if the things like \` or \`\`\` gets hidden or not.

**Comment by altanbgn** [comment]
Apparently, `conceallevel` doesn't do anything. I already have that on my `options.lua`. But tried it, no change whatsoever 😅

**Comment by OXY2DEV** [comment]
Alright, run this command,
`:e $VIMRUNTIME/queries/markdown_inline/highlights.scm`.

Does this open a file?

**Comment by altanbgn** [comment]
It does

**Comment by altanbgn** [comment]
```
; From MDeiml/tree-sitter-markdown
(code_span) @markup.raw @nospell

(emphasis) @markup.italic

(strong_emphasis) @markup.strong

(strikethrough) @markup.strikethrough

(shortcut_link
  (link_text) @nospell)

[
  (backslash_escape)
  (hard_line_break)
] @string.escape

; Conceal codeblock and text style markers
([
  (code_span_delimiter)
  (emphasis_delimiter)
] @conceal
  (#set! conceal ""))

; Conceal inline links
(inline_link
  [
    "["
    "]"
    "("
    (link_destination)
    ")"
  ] @markup.link
  (#set! conceal ""))

[
  (link_label)
  (link_text)
  (link_title)
  (image_description)
] @markup.link.label

(inline_link
  (link_text) @_label
  (link_destination) @_url
  (#set! @_label url @_url))

; Conceal image links
(image
  [
    "!"
    "["
    "]"
    "("
    (link_destination)
    ")"
  ] @markup.link
  (#set! conceal ""))

; Conceal full reference links
(full_reference_link
  [
    "["
    "]"
    (link_label)
  ] @markup.link
  (#set! conceal ""))

; Conceal collapsed reference links
(collapsed_reference_link
  [
    "["
    "]"
  ] @markup.link
  (#set! conceal ""))

; Conceal shortcut links
(shortcut_link
  [
    "["
    "]"
  ] @markup.link
  (#set! conceal ""))

[
  (link_destination)
  (uri_autolink)
  (email_autolink)
] @markup.link.url @nospell

((link_destination) @_url
  (#set! @_url url @_url))

((uri_autolink) @_url
  (#offset! @_url 0 1 0 -1)
  (#set! @_url url @_url))

(entity_reference) @nospell

; Replace common HTML entities.
((entity_reference) @character.special
  (#eq? @character.special "&nbsp;")
  (#set! conceal " "))

((entity_reference) @character.special
  (#eq? @character.special "&lt;")
  (#set! conceal "<"))

((entity_reference) @character.special
  (#eq? @character.special "&gt;")
  (#set! conceal ">"))

((entity_reference) @character.special
  (#eq? @character.special "&amp;")
  (#set! conceal "&"))

((entity_reference) @character.special
  (#eq? @character.special "&quot;")
  (#set! conceal "\""))

((entity_reference) @character.special
  (#any-of? @character.special "&ensp;" "&emsp;")
  (#set! conceal " "))

```

**Comment by OXY2DEV** [comment]
Hmm, that's strange. It says \`\`\`\ should be concealed(see line 23).

**Comment by OXY2DEV** [comment]
Let's try a minimal repro.

Put this in a file(e.g. `repro.lua`.

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "nvim-treesitter/nvim-treesitter",
      opts = {
        ensure_installed = { "markdown", "markdown_inline" }
      },
    }
    {
      "OXY2DEV/markview.nvim",
      lazy = false
    }
  },
});
```

Now run this in your terminal,
```shell
nvim -u repro.lua test.md
```
> You can replace `test.md` with any markdown file you want to open.

See if the issue persists.

**Comment by altanbgn** [comment]
![Uploading bug.png…]()

**Comment by altanbgn** [comment]
![bug](https://github.com/user-attachments/assets/d4d1e836-6983-4961-a3cc-ca88eefdc434)

**Comment by altanbgn** [comment]
`conceallevel` is 2 also. So I think there is problem with my neovim?

**Comment by OXY2DEV** [comment]
> `conceallevel` is 2 also. So I think there is problem with my neovim?

Maybe, hard to tell what's causing the issue.

----

This will have to patched in the next update(which is going to take a while).

Until then, You might want to try out a different plugin.

**Comment by altanbgn** [comment]
Is there any duplicate issues? I will try to debug it in the meantime.

**Comment by OXY2DEV** [comment]
> Is there any duplicate issues? I will try to debug it in the meantime.

No, there's no other issue where only part of the syntax isn't concealed.

**Comment by altanbgn** [comment]
Alright, I managed to get it working by adding an additional plugin.
```
    {
        "plasticboy/vim-markdown",
        config = function()
            vim.g.vim_markdown_conceal = 2 -- Enable concealment for vim-markdown
        end
    }
```

Only adding this was sufficient enough to make it work for the moment

![arst](https://github.com/user-attachments/assets/05a4d130-0089-4c37-a5bb-217ac78b0f76)

**Comment by altanbgn** [comment]
The plugin is in vim script, I will try to implement it in lua.

**Comment by altanbgn** [comment]
Okay I am such an idiot. I configured my treesitter wrong in my config file. I thought this was the correct way to install since I was migrating from packer to lazy.
```
    opts = {
            sync_install = false,
            auto_install = true,
```  

When I converted it to this, All of it worked like magic.
```
    config = function()
        require("nvim-treesitter.configs").setup({
            sync_install = false,
            auto_install = true,
```

Sorry to take your time with my stupidness 😅

**Comment by OXY2DEV** [comment]
No problem. Happens to all of us.

Glad the issue is fixed 🎉.
