### ISSUE TITLE
✨ Feature: Can Markview be used on Terminal buffers?

### ISSUE THREAD

**Issue by Kraust** [OXY2DEV/markview.nvim#187]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [X] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

I came into a use case where I may want to use Markview in terminal buffers to render output from ollama. It does not look like running `:Markview` or setting the filetype of the buffer to markdown allows markdown in terminal buffers to be formatted. Looking for some input if this is possible in the current  version of the software or if the software could be made to support this.

Note: I tried adding "t" to modes in my config and it did not appear to do anything.

**Comment by OXY2DEV** [comment]
I have tested this and it won't work.

Terminals(& terminal buffers) work differently then text buffers. Tree-sitter can't create a syntax-tree as how stuff is shown on a terminal is different to how text is shown in a normal buffer.

This wouldn't be possible, at least not now.
