### ISSUE TITLE
🐞 Bug: Highlights are wrong until colorscheme is reloaded?

### ISSUE THREAD

**Issue by cultab** [OXY2DEV/markview.nvim#189]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

At start:

![image](https://github.com/user-attachments/assets/eb5eba96-381a-463c-9382-690b69dca5f5)

After `colorscheme tokyonight-night` (same with other colorschemes)

![image](https://github.com/user-attachments/assets/d939cd52-e642-4dbc-8868-e7388300fa62)

### Steps to reproduce the issue:

I could not 100% reproduce it, but this exhibits similar behavior. Instead of the highlights being gray, they are all blue until reloaded.

# repro.lua

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    "OXY2DEV/markview.nvim",
  },
})
```

`nvim -u repro.lua <file>.md`

### Expected behavior:

The correct highlights should be used from the start.

### Neovim version:

v0.10.2

**Comment by OXY2DEV** [comment]
Your colorscheme is being loaded *after* `markview`.

If you are using `lazy.nvim` then set your colorschemes priority to a large value.
```lua
priority = 1000
```

You can also call `vim.cmd("colorscheme tokyonight");` before the `setup()` function.
