### ISSUE TITLE
Table is rendered with invalid widths

### ISSUE THREAD

**Issue by fpohtmeh** [OXY2DEV/markview.nvim#19]
Version: f60219d
OS: Windows 11

Please check the attachment to compare rendered version and default (without the plugin)

![image](https://github.com/OXY2DEV/markview.nvim/assets/147282455/13893437-40ee-4070-83fd-75d87ddd07ae)

**Comment by OXY2DEV** [comment]
This has been fixed in the `dev` branch.

![tables](https://github.com/OXY2DEV/markview.nvim/assets/122956967/54f93a76-838c-4f02-8725-97e03034c2fe)

**Comment by fpohtmeh** [comment]
Amazing! When do you expect to move it to main/master?

**Comment by OXY2DEV** [comment]
I just merged it. Can you check now?

**Comment by fpohtmeh** [comment]
Yes!!!!
