### ISSUE TITLE
🐞 Bug: Heading Color Defaults to White For All Colorschemes

### ISSUE THREAD

**Issue by andysazima** [OXY2DEV/markview.nvim#192]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

When I open a markdown file, my headings always get colored with the default white color, regardless of colorscheme. I am sure to set my colorschemes after all plugins load. The ways I've learned to fix this are to 

1. _also_ change the colorscheme to what is wanted within the lua file that I have to configure the markview plugin for Lazy (under the `config = function()` section. So effectively, my fix is to improperly set the colorscheme early, then set it again when I would expect it.
2. change the colorscheme during my session to force it to load.

Example 1: I set my colorscheme to catppuccin at the end of my plugin loading. They load in as white.

![image](https://github.com/user-attachments/assets/d671d182-91f0-42fc-9ebc-95e5b2df4ebb)

I then type `colorscheme catppuccin` and now the headings work

![image](https://github.com/user-attachments/assets/e2957f2f-5e43-40fc-a176-b8bef2efdc8d)

Example 2: I set my colorscheme in the plugin file that is returned to Lazy as well as after plugins are loaded.

![image](https://github.com/user-attachments/assets/26de5690-4558-4103-83b6-070924a452f9)

After it is loaded twice, I open the file and the headings are correct on first try

![image](https://github.com/user-attachments/assets/e2957f2f-5e43-40fc-a176-b8bef2efdc8d)

I have reproduced this on nvim 0.10.1 with the following plugins

![image](https://github.com/user-attachments/assets/eb52fd9c-e0d3-40ad-bcd1-3433eb31ed3f)

### Steps to reproduce the issue:

Open a markdown file 

### Expected behavior:

Markview should have rendered the headings in the correct colorscheme upon opening the file without the need to set the colorscheme again.

### Neovim version:

0.10.1

**Comment by OXY2DEV** [comment]
> I am sure to set my colorschemes after all plugins load.

That's the problem. It should be loaded *before* this plugin.
