### ISSUE TITLE
🐞 Bug: width of highlights.

### ISSUE THREAD

**Issue by Chaitanyabsprip** [OXY2DEV/markview.nvim#194]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

The rendering length of highlights and of replacements should respect window width. I believe  currently it consider the width of the editor.

### Steps to reproduce the issue:

Open a markdown file with a heading and a `---` line separator in it.
Open a vertical split.

Now you will see the separator cut off as if it's rendering outside the viewport. 

### Expected behavior:

The rendering should occur within the bounds of the window width.

### Neovim version:

NVIM v0.11.0-dev-ab98c5b Build type: Release LuaJIT 2.1.1727870382 Run "nvim -V1 -v" for more info

**Comment by viceav** [comment]
Hi, 
what about replacing this highlighted line 
![image](https://github.com/user-attachments/assets/4721cb33-06f7-4fd0-81e2-682576a9035e)
for this 
![image](https://github.com/user-attachments/assets/b98d94a2-318f-4b47-97f2-c1ceb1c4bda6)

in both left and right portions? 

This is before
![image](https://github.com/user-attachments/assets/8e58bb01-6064-41e2-8f95-e4fc5d275a43)
And this is after
![image](https://github.com/user-attachments/assets/3161ed84-d657-443a-90e0-3e8ba3e1b4c4)

**Comment by viceav** [comment]
Nevermind, it doesn't work when there are multiple horizontal and veritcal windows, i'll see if i can fix it right

**Comment by viceav** [comment]
Hi.
So... if i understand how the plugin works, the rendering occurs per buffer. 
So the image above works because both windows are the same width 
However in this case 
![image](https://github.com/user-attachments/assets/3e487aa2-a367-4e37-bbee-4e97b4ef3d1d)
It doesn't work. 
Right now the only thing that i can think of is rendering the buffer per window, but i don't know if the plugin is capable of that and i'm not sure if  it's a good idea. 

So for now im gonna leave this, 
If someone knows better how the plugin works or has an idea  please let me know.  i'd be glad to listen :)

**Comment by OXY2DEV** [comment]
@viceav Buffers are like 📦, if 3 people looked at the contents of the 📦 they will all see the same thing.

That's exactly what's happening.

Extmarks are local to the buffer. So, different windows can't show different things.

**Comment by Chaitanyabsprip** [comment]
I think that is fine, but the highlight should consider the width based on the width largest window that the buffer is displayed in. Someone looking at the same buffer in differently sized windows is going to be a very very low probability event.

**Comment by viceav** [comment]
@OXY2DEV Got it, thanks for the explanation :smile:

**Comment by viceav** [comment]
@Chaitanyabsprip what about adding this to your  config? 
![image](https://github.com/user-attachments/assets/d58cb838-32fc-4fd4-8fbe-28d80409cebc)
