### ISSUE TITLE
🐞 Bug: problem with the display of code blocks

### ISSUE THREAD

**Issue by Neo3477** [OXY2DEV/markview.nvim#196]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

Hello everyone,

I have a small problem with the display of code blocks. As you can see in the picture, the last line of the selection is shifted to the right. Does anyone have an idea why this could be? 

![A9A2681D-B4D5-4BAC-8B70-849B124A7B54_4_5005_c](https://github.com/user-attachments/assets/05b0d149-9ebf-4909-8f84-61f80daf45a6)

### Steps to reproduce the issue:

-there are no other markown plugins
-it is the latest version
-Neovim is version 0.10.2
-all required parsers for tree-sitter are installed

### Expected behavior:

codeblock was recreated several times and in obsidian it is rendered correctly

### Neovim version:

0.10.2

**Comment by OXY2DEV** [comment]
Check your tree-sitter config as that's handled by tree-sitter and not by this plugin.
