### ISSUE TITLE
✨ Feature: Callouts dropdown menu

### ISSUE THREAD

**Issue by moshpirit** [OXY2DEV/markview.nvim#200]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Just like we have a dropdown menu with the references, it would be nice to have something similar with the callouts, because that way we could know much better than going [to the source](https://github.com/OXY2DEV/markview.nvim/blob/67b69cdaf9055bebac3682a070d7e5c8eecba29c/lua/markview.lua#L128) what are the supported callouts, and their icons or colors.

**Comment by OXY2DEV** [comment]
> Just like we have a dropdown menu with the references

What drop-down menu? Do you use something like `obsidian.nvim`?

**Comment by OXY2DEV** [comment]
Uhh, you kinda didn't tell me what the *drop-down menu* is.

**Comment by moshpirit** [comment]
This is what I meant:
![imagen](https://github.com/user-attachments/assets/8f03c9f8-e280-46c1-870e-38a9b8c4ab17)

Which looks like the one used by LSP
![imagen](https://github.com/user-attachments/assets/a11b927f-f311-4226-8c82-89b9ea8ae3ad)

Although it could be done with fzf too if that's a better implementation.

**Comment by OXY2DEV** [comment]
Obsidian.nvim(more specifically the completion files) uses `nvim-cmp` for that.

I will look into it.

> Though, `markview.nvim` supports all the Callouts from `obsidian` & all the alerts from `github`. You can always add your own ones too.

**Comment by OXY2DEV** [comment]
It's done.

![rec](https://github.com/user-attachments/assets/1fe36734-04eb-42fc-bad5-10afc56316d9)

You can test it out from the `dev` branch.

**Comment by moshpirit** [comment]
This is incredibly amazing! ❤️ thank you so much!

**Comment by MuntasirSZN** [comment]
> It's done.
> 
> ![rec](https://github.com/user-attachments/assets/1fe36734-04eb-42fc-bad5-10afc56316d9)
> 
> You can test it out from the `dev` branch.

@OXY2DEV I think its for nvim-cmp, anything you xan do for we blink.cmp people? blink.cmp link: https://cmp.saghen.dev

**Comment by OXY2DEV** [comment]
I haven't managed to make blink work for me. Last I tried it would straight up crash and even when it didn't crash it wouldn't properly give completions.

So, I would wait for finishing everything else before adding a completion source for blink.

**Comment by OXY2DEV** [comment]
@MuntasirSZN blink.cmp completion source added.

**Comment by MuntasirSZN** [comment]
> @MuntasirSZN blink.cmp completion source added.

Damn you still remember me! Thanks btw. Its morning.

**Comment by OXY2DEV** [comment]
@MuntasirSZN ramadan mubarak to you too!

**Comment by MuntasirSZN** [comment]
@OXY2DEV Doesn't work. Wait, why in the documentation part, kind is mrkdown? (typo)

**Comment by OXY2DEV** [comment]
If you are loading `blink` after Markview it won't work.

You can check if the source is loaded via `:Blink status`.

If it still doesn't trigger then check your config for blink.

**Comment by OXY2DEV** [comment]
I have tested with a fresh config and it's working fine.

>[!NOTE]
> Make sure `blink` is loaded(add it as a dependency for `markview`).


Also check `:BlinkCmp status`.

**Comment by OXY2DEV** [comment]
@MuntasirSZN you will need to manually add `markview` as a provider for blink from now on,

```
sources = {
  per_filetype = {
    markdown = { "markview" }
  }
}
```

**Comment by MuntasirSZN** [comment]
@OXY2DEV This is better cause no need to make markview load first as a must.

**Comment by MuntasirSZN** [comment]
Also @OXY2DEV its 'saghen', not 'seghen'

**Comment by MuntasirSZN** [comment]
Also @OXY2DEV its saghen. Not seghen.

**Comment by MuntasirSZN** [comment]
> @OXY2DEV This is better cause no need to make markview load first as a must.

Nah stilll -_-

**Comment by OXY2DEV** [comment]
> > [@OXY2DEV](https://github.com/OXY2DEV) This is better cause no need to make markview load first as a must.
> 
> Nah still -_-

`blink` need to be loaded first, not the other way around.
