### ISSUE TITLE
the relative path

### ISSUE THREAD

**Issue by TyrannosaurusLjx** [OXY2DEV/markview.nvim#201]
How do I make MkdnEnter use relative paths when creating files?
When I try to create a link file with this command, it creates a new file in the parent directory of the md file I opened for the first time, but this is not what I want. How can I modify this configuration?

**Comment by OXY2DEV** [comment]
> How do I make MkdnEnter use relative paths when creating files? When I try to create a link file with this command, it creates a new file in the parent directory of the md file I opened for the first time, but this is not what I want. How can I modify this configuration?

Are you sure you are in the correct repo? This plugin doesn't implement any `Mkdn*` commands.

Are you using `markdown.nvim`?

**Comment by TyrannosaurusLjx** [comment]
> > How do I make MkdnEnter use relative paths when creating files? When I try to create a link file with this command, it creates a new file in the parent directory of the md file I opened for the first time, but this is not what I want. How can I modify this configuration?
> 
> Are you sure you are in the correct repo? This plugin doesn't implement any `Mkdn*` commands.
> 
> Are you using `markdown.nvim`?

Sorry I made a mistake. It's [mkdnflow](https://github.com/jakewvincent/mkdnflow.nvim)
