### ISSUE TITLE
✨ Feature: Fold bullet lists

### ISSUE THREAD

**Issue by barcell1** [OXY2DEV/markview.nvim#202]
### The nature of the feature:

- [X] Parser(syntax, conceal etc. related)
- [ ] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Since markview.nvim is becoming the default markdown plugin for neovim , i gonna suggest here (dont know if im doing wrong) a way to properly fold bullet lists in neovim . 
Treesitter have a known bug to not work properly with bullet lists folding. And fold bullets is a thing that i miss a lot from standard markdown editors

**Comment by OXY2DEV** [comment]
Create a file named `folds.scm` in `~/.config/nvim/queries/markdown/`.

Add this to the file.
```scm
((list) @fold)
```

Use this in your config.

```lua
vim.o.foldmethod = "expr";
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()";

-- Optional, This gets rid of the fold text and shows the actual line.
vim.o.foldtext = "";
```

>[!TIP]
> Put the options in `~/.config/nvim/after/ftplugin/markdown.lua` to only use them in markdown files.

![Screenshot_2024-11-20-01-21-43-811_com termux-edit](https://github.com/user-attachments/assets/f2344fd7-7d18-4642-82fa-6d7663321b2e)
![Screenshot_2024-11-20-01-21-58-385_com termux-edit](https://github.com/user-attachments/assets/4ebae05c-e96e-4cf1-ac09-454109b70427)

**Comment by OXY2DEV** [comment]
Also, you don't even need to do this.

Just this should be enough,
```lua
vim.o.foldmethod = "expr";
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()";

-- Optional, This gets rid of the fold text and shows the actual line.
vim.o.foldtext = "";
```

**Comment by barcell1** [comment]
could you nest sublists, like in your last image, could you nest "1. Nest 4" into "Nest 3"  without folding all the list  ?

**Comment by OXY2DEV** [comment]
You mean something like this?

| Fold closed | Fold open |
|-------------|-----------|
| ![Screenshot_2024-11-20-07-01-27-303_com termux-edit](https://github.com/user-attachments/assets/784b6504-2944-4551-b232-10154dd3d41c) | ![Screenshot_2024-11-20-07-01-43-392_com termux-edit](https://github.com/user-attachments/assets/657d8e31-77a7-4cac-9a9d-d43a81e1c378) |

Use this,
```scm
((list) @fold
  (#offset! 0 0 -1 0))
```

**Comment by barcell1** [comment]
> You mean something like this?

exactly this , mine  is folding wrong 

if im in line of the Nest 3:
![image](https://github.com/user-attachments/assets/6070f564-d948-4969-acc0-d7a288988038)

and hit fold (zc) it does 
![image](https://github.com/user-attachments/assets/70ea6251-dd43-4629-8373-bcaaf02b2d53)

or hit fold (zm) it does 
![image](https://github.com/user-attachments/assets/dea993fc-b876-4b4f-93e0-0e10eaa18c05)

it dont do like yours (the correct way)

i have this im my init.lua :
```
vim.o.foldmethod = "expr";
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()";
vim.opt_local.foldtext = "getline(v:foldstart)"
vim.opt_local.foldlevel = 99 

```

where do i add this ?
```
((list) @fold
  (#offset! 0 0 -1 0))
```
