### ISSUE TITLE
✨ Feature: Make Callout continuos, without break when line is big  

### ISSUE THREAD

**Issue by barcell1** [OXY2DEV/markview.nvim#203]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

current situation:
![image](https://github.com/user-attachments/assets/da3b97e7-4e05-4d9a-90e6-573ce2a6a497)
![image](https://github.com/user-attachments/assets/ba222b1c-68d1-4916-ac41-9dd71f135ec6)

when a line is big, it breaks the callout

**Comment by barcell1** [comment]
yes, exactly this

**Comment by OXY2DEV** [comment]
Done. You can try it out from the `dev` branch.

![Screenshot_2024-11-21-16-55-38-842_com termux-edit](https://github.com/user-attachments/assets/26a21881-2aea-4775-85ed-3c587715ce18)

**Comment by barcell1** [comment]
bro, you can mark this as done/completed , tested in dev and is working very well
