### ISSUE TITLE
🐞 Bug: code block rendering is malformed

### ISSUE THREAD

**Issue by nmder** [OXY2DEV/markview.nvim#205]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

The code entries are not rendered properly when the a line wraps around: large amount of gap between each item, likely given by the height of the longest wrapped line.

### Steps to reproduce the issue:

1. Open a markdown like https://github.com/tlkh/lida/blob/0aace9c7519007b2c28421b07072c875bb7c3b87/README.md.
2. Notice the rendering of the bibtex entry at the bottom.

### Expected behavior:

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/6cf631f6-9d37-4cf2-9c21-6bc714e76b53">

### Neovim version:

0.10.2

**Comment by OXY2DEV** [comment]
Can you check if the issue exists in the `dev` branch?

**Comment by nmder** [comment]
Seems to be fixed in the `dev` branch. Thanks!
