### ISSUE TITLE
🐞 Bug: Conceallevel stays altered after leaving a markdown file

### ISSUE THREAD

**Issue by Lvdspek** [OXY2DEV/markview.nvim#206]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

Conceallevel stays altered due to hybrid mode.
After having used hybrid mode, when opening a JSON file, the quotes don't appear. As shown below:

![image](https://github.com/user-attachments/assets/6be990b6-c1a6-433d-b768-5434a965c276)

as opposed to:
![image](https://github.com/user-attachments/assets/54af941c-b740-4be8-b743-cdbea152908c)

Here's my (lazy) config:
``` lua
	"OXY2DEV/markview.nvim",
	lazy = false,
	ft = "markdown",
	dependencies = {
		"nvim-treesitter/nvim-treesitter",
		"nvim-tree/nvim-web-devicons",
	},
	config = function()
		require("markview").setup({
			modes = { "n", "i", "no", "c" },
			hybrid_modes = { "i" },
		})
		vim.cmd("Markview enableAll")
	end,
```

### Steps to reproduce the issue:

1. Open a markdown file.
2. Edit a row that triggers hybrid mode, such as a list:
![image](https://github.com/user-attachments/assets/80a427e0-9217-404f-955d-4c893c0fa2d0)
3. Open a JSON file into a new buffer.
4. Notice how the quotes are missing.

### Expected behavior:

I expect markview to reset conceallevel to its original value once the buffer containing the markdown file is exited.

### Neovim version:

0.10.0

**Comment by OXY2DEV** [comment]
That's just how it works. You can test it,

```shell
nvim example.txt
```

```vim
:set conceallevel=3
:tabnew new.txt
:set conceallevel?
```

This will show up as 3.

**Comment by Lvdspek** [comment]
Thanks for getting back to me.
I get that when setting conceallevel manually, it is kept throughout multiple files.
I just had the assumption that Markview setting it dynamically would also automatically reset it once a .md file was exited.

Unless you plan to alter this behaviour, I think hybrid mode is not for me then :)

**Comment by OXY2DEV** [comment]
> Unless you plan to alter this behaviour, I think hybrid mode is not for me then :)

I can't simply *alter* this behavior.

I can either check when you **leave** a window or when you **enter** a window.

I can't change the options as I don't know where you entered the window from.

You could open up something like `:h` where changing the conceallevel wouldn't be a good idea.

You could also be opening a file from something like `telescope` and I can't simply detect something like that.

---

You can either use the plugin without `hybrid mode` or you can use `:Markview splitToggle` to show previews in a split.

**Comment by Lvdspek** [comment]
> I can either check when you leave a window or when you enter a window.

This is what I was thinking as well. When entering a buffer with a markdown file in it, store the conceallevel at that point. Then, when leaving that buffer, _reset_ the conceallevel to its initial value. Not sure if that should be the default behavior. But perhaps it can be configured as such in the config of the plugin?

> You can either use the plugin without hybrid mode or you can use :Markview splitToggle to show previews in a split.

Yes, those are options of course. I'm still quite fond of hybrid mode - you created something nice imo. So I'm trying to see if I can hold on to it. 

I'll close the issue as I agree with you that it's not a bug. Thanks for your time and insights.
