### ISSUE TITLE
✨ Feature: quoting rendering affecting wrapped lines

### ISSUE THREAD

**Issue by moshpirit** [OXY2DEV/markview.nvim#207]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Right now, if we use line wrapping, a paragraph is shown using more than a line, but the render mechanism of markview only works for the first line. I was hoping there could be a way to make it show the rest with this rendering too. 

This way, paragraphs like this:

> Lorem ipsum dolor sit amet consectetur adipiscing elit sagittis eleifend vitae, curae bibendum laoreet vestibulum nisi urna senectus tristique pulvinar, suscipit tincidunt a parturient etiam erat blandit ligula morbi. Quam dui ultrices blandit iaculis eleifend mi risus dictumst, nibh massa tempus ullamcorper purus in scelerisque et, sociis mattis donec facilisis tortor phasellus odio. Habitant nulla sociosqu venenatis sed malesuada quam dictum nostra, mus vehicula fermentum odio lobortis hac volutpat, aptent vitae parturient laoreet proin nam primis.
Faucibus torquent erat sem porttitor maecenas magna conubia gravida sociosqu tellus molestie netus convallis cubilia, luctus aenean interdum quisque nostra dis curabitur mus class libero sodales accumsan per. Fusce proin maecenas quam egestas venenatis lobortis varius in habitasse convallis bibendum nunc magna, nulla mi suscipit porta vestibulum per torquent fermentum interdum praesent euismod. Class ante torquent himenaeos senectus nec ullamcorper eget cras, facilisi netus posuere sodales accumsan sem et faucibus, sagittis quam tellus aptent metus luctus non.

could be more similar to how are seen here in Github:
![Captura de pantalla_20241126_194557](https://github.com/user-attachments/assets/4ed3987d-2d15-48bc-bb7c-f1eb8dab5465)
here is how they look like right now:
![imagen](https://github.com/user-attachments/assets/ac979a78-fd50-47fb-85d2-9e8fee986211)

**Comment by afrolino02** [comment]
![Image](https://github.com/user-attachments/assets/a40dbd09-4e44-4943-840d-3e339a0a7970)
How can I do it? Does that fix enable in DEV yet?? I can't see it.  i have the wrap enable.

**Comment by OXY2DEV** [comment]
@afrolino02 You don't need to use the `dev` branch for this anymore.

It should work without needing to do anything. Sometimes, you need to switch between modes for it to have effect.

**Comment by afrolino02** [comment]
> [@afrolino02](https://github.com/afrolino02) You don't need to use the `dev` branch for this anymore.
> 
> It should work without needing to do anything. Sometimes, you need to switch between modes for it to have effect.
Mmm, it doesn't work :(, I changed to stable branch and nothing happened… I also changed between Normal and Insert… Can you tell me if I must have a different config?
### Configs
```lua
require("markview").setup({
  markdown = {
    enable = true,

    -- 1) HEADINGS
    headings = {
      shift_width = 0, -- elimina cualquier sangría virtual
      org_indent = false,
      org_indent_wrap = false,
      -- opcional: fuerza estilo “simple” para quitar iconos/bordes
    },

    -- 2) BLOCK-QUOTES
    block_quotes = {
      enable = true,
      wrap = true,
    },

    -- 3) LIST
    list_items = {
      enable = true,
      wrap = false,
      indent_size = 0, -- sin espacios reales
      shift_width = 0, -- sin desplazamiento virtual

      marker_minus = { add_padding = false },
      marker_plus = { add_padding = false },
      marker_star = { add_padding = false },
      marker_dot = { add_padding = false },
      marker_parenthesis = { add_padding = false },
    },
  },
})

vim.api.nvim_create_autocmd("FileType", {
  pattern = "markdown",
  callback = function()
    vim.opt_local.wrap = false
    vim.opt_local.linebreak = false
    vim.opt_local.breakindent = false
    -- hightlights
    vim.api.nvim_set_hl(0, "@markup.italic.markdown_inline", { fg = "#fabd2f", italic = true })
    vim.api.nvim_set_hl(0, "@markup.strong.markdown_inline", { fg = "#f95c4a", bold = true })
    vim.api.nvim_set_hl(0, "@markup.strikethrough.markdown_inline", { fg = "#928374", strikethrough = true })
  end,
})
```

![Image](https://github.com/user-attachments/assets/66f8b4ab-52dd-460e-9832-b731c1baf83a)

**Comment by OXY2DEV** [comment]
You haven't even turned it on,

```lua
require("markview").setup({
  preview = {
    hybrid_modes = { "n" }
  }
});
```
