### ISSUE TITLE
🐞 Bug: code not rendered correctly in headings

### ISSUE THREAD

**Issue by drewma2k** [OXY2DEV/markview.nvim#208]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

Using ` characters to create code blocks does not render properly in headers.

### Steps to reproduce the issue:

render the following text: 
```text
# code: `code` 
```
### Expected behavior:

text inside ` characters should be rendered as code

### Neovim version:

v0.10.2

**Comment by OXY2DEV** [comment]
That's an issue with Neovim. See [this issue](https://github.com/neovim/neovim/issues/31151).
