### ISSUE TITLE
Single line with a title renders twice

### ISSUE THREAD

**Issue by kdheepak** [OXY2DEV/markview.nvim#21]
Thanks for making this plugin!

Opening a line with just one line makes the rendering weird.

1. Create a file `test.md` with the following content:

```markdown
# hello world
```

2. Open the file with this plugin loaded:

<img width="256" alt="image" src="https://github.com/OXY2DEV/markview.nvim/assets/1813121/19b86e99-3e7d-42d6-8ac8-a6d25f1c5c71">

**Comment by OXY2DEV** [comment]
What's your conceallevel?

Check via `:setlocal conceallevel?`

**Comment by kdheepak** [comment]
`conceallevel = 2`

**Comment by OXY2DEV** [comment]
What's your config table look like(if you are using any)?

I can't seem to reproduce your issue on my machine.

**Comment by kdheepak** [comment]
Hmm, I don't use any config for this plugin. I guess it's something else? I'll look into my config and get back to you.

**Comment by kdheepak** [comment]
I'm closing since it seems to be something with my config.
