### ISSUE TITLE
🐞 Bug: Icons rendered twice?

### ISSUE THREAD

**Issue by alichtman** [OXY2DEV/markview.nvim#211]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

I don't really understand why this is happening, but I am getting some weird rendering behavior when opening a file:

![image](https://github.com/user-attachments/assets/ec207d36-3375-4c7a-a2f5-868daa576a9d)

If I run `:Markview`, It resolves itself:

![image](https://github.com/user-attachments/assets/38f5ed11-193d-459b-baa1-76cb4913ac8f)

My lazy config is:

```
return {
  "OXY2DEV/markview.nvim",
  ft = { "md", "markdown" },
  lazy = false,
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
}
```

I'm using `NVIM v0.11.0-dev-1261+gab9cfc4dc3`, but it reproduces with `nvim 0.10.2` also.

### Steps to reproduce the issue:

See above

### Expected behavior:

See images above

### Neovim version:

NVIM v0.11.0-dev-1261+gab9cfc4dc3

**Comment by OXY2DEV** [comment]
You have another plugin(e.g. obsdian.nvim).

Disable that plugin's previews.

---

`:Markview` will toggle this plugin. So, it doesn't *fix itself*, it just goes back to how it looked before.

**Comment by alichtman** [comment]
Ah yeah, you're right.

I recently set up avante.nvim, and the default configuration comes with a markdown renderer baked in. 

```
return {
  "yetone/avante.nvim",
  event = "VeryLazy",
...
    
    ## This is the problem

    -- {
    --   -- Make sure to set this up properly if you have lazy=true
    --   "MeanderingProgrammer/render-markdown.nvim",
    --   opts = {
    --     file_types = { "markdown", "Avante" },
    --   },
    --   ft = { "markdown", "Avante" },
    -- },
  },
}
```

**Comment by OXY2DEV** [comment]
Yeah, `render-markdown` does markdown previews too.
