### ISSUE TITLE
🐞 Bug: Checkboxes in Tables don't render (I think?)

### ISSUE THREAD

**Issue by ssteinbach** [OXY2DEV/markview.nvim#212]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

Thanks for the great plugin!  Not sure if this is intentional or not.

A table with a checkbox in it is blank or renders with an "x".

### Steps to reproduce the issue:

```md
| kind | checkbox |
|------|----------|
| Checked | [x] |
| Unchecked | [ ] |
```

Produces the attached image
<img width="232" alt="Screenshot 2024-12-01 at 1 04 03 PM" src="https://github.com/user-attachments/assets/08fad632-0810-48cf-a1c2-97e312938ef9">

### Expected behavior:

Should have put the glyph from the list in the cell, equivalent to the glyph rendered with a list:

```md
* [ ] unchecked
* [x] checked
```

<img width="130" alt="Screenshot 2024-12-01 at 1 06 08 PM" src="https://github.com/user-attachments/assets/e95fa145-e42a-4335-8801-54d63acc7935">

### Neovim version:

v0.10.1

**Comment by OXY2DEV** [comment]
You can't use checkboxes inside of tables.

| Header | Header |
|---|---|
| - [ ] Checkbox | Text |
