### ISSUE TITLE
🐞 Bug: backward slash inside inline code within a table cell causes misalignment

### ISSUE THREAD

**Issue by ibhagwan** [OXY2DEV/markview.nvim#214]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

Images will work best, consider the below aligned table:
![IMG_2766](https://github.com/user-attachments/assets/4469e399-e3cc-4e7b-85d8-87833595dd73)

Due to the backward slash, will render as:
![IMG_2765](https://github.com/user-attachments/assets/1edd7b50-f040-4a65-a8a5-877504cf72b5)

Fantastic plug-in btw @OXY2DEV, ty for your hard work! very meticulous :)

### Steps to reproduce the issue:

Use inline code within a table cell with `\` in it.

### Neovim version:

0.10.2

**Comment by OXY2DEV** [comment]
Can you check if the issue still occurs in the `dev` branch?

**Comment by ibhagwan** [comment]
Other bad things happen with the dev branch
![IMG_2767](https://github.com/user-attachments/assets/16794246-a3b5-4bb0-80d4-313d6fcaf5b8)
![IMG_2768](https://github.com/user-attachments/assets/d9a7491a-b516-49ef-b2d9-5e8889324070)

**Comment by ibhagwan** [comment]
Btw, forgot to mention my setup call removes the inline code “corner padding”:
```lua
      require("markview").setup({
        hybrid_modes = { "n" },
        inline_codes = { corner_left = "", corner_right = "" },
      })
```

**Comment by ibhagwan** [comment]
Btw, I just found another issue in the `dev` branch, regarding split toggle (which raises an exception on main branch).

- Run `:Markview splitToggle`
- Make the source markdown win (not the rendered one) only window  with `<C-w>o`
- Run `:Markview splitToggle` again:
![IMG_2770](https://github.com/user-attachments/assets/653e1a2a-3135-443a-952f-1422f5c8acde)

Can open another issue for this if you’d like, just wasn’t sure since this is the dev branch.

**Comment by OXY2DEV** [comment]
> Btw, I just found another issue in the `dev` branch, regarding split toggle (which raises an exception on main branch).
> 
> * Run `:Markview splitToggle`
> * Make the source markdown win (not the rendered one) only window  with `<C-w>o`
> * Run `:Markview splitToggle` again:
>   ![IMG_2770](https://private-user-images.githubusercontent.com/59988195/391837429-653e1a2a-3135-443a-952f-1422f5c8acde.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTk4NTgsIm5iZiI6MTczMzIxOTU1OCwicGF0aCI6Ii81OTk4ODE5NS8zOTE4Mzc0MjktNjUzZTFhMmEtMzEzNS00NDNhLTk1MmYtMTQyMmY1YzhhY2RlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwOTUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWI0ZTczZmQ3ZDA3MTQyNDEwYjk5NWE1MTk4OTJkM2E5MDhiYjVhNGJkNmE4NjRjNTE5OTU3Y2YwYTQ3ZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.or-7nJjVeYX0DbcrfThyL8mmylQkqT4r3B0IzALycYo)
> 
> Can open another issue for this if you’d like, just wasn’t sure since this is the dev branch.

It should be fixed now.

**Comment by OXY2DEV** [comment]
> Btw, forgot to mention my setup call removes the inline code “corner padding”:
> 
> ```lua
>       require("markview").setup({
>         hybrid_modes = { "n" },
>         inline_codes = { corner_left = "", corner_right = "" },
>       })
> ```

I couldn't reproduce this.

**Comment by OXY2DEV** [comment]
> Other bad things happen with the dev branch
> 
> > cursor outside of table
> > ![IMG_2767](https://private-user-images.githubusercontent.com/59988195/391829241-16794246-a3b5-4bb0-80d4-313d6fcaf5b8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTk4NTgsIm5iZiI6MTczMzIxOTU1OCwicGF0aCI6Ii81OTk4ODE5NS8zOTE4MjkyNDEtMTY3OTQyNDYtYTNiNS00YmIwLTgwZDQtMzEzZDZmY2FmNWI4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwOTUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWZjNTA3NTBjYzIxNDQ0MmExOGE4ZTU0NmQwZGE5NTc2ZmQ1NjViZGJkMDk0NjEyZGM0MjU2OTM1ZTEzNDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5cQNoPNYUAry5eD0rP-zrJDNbXHoq3rQSIVyDDRFZx4)
> > cursor on first line of table
> > ![IMG_2768](https://private-user-images.githubusercontent.com/59988195/391829248-d9a7491a-b516-49ef-b2d9-5e8889324070.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTk4NTgsIm5iZiI6MTczMzIxOTU1OCwicGF0aCI6Ii81OTk4ODE5NS8zOTE4MjkyNDgtZDlhNzQ5MWEtYjUxNi00OWVmLWIyZDktNWU4ODg5MzI0MDcwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwOTUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjNhZjM0MDAwZWJlN2RlYzVhN2U3MTU3MmZlOTI2NWNlYWRmN2E5YWZmNTc4NmNjMTRmYzQ5ZmJhMjdiMTI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fad1Qjs7zsElk8GZMCKVms15Ck6vTyqb9Wah76RodZ4)

That happens when rendering fails.
What error message did you get?

> If you are using a config and it goes away after removing the config.
> You should also provide the config table.

**Comment by ibhagwan** [comment]
Updated to the latest dev branch, here's the latest status:
- [x] `:Markview splitToggle` - solved.
- [X] There's a duplicate tag in the vimdoc help file when updating the dev branch:
![image](https://github.com/user-attachments/assets/45d68857-6d1b-4151-b722-c74f4ac31dad)

> That happens when rendering fails.
> What error message did you get?

No error messages and I get the same result on a different machine (with the same nvim config):
![image](https://github.com/user-attachments/assets/6c03a614-29d9-4f4f-9ea5-af7efaa53c31)

The odd thing is that my highlight links are cleared (the reason for the ugly red code blocks), even thought I have these right after setup.

The other odd thing is that if I leave the buffer and come back to it (even if I just open a simple fzf-lua float), the rendering is now fixed (but now requires `set nowrap` to look good?):
![image](https://github.com/user-attachments/assets/ac9a1ddc-7795-47ec-b32e-06d97cc4097b)

> If you are using a config and it goes away after removing the config.
> You should also provide the config table.

My config is on Github, relevant part is in https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugins/init.lua:
```lua
  {
    "OXY2DEV/markview.nvim",
    enabled = true,
    branch = "dev",
    ft = "markdown",
    config = function()
      print("1")
      require("markview").setup({
        hybrid_modes = { "n" },
        inline_codes = { corner_left = "", corner_right = "" },
      })
      vim.api.nvim_set_hl(0, "MarkviewCode", { default = false, link = "MarkviewHeading5" })
      vim.api.nvim_set_hl(0, "MarkviewCodeInfo", { default = false, link = "MarkviewHeading5" })
      vim.api.nvim_set_hl(0, "MarkviewInlineCode", { default = false, link = "MarkviewHeading5" })
      vim.api.nvim_set_hl(0, "MarkviewIcon1", { default = false, link = "MarkviewHeading6" })
      vim.api.nvim_set_hl(0, "MarkviewIcon2", { default = false, link = "MarkviewHeading6" })
      vim.api.nvim_set_hl(0, "MarkviewIcon3", { default = false, link = "MarkviewHeading6" })
      vim.api.nvim_set_hl(0, "MarkviewIcon4", { default = false, link = "MarkviewHeading6" })
      vim.api.nvim_set_hl(0, "MarkviewIcon5", { default = false, link = "MarkviewHeading6" })
      vim.api.nvim_set_hl(0, "MarkviewIcon6", { default = false, link = "MarkviewHeading6" })
      print("2")
    end
  },
```

Both `1` and `2` are printed when I enter a markdown file so something is clearing my custom highlight links in the dev branch (which doesn't happen on main).

**Comment by ibhagwan** [comment]
The wrap issue seems to also happen on the main branch, it seems that my window width is sufficient (see vim.o.columns in the screencast) yet it only displays properly when I widen the screen over 135 columns:
![Peek 2024-12-03 07-40](https://github.com/user-attachments/assets/ff9be2b4-a959-4872-9aac-c85a2386566c)

**Comment by OXY2DEV** [comment]
> No error messages and I get the same result on a different machine (with the same nvim config):

Well, You definitely have something in your config that is changing the `conceallevel`.

> If the issue goes away after moving the cursor, changing modes & running `:Markview`, then it's something in your config.

> The odd thing is that my highlight links are cleared (the reason for the ugly red code blocks), even thought I have these right after setup.

This can happen if you are loading you colorscheme **after** markview.

> The wrap issue seems to also happen on the main branch, it seems that my window width is sufficient

It's an issue with Neovim. When wrapping lines Neovim doesn't consider *hidden text*. So, your width is 2x of what you see.

That's why it gets wrapped like that.

> My config is on Github, relevant part is in

I can't reproduce the 1st bug with your config 🙁.
![rec](https://github.com/user-attachments/assets/9ba1642b-8a77-4a01-97bc-e543e22c5da1)

**Comment by ibhagwan** [comment]
> Well, You definitely have something in your config that is changing the conceallevel.

Did a search and removed all `conceallevel` from my config, anywhere, issue still remains.

> This can happen if you are loading you colorscheme after markview.

Not sure if that's the case, first this doesn't happen on `main` and also I loaded the plugin only on `ft = "markdown"` so it definitely loads after the colorscheme.

I tried changing it to `lazy=false` and load the colorscheme after and the linked highlights get cleared which results in this:
![image](https://github.com/user-attachments/assets/be70f5b6-6ada-402f-9de1-aeefde646403)

> Searching for the highlights `MarkviewCode`, `MarkviewInlineCode` shows (all) were cleared
![image](https://github.com/user-attachments/assets/a0f9a3d6-a9e6-4512-9bd8-57b93f1ec54d)

However, when I lazy load (meaning it's def after the colorscheme), something seems to reset my highlights to default:
![image](https://github.com/user-attachments/assets/23ab6558-3402-46ac-8796-5a1bd2b1af08)


> It's an issue with Neovim. When wrapping lines Neovim doesn't consider hidden text. So, your width is 2x of what you see.
> That's why it gets wrapped like that.

Understood

> I can't reproduce the 1st bug with your config 🙁.

Ty for your hard work @OXY2DEV! sorry for this mess of an issue.

I'm not sure what is the "1st bug" anymore as I managed to complicate this issue beyond repair :-)

Let me try and make sense again, the OP/title issue is solved in `dev`, the only 2 issues remaining are the "startup" issues:
- Highlight links that seem to get redefined on plugin load
- Bad rendering of tables on the first load only

**Comment by ibhagwan** [comment]
Ok, did the same "experiment" with `main`.

> `lazy=true`, highlights get redefined but none are missing:
![image](https://github.com/user-attachments/assets/27b77ceb-0f71-4c8d-9557-b2c318072697)

> `ft="markdown"`, hl links remain intact (cell misalignment still exists on `main` as expected):
![image](https://github.com/user-attachments/assets/0511382c-dd14-4139-9191-c2e83f6ca89d)

**Comment by OXY2DEV** [comment]
> However, when I lazy load (meaning it's def after the colorscheme), something seems to reset my highlights to default:

I think I figured out the issue.

Your colorscheme probably has a `@markup.heading`, this gets picked up by `MarkviewPalette5`, this gets linked by `MarkviewHeading5`.

And you are linking to `MarkviewHeading1`, so it's doing what it should.

Can you check what color `@markup.heading` has?

**Comment by ibhagwan** [comment]
> Your colorscheme probably has a @markup.heading, this gets picked up by MarkviewPalette5, this gets linked by MarkviewHeading5.

Correct!
![image](https://github.com/user-attachments/assets/9cf40023-9913-4d79-afa4-882aab35126d)

> And you are linking to `MarkviewHeading5`, so it's doing what it should.

Not sure I get this part, was something changed in this regard between main/dev?

> MarkviewHeading5

![image](https://github.com/user-attachments/assets/6fde1448-2bdc-4373-a9e6-dbd516a0e3e9)

**Comment by ibhagwan** [comment]
> Apparently, I accidentally deleted the autocmd responsible for setting the highlights 💀.
> 
> Let me fix that real quick.

Although not a big deal you're bound to get some issue about the duplicate tag in the vimdoc (rename `nvim-o-highlight_groups`):
![image](https://github.com/user-attachments/assets/45d68857-6d1b-4151-b722-c74f4ac31dad)

**Comment by OXY2DEV** [comment]
That's the old documentation.

I am writing the new one at the moment.

**Comment by OXY2DEV** [comment]
The highlight groups issue should be fixed now.

**Comment by ibhagwan** [comment]
Just noticing another issue with `dev`, see this weirdness with the link icons:
![Peek 2024-12-03 08-43](https://github.com/user-attachments/assets/9cd689c9-ab27-4fd8-b959-f59cafb928a5)

**Comment by ibhagwan** [comment]
> The highlight groups issue should be fixed now.

Updated to latest `dev`:
![image](https://github.com/user-attachments/assets/0d3a8816-6453-439d-8d57-a3266451fb72)


The initial render issue seems to be fixed now, however, there's another issue with the unconcealing of tables, the first/last border lines remain visible (doesn't happen on main):
![image](https://github.com/user-attachments/assets/40a0d528-4451-48e7-8a12-3211212552d7)

I have to relink to the new `MarkviewPallete` groups now so the colors are ugly as hell

**Comment by OXY2DEV** [comment]
> the first/last border lines remain visible

This is fixed now.

**Comment by ibhagwan** [comment]
> This is fixed now.

Updated:
![image](https://github.com/user-attachments/assets/c0fbb8b3-fdc7-489e-8cab-f5478b89c62a)

Now getting exceptions:
![image](https://github.com/user-attachments/assets/56b4c3c6-81c1-4419-b11a-b63fc2e67404)

**Comment by OXY2DEV** [comment]
> These happen with each move of the cursor.

I can't really fix it without seeing what is even causing the bug.

The best I can guess is there's something in the heading of the table that's causing the issue.

Do you have a link to the file causing the issue?

**Comment by ibhagwan** [comment]
> Do you have a link to the file causing the issue?

It's [fzf-lua's README](https://github.com/ibhagwan/fzf-lua/blob/main/README.md).

Btw, is there a single highlight I can change in  my colorscheme that will derive better results for the generated MarkviewPallete background colors? I'm using [bluz71/vim-nightfly-colors](https://github.com/bluz71/vim-nightfly-colors) and the default generated theme has almost all highlights with high contrast red background, to fix it I have to pretty much relink all the highlights with background:
![image](https://github.com/user-attachments/assets/78c3ec92-88a3-4200-b500-3812743b576a)

**Comment by OXY2DEV** [comment]
I found the issue.

Turns out the color space conversation function is buggy.

Let me fix that.

**Comment by OXY2DEV** [comment]
Color issues has been fixed!
![Screenshot_2024-12-04-12-16-42-161_com termux-edit](https://github.com/user-attachments/assets/c7a00510-4368-4da7-bf97-a956a98a50a9)

**Comment by OXY2DEV** [comment]
All the bugs should be fixed now

**Comment by ibhagwan** [comment]
Ty @OXY2DEV, the highlight groups look much better now:
![image](https://github.com/user-attachments/assets/26bd456b-8b4e-4d52-a3ea-c8a94f7f2aa2)

Much appreciate your hard work on this!
