### ISSUE TITLE
✨ Feature: API to enable for specific buffer/win?

### ISSUE THREAD

**Issue by ibhagwan** [OXY2DEV/markview.nvim#216]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [ ] Renderer(style, options etc. related)
- [X] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

Hi again @OXY2DEV!

Would love to support your amazing plugin in fzf-lua previews, similar to what I did with `render-markdown.nvim` https://github.com/ibhagwan/fzf-lua/discussions/1546.

Is there a single command I can run, similar to what is described [here](https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/98#issuecomment-2515611148):
```lua
require("render-markdown.core.ui").update(preview_buf, preview_win, "Fzf", true)
```

Where I'm able to attach to a specific window/buffer and trigger a redraw (so that I can call it upon scroll/resize/etc) that does not rely on autocmds (those are limited/ignored in the preview buffer)?

**Comment by OXY2DEV** [comment]
On the `dev` branch you can do,
```lua
local cmd = require("markview").commands;

-- Attach to a buffer.
cmd.attach(1);
-- Detach from a buffer.
cmd.detach(1);

-- Draw preview to a buffer(this will not change `conceallevel` & `concealcursor`, and will not update itself).
cmd.redraw(1);
-- Clear previews from a buffer.
cmd.clear(1);
```

These can also be used as regular commands.
```vim
:Markview attach 1
:Markview detach 1

:Markview redraw 1
:Markview clear 1
```

**Comment by OXY2DEV** [comment]
It unfortunately doesn't allow passing a window as the renderers don't care about the window

Rather they run a utility function to get the *most likely* correct window.

**Comment by ibhagwan** [comment]
> It unfortunately doesn't allow passing a window as the renderers don't care about the window
> 
> Rather they run a utility function to get the _most likely_ correct window.

Shouldn’t make a difference as the preview buffer is “unique”, I’ll test this tomorrow and let you know.

**Comment by ibhagwan** [comment]
@OXY2DEV, this was completed in https://github.com/ibhagwan/fzf-lua/commit/ed6539e018a522f176ad1f1ee6cb2e0172e8379a.

Unfortuntaely, it's a bit laggy, when scrolling it's also not very funcitonal, as it's very slow and almost impossible to cancel, for example, if I press scroll 5 times I have to wait a while for the result to be displayed and the intreface is laggy while this happens.

Let me know if there's a better way than calling `attach` followed by `render` as I couldn't find a method for `is_attached` but looking at the code it seemed harmless as it would just discover buffer is already attached and exit the function early.

**Comment by OXY2DEV** [comment]
That's weird. It shouldn't be lagging when scrolling.

> if I press scroll 5 times I have to wait a while for the result to be displayed

Do you have anything that modifies the buffers text? The default denounce value is **50ms** which is noticable in most cases so it could be just the plugin waiting for the denounce period to finish.

Can you tell me how `fzf-lua` is using `markview`, so that I can test it?

> Let me know if there's a better way than calling attach followed by render as I couldn't find a method for is_attached but looking at the code it seemed harmless as it would just discover buffer is already attached and exit the function early.

The reason there's not method for that is because the `attach()` function it [should be checking if the plugin can attach or not](https://github.com/OXY2DEV/markview.nvim/blob/dev/lua/markview.lua#L256).

I will add a method to check it.

**Comment by ibhagwan** [comment]
> Do you have anything that modifies the buffers text? The default denounce value is 50ms which is noticable in most cases so it could be just the plugin waiting for the denounce period to finish.

Nothing special, scroll is just a call to ctrl-d/u.

> Can you tell me how fzf-lua is using markview, so that I can test it?

Markview is enabled by default, use the latest fzf-lua and have maekview plugin loaded and it should get called automatically in the preview buffer.

**Comment by OXY2DEV** [comment]
> Nothing special, scroll is just a call to ctrl-d/u.

Uhh, so how do I scroll? I can't use `Shift+Up/Down` due to being on Android.

**Comment by ibhagwan** [comment]
> > Nothing special, scroll is just a call to ctrl-d/u.
> 
> Uhh, so how do I scroll? I can't use `Shift+Up/Down` due to being on Android.

Change the bindings to something you can use.

For a single call picker call: 
```lua
:lua require("fzf-lua").files({keymap={builtin={["<c-f>"]="preview-page-down"}}})
```

Permanently:
```lua
require("fzf-lua").setup({
  keymap={builtin={
    ["<c-f>"]="preview-page-down",
    ["<c-b>"]="preview-page-up"
}}})
```

**Comment by OXY2DEV** [comment]
Ah, thanks. That works.

I am noticing lags when switching between files. But I don't see any lags when doing `preview-page-up` & `preview-page-down`.

Does the lag happen even when viewing small files on your end?

**Comment by ibhagwan** [comment]
> Does the lag happen even when viewing small files on your end?

Happens on the fzf-lua project REAME.md, let me know if you’d like I’ll record a comparison between how it behaves with render-markdown vs markview.

**Comment by OXY2DEV** [comment]
So, I am noticing that on each scroll `attach()` & `redraw()` are being called.

`attach()` is exiting property. So, I am thinking that lag could potentially be from having 2 redraws(1 from `redraw()` and another from the **CursorMovedI**).

---

I don't think you need to run `attach()` because, the user might not want the buffers to be attached without actually opening them.

You can however do.

```
--- I will be adding a way to retrieve the buffer if you don't have access to it.
cmd.clear();
cmd.redraw();
```

You are running it on each scroll. So, this should be a lot simpler and easier.

**Comment by OXY2DEV** [comment]
Yup, it's definitely the 2 redraws.

I changed `attach()` with `clear()` and the lag seems to not happen on scroll anymore.

-----

But this means that `conceallevel` & `concealcursor` aren't set.

Since `render-markdown` & `markview.nvim` both use these options. Is it possible to change their value based on filetype on your end?(Because I don't want JSON files to also use conceals if these are set globally).

**Comment by ibhagwan** [comment]
Changed to:
```lua
cmd.clear(bufnr);
cmd.redraw(bufnr);
```

Similar slow and laggy behavior on scrolls.

**Comment by ibhagwan** [comment]
> But this means that conceallevel & concealcursor aren't set.

> Since render-markdown & markview.nvim both use these options. Is it possible to change their value based on filetype on your end?(Because I don't want JSON files to also use conceals if these are set globally).

It seems this is still rendered regardless of the options (I didn't check if it's set or not), but if these are needed and I call `clear` or `redraw` doesn't it make more sense to have these enabled on markview's end?

**Comment by OXY2DEV** [comment]
> Changed to:
> 
> ```lua
> cmd.clear(bufnr);
> cmd.redraw(bufnr);
> ```
> 
> Similar slow and laggy behavior on scrolls.

Uhh, does it look like this on your end? I can't really tell which one(Termux, neovim, fzf-lua or markdown) is lagging.

https://github.com/user-attachments/assets/cd7279c8-46b8-477b-92e6-72fb137b2558

**Comment by ibhagwan** [comment]
> Also, I am seeing that you have pushed changes to main in your repo.
> Unfortunately, the whole commands thing only works on the dev branch.
> So, I think you should comment it out until v25 is released.

I see, perhaps it's better off I will comment this out as well and we do the testing again once this is on the main branch, otherwise it's just asking for issues.

**Comment by OXY2DEV** [comment]
Can you send a recording of the lags?

**Comment by ibhagwan** [comment]
> Can you send a recording of the lags?

Recoding now, I found the issue is actually much worse, just having markview enabled makes the scroll of anything in fzf-lua worse, even when markview rendering is disabled in the previewer, recording now.

**Comment by OXY2DEV** [comment]
I think I found the issue.

For some reason, I added `CursorMoved` to `attach()` instead of being a global event.

This caused the plugin to become extremely laggy since every time `attach()` is called a new autocmd getes created resulting in this mess.

**Comment by ibhagwan** [comment]
I just recorded using software called `peek` but it's impossible to see the issue as the frame right is so bad, I'll have to research something that records terminal in high FPS.

Basically if I hold down `shift-down` to scroll, enabling `markview.nvim` causes very bad lag whereas without the plugin the scrolling is super speedy and instant

> I think I found the issue.
> For some reason, I added CursorMoved to attach() instead of being a global event.

It certainly does feel like markview is doing something regardless of it happening in an unattached buffer.

**Comment by OXY2DEV** [comment]
I have done some test. And the lag is definitely coming from the movement autocmds.

I will see where the issue is.

**Comment by OXY2DEV** [comment]
I have made some changes to how redrawing works.

Can you test it out(as I can't test it properly on a phone)?

Here's a minimal config to make it easier,
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
        spec = {
                {
                        "nvim-treesitter/nvim-treesitter",
                        build = ":TSUpdate",

                        ensure_installed = { "markdown", "markdown_inline" }
                },
                {
                        "OXY2DEV/markview.nvim",
                        branch = "dev",
                        lazy = false
                },
                {
                        "ibhagwan/fzf-lua",
                        commit = "ed6539e018a522f176ad1f1ee6cb2e0172e8379a",
                        pin = true,
                        opts = {
                                keymap = {
                                        builtin = {
                                                ["<PageUp>"] = "preview-page-up",
                                                ["<PageDown>"] = "preview-page-down",
                                        }
                                }
                        }
                }
        },
});

vim.o.conceallevel = 3;
vim.api.nvim_set_keymap("n", "<space>q", "<CMD>:q<CR>", {});
```

**Comment by ibhagwan** [comment]
> Can you test it out(as I can't test it properly on a phone)?

Going to sleep, will test tomorrow, now regarding…

> ** I can't test it properly on a phone**

Is this a temporary a thing or are you telling me you’ve developed this plugin in its entirety on a freaking phone, and why do I get the feeling it’s the latter (as evident [in this comment](https://github.com/OXY2DEV/markview.nvim/issues/216#issuecomment-2522016068))? 🤯🤯🤯

If so, I gotta step up my game, this is some next level dedication lol

**Comment by OXY2DEV** [comment]
> Is this a temporary a thing or are you telling me you’ve developed this plugin in its entirety on a freaking phone,

Yes, all 24,461 lines of it 💀.
![Screenshot_2024-12-06-12-43-47-712_com termux-edit](https://github.com/user-attachments/assets/9b023bb7-8952-4011-8b08-2e064515b494)

> Just to be clear, ~6,000 lines of it are just for storing math symbols, math fonts, HTML entities etc.

**Comment by OXY2DEV** [comment]
> If so, I gotta step up my game, this is some next level dedication lol

Those 4k+ stars would like to disagree with you.

**Comment by ibhagwan** [comment]
> Yes, all 24,461(or around 18K if you only count code) lines of it 💀.

Couldn’t help it lol

https://www.reddit.com/r/neovim/comments/1h7vhmg/bro_been_developing_his_2k_star_plugin_on_a/

> Those 4k+ stars(in your repos) would like to disagree with you.

You’re too kind :)

**Comment by OXY2DEV** [comment]
So, I have looked into the issue a bit more and here's what I found,

1. The culprit for the lag was `redraw()`. It is meant to render the preview only once and doesn't do denouncing. So, this causes a lot of lags(as literally calling it causes it to redraw the buffer 20-30 times a second).
2. Making the entire thing asynchronous isn't an option as one of the core feature of the plugin is the ability to change the config *at any time*(even without calling `setup()`). And trying to make the entire thing async kinda doesn't work with this.
3. Using `attach()` from the previewers side isn't a good option as it would relay on the mode for showing the preview. The user could have changed the mode option which would result in the preview not showing at all.

Here's what I think should be done.

Allow `attach()` to take a second argument. If the second argument is not `nil` it will ignore the mode option.

**Comment by OXY2DEV** [comment]
Here's a simple comparison(with the minimal config,

Pay attention to when I let go of the buttons.

> Before

https://github.com/user-attachments/assets/3e6043cb-400a-4f92-8aa6-2ac5bcb1eea6

> After

https://github.com/user-attachments/assets/f6525be4-6bbd-4a75-859b-b784218979a2

>[!NOTE]
> I deleted `mv.redraw()` and used `mv.attach(bufnr, true)`.

**Comment by ibhagwan** [comment]
> Pay attention to when I let go of the buttons.

Can def see the difference.

> I deleted `mv.redraw()` and used `mv.attach(bufnr, true)`

Just making sure I understand this right,I should reduce calls to `atrach` only? No need to call `mv.redraw` anymore?

**Comment by OXY2DEV** [comment]
> Just making sure I understand this right,I should reduce calls to atrach only? No need to call mv.redraw anymore?

Yes, just calling `mv.attach(bufnr, true)` will be enough.

Let me know, if the lag still occurs.

**Comment by ibhagwan** [comment]
> Let me know, if the lag still occurs.

It's fantastic now, no lag!

While adding support for render-markdown I realized I could minic the split view (which you have added to this plugin), looks quite wonderful doesn't it?

We can close this issue with this beautiful screenshot, cheers @OXY2DEV :rocket: 

![image](https://github.com/user-attachments/assets/5ff4bb63-0b57-413b-a6c4-b218b865b1b7)

**Comment by OXY2DEV** [comment]
> It's fantastic now, no lag!

Awesome!

> While adding support for render-markdown I realized I could minic the split view (which you have added to this plugin), looks quite wonderful doesn't it?

Indeed, it does. Even though I added `splitview` & `hybrid_mode`. I never actually used them(outside of testing).

So, feedbacks are welcome.

> We can close this issue with this beautiful screenshot, cheers @OXY2DEV 🚀

Cheers!

**Comment by ibhagwan** [comment]
Just re-enabled support for `markview`, although it's still on `dev` branch I used the existence of the `redraw` method to distinguish between main/dev, let me know if this looks acceptable (unless you plan to delete the `redraw` method from commands, this should work):
> https://github.com/ibhagwan/fzf-lua/commit/a5698761ff2b12a0d04cd0be0b60ae6970b0c539
```lua
  elseif package.loaded["markview"] then
    local cmds = package.loaded["markview"].commands
    if cmds and cmds.redraw then cmds.attach(bufnr, true) end
  end
```

**Comment by OXY2DEV** [comment]
Yes, this looks good.

**Comment by DT021** [comment]
> > Is this a temporary a thing or are you telling me you’ve developed this plugin in its entirety on a freaking phone,
> 
> Yes, all 24,461(or around 18K if you only count code) lines of it 💀. ![Screenshot_2024-12-06-12-43-47-712_com termux-edit](https://private-user-images.githubusercontent.com/122956967/393126096-9b023bb7-8952-4011-8b08-2e064515b494.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MTkzMjUsIm5iZiI6MTczMzUxOTAyNSwicGF0aCI6Ii8xMjI5NTY5NjcvMzkzMTI2MDk2LTliMDIzYmI3LTg5NTItNDAxMS04YjA4LTJlMDY0NTE1YjQ5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQyMTAzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWExNzY1MzE2NjA1MjNjMDMxMDE4MzljZGI0YjY4N2ZjOTBjYTRjZjNlOGRhMDYxNWE5MjVjYjA4NTE3YzRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xqtE6m63oYOT3ERcRK4pFZhCWZq0cSdCAniWdfn3uB0)
> 
> > Just to be clear, ~6,000 lines of it are just for storing math symbols, math fonts, HTML entities etc.

Is this a preference thing or do you not have a pc to be able to code on?

**Comment by OXY2DEV** [comment]
> Is this a preference thing or do you not have a pc to be able to code on?

I don't have a PC to code on.

**Comment by zachlatta** [comment]
If you're interested, there are some people in https://www.reddit.com/r/neovim/comments/1h7vhmg/bro_been_developing_his_2k_star_plugin_on_a/ who are interested in starting a GoFundMe for you to get a laptop!

**Comment by OXY2DEV** [comment]
> If you're interested, there are some people in https://www.reddit.com/r/neovim/comments/1h7vhmg/bro_been_developing_his_2k_star_plugin_on_a/ who are interested in starting a GoFundMe for you to get a laptop!

There's already #218 about that.

GoFundMe only works on selected countries, so it wouldn't really work out.

**Comment by zachlatta** [comment]
What country are you in? I might be able to help coordinate. I run https://hackclub.com which has given grants to high schoolers all over the world.

**Comment by OXY2DEV** [comment]
> What country are you in?

Bangladesh.

> high schoolers

I am not a high schooler though(unless high school also includes the 11th & 12th grade).

**Comment by siduck** [comment]
@OXY2DEV  you should be able to setup buymecoffee or ko-fi at least :thinking:

**Comment by Myzel394** [comment]
@OXY2DEV if you can cash it out, I (and surely other people as well) could also send you some crypto currencies! I'd be happy to send you some Bitcoin or Monero :)

**Comment by xz-dev** [comment]
> @OXY2DEV if you can cash it out, I (and surely other people as well) could also send you some crypto currencies! I'd be happy to send you some Bitcoin or Monero :)

Although cryptocurrencies are convenient for international transactions, I don’t think there is a way for a minor to cash out for fiat currency.

**Comment by Leichesters** [comment]
> Although cryptocurrencies are convenient for international transactions, I don’t think there is a way for a minor to cash out for fiat currency.

It is good idea. He has parents that can cash out or he can wait until he is no longer minor. I can also send xrp.
