### ISSUE TITLE
✨ Feature: being able to change the color of the regular text, bold and italics.

### ISSUE THREAD

**Issue by moshpirit** [OXY2DEV/markview.nvim#217]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [X] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

We can change the headings, code blocks, quote blocks, hyperlinks, list items and check boxes, but I can't find how to set a specific color for regular, italic and bold texts.

**Comment by OXY2DEV** [comment]
Uhh, did you see the [README](https://github.com/OXY2DEV/markview.nvim?tab=readme-ov-file#-highlight-groups)?

**Comment by moshpirit** [comment]
> Uhh, did you see the [README](https://github.com/OXY2DEV/markview.nvim?tab=readme-ov-file#-highlight-groups)?

Hi, thanks for replying! Yes, I have, but I don't see anywhere bold, italics or regular text. I'm not sure exactly what do you mean. Do you mean that these are beyond what the plugin can do?

**Comment by OXY2DEV** [comment]
> > Uhh, did you see the [README](https://github.com/OXY2DEV/markview.nvim?tab=readme-ov-file#-highlight-groups)?
> 
> Hi, thanks for replying! Yes, I have, but I don't see anywhere bold, italics or regular text. I'm not sure exactly what do you mean. Do you mean that these are beyond what the plugin can do?

Yes, because the plugin doesn't change their color.

They are controlled by tree-sitter. And you can check the group name by running `:Inspect` on top of the text.

**Comment by moshpirit** [comment]
> Yes, because the plugin doesn't change their color.
> 
> They are controlled by tree-sitter. And you can check the group name by running `:Inspect` on top of the text.

TIL!! NeoVim is an amazing world, I'm glad to learn in every step of configuration I take.

I got to customize to emphasize the text with custom colors:

```lua
return {
  { --NOTE: Gruvbox.NVIM
    'ellisonleao/gruvbox.nvim',
    lazy = false,
    name = 'gruvbox',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme 'gruvbox'
      vim.api.nvim_create_autocmd('FileType', {
        pattern = 'markdown', -- To set custom colors in Markdown files, fonts are defined by the terminal.
        callback = function() 
          -- vim.api.nvim_set_hl(0, '@spell.markdown', { fg = '#f9f0cc' }) -- Regular font
          vim.api.nvim_set_hl(0, '@markup.italic.markdown_inline', { fg = '#fabd2f', italic = true })
          vim.api.nvim_set_hl(0, '@markup.strong.markdown_inline', { fg = '#f95c4a', bold = true })
          vim.api.nvim_set_hl(0, '@markup.strikethrough.markdown_inline', { fg = '#928374', strikethrough = true })
        end,
      })
    end,
  },
}
```
