### ISSUE TITLE
Working config for "label" heading?

### ISSUE THREAD

**Issue by pkazmier** [OXY2DEV/markview.nvim#22]
Can you share a working configuration that would produce this style of headings? I've been trying different permutations from the wiki page, but I'm getting various errors and cannot figure out the secret incantation I'm supposed to be doing. Ideally, if I could add an icon to the front of those headings as well (without the shift_width), it would be perfect.

![image](https://github.com/OXY2DEV/markview.nvim/assets/747855/3962a619-9022-4ae8-9b36-a4eabc125914)

On the wiki, there is this example:

```lua
    style = "label",

    hl = "rainbow1",

    corner_left = "", corner_left_hl = nil,
    corner_right = "", corner_right_hl = nil,

    padding_left = "", padding_left_hl = nil,
    padding_right = "", padding_right_hl = nil,

    icon = "", icon_hl = nil,
    text = "", text_hl = nil,

    sign = nil, sign_hl = nil
```

But it fails with "attempt call field 'position' (nil value)". Any help would be appreciated as I really like the design choices you have made here. It looks lovely and as one that spends most of my time taking notes in markdown, I appreciate all your efforts!

**Comment by OXY2DEV** [comment]
This is the actual table for headings.

```lua
require("markview").setup({
    heading = {
        enable = true,
        shift_width = 4,

        heading_1 = {},
        heading_2 = {},
        heading_3 = {},
        heading_4 = {},
        heading_5 = {},
        heading_6 = {}
    }
});
```
What you are showing should be inside the `heading_1`(and all the other headings if you are configuring them too).

I will update the wiki to be more clear.

**Comment by OXY2DEV** [comment]
Check [this table](https://github.com/OXY2DEV/markview.nvim/blob/399525e3d6e726cdd887c5e9be632ffc0b450783/lua/markview/presets.lua#L351) it has everything configured(it is used in the screenshot).

You can see how I did it.

**Comment by pkazmier** [comment]
Sorry if I was not clear, I do understand the top-level configuration and had the block of code in the right location. In addition, I had also discovered that table you shared, but even that configuration does not work for me as I get this error:

```
E5108: Error executing lua vim/_editor.lua:0: nvim_exec2()..BufWinEnter Autocommands for "<buffer=3>": Vim(append):Error executing lua callback: .
..te/pack/deps/opt/markview.nvim/lua/markview/renderer.lua:586: attempt to call field 'position' (a nil value)
stack traceback:
        ...te/pack/deps/opt/markview.nvim/lua/markview/renderer.lua:586: in function 'render_headers'
        ...te/pack/deps/opt/markview.nvim/lua/markview/renderer.lua:1153: in function 'render'
        ...m/site/pack/deps/opt/markview.nvim/ftplugin/markdown.lua:43: in function <...m/site/pack/deps/opt/markview.nvim/ftplugin/markdown.lua:2
9>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...ivim/site/pack/deps/start/mini.nvim/lua/mini/starter.lua:1528: in function 'eval_fun_or_string'
        ...ivim/site/pack/deps/start/mini.nvim/lua/mini/starter.lua:908: in function 'eval_current_item'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...ivim/site/pack/deps/start/mini.nvim/lua/mini/starter.lua:1528: in function 'eval_fun_or_string'
        ...ivim/site/pack/deps/start/mini.nvim/lua/mini/starter.lua:908: in function 'eval_current_item'
        [string ":lua"]:1: in main chunk
```

And here is the config I tried:
```lua
require("markview").setup({
  modes = { "n", "i" },
  headings = {

    enable = true,
    shift_width = 0,

    heading_1 = {
      style = "label",

      padding_left = " ",
      padding_right = " ",

      corner_right = "",
      corner_right_hl = "decorated_h1_inv",

      hl = "decorated_h1",
    },
    heading_2 = {
      style = "label",

      padding_left = " ",
      padding_right = " ",

      corner_right = "",
      corner_right_hl = "decorated_h2_inv",

      hl = "decorated_h2",
    },
    heading_3 = {
      style = "label",

      padding_left = " ",
      padding_right = " ",

      corner_right = "",
      corner_right_hl = "decorated_h3_inv",

      hl = "decorated_h3",
    },
    heading_4 = {
      style = "label",

      padding_left = " ",
      padding_right = " ",

      corner_right = "",
      corner_right_hl = "decorated_h4_inv",

      hl = "decorated_h4",
    },
    heading_5 = {
      style = "label",

      padding_left = " ",
      padding_right = " ",

      corner_right = "",
      corner_right_hl = "decorated_h5_inv",

      hl = "decorated_h5",
    },
    heading_6 = {
      style = "label",

      padding_left = " ",
      padding_right = " ",

      corner_right = "",
      corner_right_hl = "decorated_h6_inv",

      hl = "decorated_h6",
    },
})

```

**Comment by pkazmier** [comment]
Also, I'm using main branch as I saw you merged the dev branch to it.

**Comment by OXY2DEV** [comment]
Ah, that one's a bug. My bad

**Comment by OXY2DEV** [comment]
Can you check now?

**Comment by pkazmier** [comment]
No more errors. Looks like I just need to define those decorated highlight groups now. Thanks!

<img width="536" alt="image" src="https://github.com/OXY2DEV/markview.nvim/assets/747855/e5699cea-f4dd-446b-ac88-2c85429b42d7">

**Comment by OXY2DEV** [comment]
They are also in that file.

Check [this line](https://github.com/OXY2DEV/markview.nvim/blob/399525e3d6e726cdd887c5e9be632ffc0b450783/lua/markview/presets.lua#L246)

**Comment by pkazmier** [comment]
Yeah, just saw that as well. It's looking great now:

<img width="550" alt="image" src="https://github.com/OXY2DEV/markview.nvim/assets/747855/e9c70d43-9eab-4384-a8ee-40149d2ce797">

Just need to find out what happened to my code block background, but that's easy enough. Thanks again!

**Comment by pkazmier** [comment]
Hmm ... I see when I defined those highlight groups, it overrides all of them, so I no longer get the defaults you had picked for things like the code block, the block quote, etc ... Any chance you can do a `vim.tbl_deep_extend` to merge user choices with the standard ones?

**Comment by pkazmier** [comment]
Specifically, I lose these groups when I added the decorated ones. I'll just re-add these manually, but it would be nice to merge versus replace.

<img width="905" alt="image" src="https://github.com/OXY2DEV/markview.nvim/assets/747855/2d72568e-9ba0-454c-ac63-7fe7f6fc7950">

**Comment by pkazmier** [comment]
Looking good now! Next step for me is to link all of those highlight groups so I don't have hardcoded values as I switch themes often and would like colors that align with the theme I'm using. But coincidentally your choices look good with my primary theme (minihues). 
<img width="754" alt="image" src="https://github.com/OXY2DEV/markview.nvim/assets/747855/4f8df92f-c2d3-49e1-b992-25882eb9b2cb">

They even look good with my secondary theme (gruvbox-material)—save for the code block:
<img width="754" alt="image" src="https://github.com/OXY2DEV/markview.nvim/assets/747855/d4630b66-a35b-4b6a-9cd4-53538e33f71a">

**Comment by OXY2DEV** [comment]
> Specifically, I lose these groups when I added the decorated ones. I'll just re-add these manually, but it would be nice to merge versus replace.
> 
> <img alt="image" width="905" src="https://private-user-images.githubusercontent.com/747855/346171200-2d72568e-9ba0-454c-ac63-7fe7f6fc7950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTY2OTEsIm5iZiI6MTcyMDE5NjM5MSwicGF0aCI6Ii83NDc4NTUvMzQ2MTcxMjAwLTJkNzI1NjhlLTliYTAtNDU0Yy1hYzYzLTdmZTdmNmZjNzk1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNjE5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTk1ODgwOTIyMjM0ZTA3YjRhODVhMjk3NzQxNTBkMzk3ZGVhZDZlN2U2MjJjNDNjZmU5MWJlOTI0MDJlOGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pT5QEAhf-GqRPcbG53TqDURZXif4pb1ZQP2NYJ8e4vk">

You can just do something like `vim.list_extnend( require("markview").configuration.highlight groups, require("markview.presets").decorated_hls)` for that.

**Comment by pkazmier** [comment]
I submitted #24 which allows a user to use the established idiom of overriding default values via the setup function. One can override only a specific item, while still inheriting the rest of the defaults.

**Comment by OXY2DEV** [comment]
> I submitted #24 which allows a user to use the established idiom of overriding default values via the setup function. One can override only a specific item, while still inheriting the rest of the defaults.

This is not intended behavior. This works great when you are doing small tweaks to the plugin.

But when you try to use the setup function to *actually* set things up to your need you will have no way to remove these default highlight groups.

The plugin is meant to be configured in 2 ways either via the `presets` or by `configuring everything`.

Besides, you can just use `vim.list_extend(markview.configuration.highlight groups, { your_list_of_highlights })` to do that.

**Comment by pkazmier** [comment]
What are your thoughts on this line from the PR?

https://github.com/OXY2DEV/markview.nvim/pull/24/files#diff-f95388a6e004a0ee8f59c156ec09bc8b0545c9f780a52430b21d15a9246c0376R501

Before I got the label headers working, when I wanted to use the default icon headers, I had to define all of them because I could not just set `shift_width` because doing so with a shallow extend wiped out your defaults. Thanks.

**Comment by OXY2DEV** [comment]
> What are your thoughts on this line from the PR?
> 
> https://github.com/OXY2DEV/markview.nvim/pull/24/files#diff-f95388a6e004a0ee8f59c156ec09bc8b0545c9f780a52430b21d15a9246c0376R501
> 
> Before I got the label headers working, when I wanted to use the default icon headers, I had to define all of them explicitly—even though I had no changes to heading_N—because I could not just set `shift_width`. Doing so with a shallow extend wiped out your defaults. Thanks.

The plugin originally used `tbl_deep_extend` but there's a problem. You lose the ability to disable parts of the plugin.

Some of the options use nested tables for their configuration and deep extend will result in inconsistent behavior (due to properties set by the plugin getting into places you don't want them).

Plus, some of the options use the `hl` property which will have an issue here because now you have explicitly define all the color related properties(as they will otherwise use `hl` instead).

**Comment by pkazmier** [comment]
On a tangential note, I really like how my headings stack when using nvim-treesitter-context. In the prior markdown plug-in I used, the formatting of the header reverted back to plain text. But, with your plug-in, the formatting stays, so it looks very nice. Here is a small movie to demonstrate.

https://github.com/OXY2DEV/markview.nvim/assets/747855/64d0d6c9-e654-4311-a595-e7f3af3c3ff9
