### ISSUE TITLE
🐞 Bug: Add support to Vimwiki

### ISSUE THREAD

**Issue by Bthxtly** [OXY2DEV/markview.nvim#224]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

I'm using Vimwiki, which sets file type as "vimwiki" under its path. I add "vimwiki" to the "filetypes" table, but when I open a vimwiki file, it throws error "no parser for 'vimwiki' language, see :help treesitter-parsers". **Can I let Markview treat the vimwiki file as a normal markdown file and use markdown parser?** Here are my configure and errors:
![image](https://github.com/user-attachments/assets/9aa99ac0-d555-40c3-9500-e28342a6faf0)
![image](https://github.com/user-attachments/assets/293cb2bf-bcbe-4226-a30d-36c6fa61eb44)

### Steps to reproduce the issue:

Add "vimwiki" to "filetypes" option and open a vimwiki file, then nvim tries to look for vimwiki parser but fail.

### Expected behavior:

Use markdown parser instead.

### Neovim version:

NVIM v0.10.2

**Comment by OXY2DEV** [comment]
This is something you have to set up yourself.

Maybe, try this?

```lua
require("nvim-treesitter.parsers").get_parser_configs().vimwiki = {
    experimental = true,
    install_info = {
      files = { "src/parser.c", "src/scanner.c" },
      location = "tree-sitter-markdown",
      url = "https://github.com/MDeiml/tree-sitter-markdown"
    },
    maintainers = { "@MDeiml" },
    readme_name = "markdown (basic highlighting)"
});
```

**Comment by OXY2DEV** [comment]
Also, the filetype is `vimwiki`, only the syntax is using `markdown`.

So, you should've also changed what parser is used for `vimwiki`(otherwise you aren't making use of the tree-sitter highlighting) files.

**Comment by Bthxtly** [comment]
Thanks, I solve the problem by adding `vim.treesitter.language.register("markdown", { "vimwiki" })` to my configure file. I'm new to neovim and don't know much about treesitter, but you inspired me. Thank you anyway :)
