### ISSUE TITLE
how to enable hybrid mode for the whole table in normal mode?

### ISSUE THREAD

**Issue by uwla** [OXY2DEV/markview.nvim#232]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

If I use hybrid mode in normal mode and the cursor is inside a table, the table borders are not rendered, neither other elements (code blocks, italic, bold) for the current line, but they are still rendered for the remaining lines.

This causes the table lines to be misaligned

![image](https://github.com/user-attachments/assets/a1bb6755-98d1-4d45-877a-99556515b7e8)

![m7](https://github.com/user-attachments/assets/b6fd4891-f287-4739-97d7-4b64572aec13)

Even though the table is aligned, it appears misaligned, which causes confusion.

### Steps to reproduce the issue:

Enable hybrid mode for normal mode, create a tablet whose lines delimiters are aligned, and whose table cells have elements such as code blocks, italics and bold.

### Expected behavior:

Have an option to not render code blocks, italics, and bold inside tables when using hybrid mode, so that the table alignment is consistent

### Neovim version:

latest

**Comment by OXY2DEV** [comment]
There's no way to get around this.

Some of the syntaxes are hidden by `tree-sitter`. So, they are beyond my control.

> I can't overwrie them as some other plugin may rely on these.

You can change what is concealed via `~/.config/nvim/queries/markdown/highlights.scm`(see default values via `e $VIMRUNTIME/queries/markdown/highlights.scm`).

You can simply remove everything that has `@conceal`.

---

You may also want to remove the inline ones too using `~/.config/nvim/queries/markdown_inline/highlights.scm`(default values are in `e $VIMRUNTIME/queries/markdown_inline/highlights.scm`).
