### ISSUE TITLE
[Feature Request] Option to only unconceal the current line

### ISSUE THREAD

**Issue by Rizhiy** [OXY2DEV/markview.nvim#25]
Currently, when I enter insert mode, the whole file changes the conceal level. What would be better is if only the current line changed the level of conceal, or perhaps the current "context", e.g. code block.

**Comment by kuntau** [comment]
The obsidian style. Would be great if we could have this feature

**Comment by OXY2DEV** [comment]
Last time I tried it was very **VERY** buggy.

I am going to try again later to see if I can do something.

**Comment by kuntau** [comment]
Maybe this feature better suited to be in Neovim core?

**Comment by OXY2DEV** [comment]
> Maybe this feature better suited to be in Neovim core?

Neovim core already has this. You can check it by setting the `conceallevel` to 2.

The only issue is it doesn't hide `virtual text`. So things like `inline code`, `link` have the same text shown twice.

**Comment by oonamo** [comment]
I found a workaround for this, at least for markdown wiki links and md links.
I placed this in my `after/ftplugin/markdown.lua`
```lua
vim.api.nvim_create_autocmd("CursorMoved", {
	buffer = vim.api.nvim_get_current_buf(),
	callback = function()
		if vim.fn.mode():sub(1, 1) == "i" then
			return
		end
		local cursor = vim.api.nvim_win_get_cursor(0)
		local line = vim.fn.getline(cursor[1])
		local is_wiki_link = line:match("%[%[.*%]%]")
		if is_wiki_link then
			vim.o.concealcursor = ""
			return
		end
		local is_md_link = line:match("%[.*%]%(.*%)")
		if is_md_link then
			vim.o.concealcursor = ""
			return
		end
		-- local is_todo = line:match("- %[.%]")
		-- if is_todo then
		-- 	vim.o.concealcursor = ""
		-- 	return
		-- end
		vim.o.concealcursor = "n"
	end,
})

```

**Comment by OXY2DEV** [comment]
You can use the new `options` configuration option to make it unconceal text on the current line.

![concealing.gif](https://github.com/user-attachments/assets/fe1639bb-1729-4cea-86ac-cdfed925a19c)

Use this in your config.

```lua
options = {
    on_enable = {
        conceallevel = 2,
        concealcursor = ""
    },
    on_disable = {
        conceallevel = 0,
        concealcursor= ""
    }
}
```

**Comment by daviewales** [comment]
Is this still valid? I've tried the following, but it doesn't seem to be working for me:

```
	require 'markview'.setup {
		options = {
			on_enable = {
				conceallevel = 2,
				concealcursor = ""
			},
			on_disable = {
				conceallevel = 0,
				concealcursor= ""
			}
		}
	}
```

Even when I manually `:set conceallevel=0` or `:set concealcursor=""`, it flashes for a second, then instantly switches back to full conceal.

**Comment by OXY2DEV** [comment]
> Is this still valid? I've tried the following, but it doesn't seem to be working for me:
> 
> ```
> 	require 'markview'.setup {
> 		options = {
> 			on_enable = {
> 				conceallevel = 2,
> 				concealcursor = ""
> 			},
> 			on_disable = {
> 				conceallevel = 0,
> 				concealcursor= ""
> 			}
> 		}
> 	}
> ```
> 
> Even when I manually `:set conceallevel=0` or `:set concealcursor=""`, it flashes for a second, then instantly switches back to full conceal.

`options` has been renamed to `callbacks`. Use this,
```lua
require 'markview'.setup {
    callbacks = {
        on_enable = {
            conceallevel = 2,
            concealcursor = ""
        },
        on_disable = {
            conceallevel = 0,
            concealcursor= ""
        }
    }
}
```

See [default values here](https://github.com/OXY2DEV/markview.nvim/blob/main/lua/markview.lua#L39).

**Comment by ibhagwan** [comment]
> options has been renamed to callbacks. Use this,

Hi @OXY2DEV, I’m trying to have the cursor line unconcealed, tried both what you suggested above and also functions as callbacks but only my `on_disable` is called:
> lazy setup opts
```lua
  {
    "OXY2DEV/markview.nvim",
    enabled = true,
    -- ft = "markdown",
    lazy = false,
    opts = {
      callbacks = {
        on_enable = function(_, window)
          print("enabled")
          vim.wo[window].conceallevel = 2;
          vim.wo[window].concealcursor = "";
        end,
        on_disable = function(_, window)
          print("disabled")
          vim.wo[window].conceallevel = 0;
          vim.wo[window].concealcursor = "";
        end,
      }
    },
  },
```

**Comment by OXY2DEV** [comment]
> I’m trying to have the cursor line unconcealed

When are you trying to have them unconcealed?

---

If you are trying to have the line under cursor *always* unconcealed you need to use the `on_mode_change` callback. [See the wiki](https://github.com/OXY2DEV/markview.nvim/wiki/Plugin-options)

**Comment by ibhagwan** [comment]
> When are you trying to have them unconcealed?

I’m trying to have similar behavior to what is displayed in your screen recording above where the cursor line is unconcealed when the cursor moves, similar to the default behavior of render-markdown.

> If you are trying to have the line under cursor always unconcealed you need to use the on_mode_change callback too

Maybe I’m missing something, but the mode doesn’t change when I’m moving the cursor on normal mode, I want the **current line** to show the original text only without any decorations, shouldn’t the trigger for this happens when the cursor moves?

**Comment by OXY2DEV** [comment]
> I’m trying to have similar behavior to what is displayed in your screen recording above

You can simply just do,
```lua
hybrid_modes = { "n" }
```
No need to use the callbacks.

**Comment by ibhagwan** [comment]
> > I’m trying to have similar behavior to what is displayed in your screen recording above
> 
> You can simply just do,
> 
> ```lua
> hybrid_modes = { "n" }
> ```
> 
> No need to use the callbacks.

Ty @OXY2DEV! this is exactly what I was after :)

**Comment by rodhash** [comment]
Hybrid mode is interesting but, what if we want to unconceal only the current line while in Insert mode?

I'm trying some [options](https://github.com/OXY2DEV/markview.nvim/wiki/Plugin-options#-plugin-options) but didn't quite work for that purpose yet.

Setting `conceallevel=2` doesn't seem to do the trick as well.

Even tho @OXY2DEV  mentioned this to be quite [buggy](https://github.com/OXY2DEV/markview.nvim/issues/25#issuecomment-2211704255), is this too much buggy? I was trying to give it a shot.

**Comment by OXY2DEV** [comment]
> Hybrid mode is interesting but, what if we want to unconceal only the current line while in Insert mode?

I will probably add an option to add this.

> I'm trying some options but didn't quite work for that purpose yet.

Because it's kinda hard-coded on the main branch.

> Setting conceallevel=2 doesn't seem to do the trick as well.

Because this only affects *conceals*.

> Even tho @OXY2DEV mentioned this to be quite buggy, is this too much buggy? 

The initial version was buggy because I couldn't get the lines numbers to not show the decorations in.

I was trying to get similar behavior as `render-markdown` but after testing it, it got in the way more than it helped(which kinda beats the point of having the feature).

It should be easy to re-implament now though.

I will give it a try tomorrow.

**Comment by rodhash** [comment]
Cool .. thanks!

**Comment by OXY2DEV** [comment]
@rodhash I have added this feature in the `dev` branch.

So, it should be available in `v25`.

If you would like to test it out put this in your config,
```lua
preview = {
  linewise_hybrid_mode = true
}
```

**Comment by rodhash** [comment]
Thank you for the quick development but for me it still unconcealing the whole file.

I have dev branch installed:
<img width="542" alt="image" src="https://github.com/user-attachments/assets/cd3d275a-97d6-4b7a-a253-2c5bb7ad9164">

My config file:
```lua

      require("markview").setup({
        linewise_hybrid_mode = true
      })
```

Am I missing something?

**Comment by OXY2DEV** [comment]
> Am I missing something?

You first need to enable hybrid mode.

I am assuming you want to use it in `[i]insert mode`. This is what you need to use.

```lua
require("markview").setup({
  preview = {
    modes = { "n", "no", "c", "i" },
    hybrid_modes = { "i" },
    linewise_hybrid_mode = true
  }
});
```

Apologies for not making it clear.

**Comment by rodhash** [comment]
Hey, no worries!

Even tho "dev" branch worked before this time I got an error trying to install it:

<img width="586" alt="image" src="https://github.com/user-attachments/assets/a98907e9-3666-475a-aa64-9dd710f271bf">


Interesting that, even with that error it seems to be working and unconcealing only current line.

**Comment by OXY2DEV** [comment]
> Even tho "dev" branch worked before this time I got an error trying to install it:

That's because I forgot to remove the old sections of the help file.

> Interesting that, even with that error it seems to be working and unconcealing only current line.

Yes, this error doesn't affect the plugin itself and rather is an issue with opening the help files for the plugin.

**Comment by daviewales** [comment]
Thank you!!! I've been waiting a long time for a plugin like this!
On `dev`, with the following config, it's nearing perfection!

``` lua
require 'markview'.setup {
	preview = {
		modes = { "n", "no", "c", "i" },
		hybrid_modes = { "i", "n" },
		linewise_hybrid_mode = true
	}
}
```

**Comment by OXY2DEV** [comment]
What's stopping it from reaching perfection?

**Comment by daviewales** [comment]
Haha! If you could show images inline like [hologram.nvim](https://github.com/edluffy/hologram.nvim), it would be amazing. But you can probably wait until more mainstream terminal support at least one of the competing graphics protocols (Kitty, iTerm2, Sixel). And perhaps there's a way to make `hologram.nvim` and `markview.nvim` work together, to avoid duplicating the work.

Also, text seems to jump right by one character then back again when revealing it.
See the following consecutive frames of a recording:

![105](https://github.com/user-attachments/assets/ce52e8b8-c951-4551-8e58-8d819d7188f5)
![106](https://github.com/user-attachments/assets/faf1c337-ce83-4977-a486-1f0b53cb813b)
![107](https://github.com/user-attachments/assets/e09f2f3c-2c49-4506-abe1-a82730abad87)

Also, soft-wrapped lists don't maintain their indentation:

![image](https://github.com/user-attachments/assets/3d7d752e-d113-4435-9761-42cadfad203e)

Also, conceal gets disabled when my autocompletion appears:
![image](https://github.com/user-attachments/assets/6947a521-f8bf-4665-a6e8-c7690c3365fe)

All that said, this is still the best Markdown plugin for Neovim! Thank you!

**Comment by OXY2DEV** [comment]
> If you could show images inline like hologram.nvim

I personally don't want add extra dependencies(unless *absolutely needed*) as testing them for potential bugs is impossible in some cases.

Unfortunately, image rendering is *super slow*. It takes ~2s just to load a 200kb image so testing it is not ideal.

I will wait for image support in Neovim(this is being discussed by the contributors). As that would make maintaining the feature easier.

> Also, text seems to jump right by one character then back again when revealing it.

This is something I can try to fix. I originally didn't do this as iterating over a lot of nodes may not be ideal. I will see if I can fix it.

> Also, soft-wrapped lists don't maintain their indentation:

This is a sacrifice I had to make as otherwise `inline codes` & $math * symbols$ get stretched. There's also no good way to determine where a line is wrapped. So, counting it character by character could be the cause of lags.

> Also, conceal gets disabled when my autocompletion appears:

Unfortunately, I couldn't reproduce this. I use `nvim-cmp`. Unless your mode changed during completion(this will happen 3 times whenever you use `snippets`, and 2 times when using some completions).

> EDIT: OSC8 URL support would be cool 

Some terminal do provide something similar to this. For example if you use `xfce4-terminal` you can hover over links and they act like the links in the browser.

I don't want to use mouse events(as it could potentially break stuff and I don't enough confidence that my code won't have bugs, I have seen the creator of NvChad heavily use this but it gets very laggy for me when using this approach).

**Comment by OXY2DEV** [comment]
Btw, this is what I was talking about relating to links.

![Screenshot_2024-12-12-09-55-38-909_com termux x11-edit](https://github.com/user-attachments/assets/9d9cfff6-a2a5-4ff1-b360-c97d181ab22d)

**Comment by daviewales** [comment]
Regarding links, if it's working for you in xfce4-terminal, maybe it's just my terminal (Tried in Windows Terminal and WezTerm) or my Neovim version (v0.10.2) which is lacking. (Are you running a development version of Neovim?)

I did find one more glitch. Inline code over hard line breaks doesn't conceal properly:

![image](https://github.com/user-attachments/assets/3b6b3296-43d2-48f2-9e7b-1063f1019c71)

![image](https://github.com/user-attachments/assets/2413bb7e-050c-4f46-a54b-59edc98275a8)

**Comment by OXY2DEV** [comment]
> Are you running a development version of Neovim?)

I can't. The development version for 0.11 added a new dependency and unfortunately, this dependency isn't available in Termux.

So, unless someone patches that for Termux. I won't be able to use development builds. Also, I will have to wait for binaries to release before installing newer versions of Neovim(if the dependencies aren't available).

**Comment by OXY2DEV** [comment]
> I did find one more glitch. Inline code over hard line breaks doesn't conceal properly:

That might have been caused by a typo on my end.

I will fix that(along with some other minor bugs).

**Comment by daviewales** [comment]
Thanks for the tip about `nvim-cmp`. I was still on the deprecated predecessor `nvim-compe`. Switching to `nvim-cmp` has fixed the flicker when autocompletion activates.
