### ISSUE TITLE
[Feature Request] Specify modes for conceal

### ISSUE THREAD

**Issue by Rizhiy** [OXY2DEV/markview.nvim#26]
Currently, the conceal also changes when entering command mode, e.g. to write the file (`:w`).
Would be great if we could specify which mode the text is concealed in. The default should probably be normal and command.

**Comment by OXY2DEV** [comment]
You can already do that with the `modes` option(as mentioned [here](https://github.com/OXY2DEV/markview.nvim/wiki/Setup#modes)).

```
modes = { "n", "c" }
```

**Comment by OXY2DEV** [comment]
> The default should probably be normal and command.

This plugin makes use of `conceal` so if the preview is active in `command` sometimes search will not work properly.

**Comment by OXY2DEV** [comment]
I will be closing this as there is currently option to specify the modes.

[It is mentioned in the wiki page](https://github.com/OXY2DEV/markview.nvim/wiki/Plugin-setup).
