### ISSUE TITLE
[BUG] Code indent not working properly after list item

### ISSUE THREAD

**Issue by Rizhiy** [OXY2DEV/markview.nvim#27]
See:
""""
1. Item

   ```python
   import os

   import more
   ```
"""
Rendered as:
![image](https://github.com/OXY2DEV/markview.nvim/assets/5617397/9ef156ac-351e-4de9-aa46-5324d95a5e31)

**Comment by OXY2DEV** [comment]
Can you check it now?

![Screenshot_2024-07-06-07-07-32-838_com termux-edit](https://github.com/OXY2DEV/markview.nvim/assets/122956967/720cc040-b5e1-423f-8328-18f6d0ba0a9b)

**Comment by Rizhiy** [comment]
That problem is gone, but now there is another)
![image](https://github.com/OXY2DEV/markview.nvim/assets/5617397/fee903dd-2a41-40cf-8d78-e4339113a556)

Please note: the line between imports is completely empty.

**Comment by OXY2DEV** [comment]
> That problem is gone, but now there is another)
> ![image](https://github.com/OXY2DEV/markview.nvim/assets/5617397/fee903dd-2a41-40cf-8d78-e4339113a556)
> 
> Please note: the line between imports is completely empty.

The plugin no longer adds padding to empty lines. It was removed due to not working as intended.

**Comment by Rizhiy** [comment]
Well it doesn't need to add padding, just render the code block properly.

**Comment by OXY2DEV** [comment]
> Well it doesn't need to add padding, just render the code block properly.

That's not how virtual text works.

You need something on the line where the plugin will try to add decorations.

Or else it will be added to the start of the line.

Before empty lines in `list_items` would get padding added to them(regardless of whether they are empty or not).

This unfortunately doesn't quite work. There are cases where you have a list followed by a table. In that case the top border of the table will get messed up and.

Or in case you have a list and multiple empty lines after it the plugin will add padding to all of those empty lines(this is from treesitter so not much can be done here). This is bad when you have a list at the end of a file.

There will probably be some forms of limit to how many `empty lines` are considered part of the list. But for now, you just have to add spaces to empty lines.

**Comment by Rizhiy** [comment]
Maybe add padding only inside code blocks?
