### ISSUE TITLE
Refresh on normal mode command

### ISSUE THREAD

**Issue by YodaEmbedding** [OXY2DEV/markview.nvim#28]
Rendering problems mostly seem to occur when a command is run outside of insert mode. For instance, try:

 - `i# Hi<Esc>yyp`
  ![Screenshot 2024-07-05 at 8 17 53 PM](https://github.com/OXY2DEV/markview.nvim/assets/721196/c429fb0c-c99f-4c01-8c24-52549713ce34)

 - `i# Hi<Esc>u<C-r>`
  ![Screenshot 2024-07-05 at 8 20 08 PM](https://github.com/OXY2DEV/markview.nvim/assets/721196/a71cec76-aa56-4435-afe0-329b258aca19)

**Comment by OXY2DEV** [comment]
I don't think there's much I can do since the plugin relies on the `ModeChanged` event. If the event isn't fired then you get results like that.
