### ISSUE TITLE
Issue with the new pending task `[-]`

### ISSUE THREAD

**Issue by kuntau** [OXY2DEV/markview.nvim#30]
<img width="60" alt="Screenshot 2024-07-06 at 3 29 35 PM" src="https://github.com/OXY2DEV/markview.nvim/assets/327489/da8fe397-b7c5-44d5-970d-582692d2f8b8">
<img width="66" alt="Screenshot 2024-07-06 at 3 34 34 PM" src="https://github.com/OXY2DEV/markview.nvim/assets/327489/0a861074-a403-443e-9993-aa61539bd3ee">

Looks like some alignment issue or missing space on the right with the new style

**Comment by OXY2DEV** [comment]
What did you write that caused the issue?

**Comment by OXY2DEV** [comment]
I can't seem to reproduce it.

![Screenshot_2024-07-06-13-46-14-953_com.termux-edit.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/e19f23da-2898-461f-8ddb-7526721a48fb)

**Comment by kuntau** [comment]
<img width="59" alt="Screenshot 2024-07-06 at 4 03 57 PM" src="https://github.com/OXY2DEV/markview.nvim/assets/327489/59500d1d-58c3-4295-919d-3555fd874ca3">

Normal stuff

**Comment by kuntau** [comment]
Maybe it's nerd font fault?

**Comment by OXY2DEV** [comment]
Why are you using `- -` instead of `- [-]`?

Markdown doesn't support pending checkboxes. So the plugin only looks for [-]. So, that could be an issue.

No idea why you are getting something shown there.

**Comment by OXY2DEV** [comment]
> Maybe it's nerd font fault?

It can be since nerd font symbols sometimes replace normal symbols.

**Comment by kuntau** [comment]
I thought you're using nerd font symbols.

**Comment by OXY2DEV** [comment]
> I thought you're using nerd font symbols.

I am not. It's from the `Geometric shapes` symbols group.

![Screenshot_2024-07-06-14-21-34-325_jp.ddo.hotmist.unicodepad.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/08eb0374-cb08-4f66-9cbb-408b7a980d03)
