### ISSUE TITLE
Bug with nvim 0.9.5

### ISSUE THREAD

**Issue by edicon** [OXY2DEV/markview.nvim#31]
nvim -v  
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

An error occurs when running nvim.
The config is default.

E5108: Error executing lua ....local/share/nvim/plugged/markview.nvim/lua/markview.lua:544: attempt to call field 'islist' (a nil value)
stack traceback:
        ....local/share/nvim/plugged/markview.nvim/lua/markview.lua:544: in main chunk
        [C]: in function 'require'

**Comment by OXY2DEV** [comment]
Did you read the requirements?

![Screenshot_2024-07-07-13-55-50-801_com.github.android-edit.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/7e77002c-c1b5-4c79-a50f-5e98bafc5ab5)


Literally the first line says it requires 0.10 **minimum**.

The plugin uses inline virtual texts. And anything below 0.10 doesn't support it.
