### ISSUE TITLE
change conceallevel when toggle Markview

### ISSUE THREAD

**Issue by LintaoAmons** [OXY2DEV/markview.nvim#34]
When toggle-off Markview

set the conceallevel = 0

when toggle-one Markview

set the conceallevel back to 2

**Comment by OXY2DEV** [comment]
It should do it by default.

![Screenshot_2024-07-07-14-37-15-592_com.termux.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/9da71d90-4731-4b16-8a83-f42bb9f66bdf)

**Comment by LintaoAmons** [comment]
thanks, then should be the issue of my own config~

**Comment by OXY2DEV** [comment]
> thanks, then should be the issue of my own config~

If you are using a `distro` make sure it doesn't change your options(or check what options they set).
