### ISSUE TITLE
Empty line breaks table rendering

### ISSUE THREAD

**Issue by Saecki** [OXY2DEV/markview.nvim#38]
Table rendering breaks when there is a that is completely empty:

```md
| Key                              | Action                   |
|----------------------------------|--------------------------|
| <kbd>left-click</kbd>            | Add a stream line origin |
| <kbd>right-click</kbd>           | Remove a stream line     |
| <kbd>ctrl scroll</kbd>           | Zoom                     |
|                                  |                          |
| <kbd>scroll</kbd>                | Pan                      |
| <kbd>shift scroll</kbd>          | Pan in x-direction       |
| <kbd>middle-click</kbd> and drag | Pan                      |
```

![image](https://github.com/OXY2DEV/markview.nvim/assets/43008152/c26ebf14-4980-4537-815d-f12692e16fe0)

As soon as one character is added to the any of the columns of the empty line, the table is rendered as expected:

![image](https://github.com/OXY2DEV/markview.nvim/assets/43008152/8a389ec0-eca2-4032-aa02-4bdae52fbede)

**Comment by OXY2DEV** [comment]
That's because treesitter doesn't consider it a `valid` table.

![Screenshot_2024-07-07-19-11-36-242_com.termux-edit.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/cc8c80e8-345f-4f31-bba3-55ca23e65417)

**Comment by OXY2DEV** [comment]
> After further investigation this seems to be an issue with the top and bottom table borders overlapping other ajacent content, for example this happens when there is no blank line after a title:

That's not an issue. That's just how virtual text work.

**Comment by Saecki** [comment]
> That's because treesitter doesn't consider it a `valid` table.
> 
> ![Screenshot_2024-07-07-19-11-36-242_com.termux-edit.jpg](https://private-user-images.githubusercontent.com/122956967/346337152-cc8c80e8-345f-4f31-bba3-55ca23e65417.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTgzMjQsIm5iZiI6MTcyMDM1ODAyNCwicGF0aCI6Ii8xMjI5NTY5NjcvMzQ2MzM3MTUyLWNjOGM4MGU4LTM0NWYtNGYzMS1iYmEzLTU1Y2EyM2U2NTQxNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxMzEzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzM5NDU5MmRiNTY1NWIzMjBjNzliNDIwMDA1ZTdiMmYyNzE5YmI3NjE2NWFlMTVmMjM3YjFlMDg5YjFkZWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bx3e5dNGQ7dmOuYghWRImcAagjWHadFhT8zWhJsSccA)

Well that sucks :(

**Comment by Saecki** [comment]
> > After further investigation this seems to be an issue with the top and bottom table borders overlapping other ajacent content, for example this happens when there is no blank line after a title:
> 
> That's not an issue. That's just how virtual text work.

My point was, that maybe the top and bottom borders could be added as virtual lines to avoid that behavior.

**Comment by OXY2DEV** [comment]
> > That's because treesitter doesn't consider it a `valid` table.
> > 
> > ![Screenshot_2024-07-07-19-11-36-242_com.termux-edit.jpg](https://private-user-images.githubusercontent.com/122956967/346337152-cc8c80e8-345f-4f31-bba3-55ca23e65417.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTgzMjQsIm5iZiI6MTcyMDM1ODAyNCwicGF0aCI6Ii8xMjI5NTY5NjcvMzQ2MzM3MTUyLWNjOGM4MGU4LTM0NWYtNGYzMS1iYmEzLTU1Y2EyM2U2NTQxNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxMzEzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzM5NDU5MmRiNTY1NWIzMjBjNzliNDIwMDA1ZTdiMmYyNzE5YmI3NjE2NWFlMTVmMjM3YjFlMDg5YjFkZWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bx3e5dNGQ7dmOuYghWRImcAagjWHadFhT8zWhJsSccA)
> 
> Well that sucks :(

I don't think it would've mattered since other markdown previewers would've most likely either skipped it or rendered 2 separate tables.

**Comment by Saecki** [comment]
Yeah, I think it's fine not to support these invalid tables. I just thought the virtual lines would fix this issue with content directly above or below tables, like here:

> After further investigation this seems to be an issue with the top and bottom table borders overlapping other ajacent content, for example this happens when there is no blank line after a title: ![image](https://private-user-images.githubusercontent.com/43008152/346335640-c819afb4-2fd4-42d1-a7df-cec2fb03d60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTg5MzMsIm5iZiI6MTcyMDM1ODYzMywicGF0aCI6Ii80MzAwODE1Mi8zNDYzMzU2NDAtYzgxOWFmYjQtMmZkNC00MmQxLWE3ZGYtY2VjMmZiMDNkNjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEzMjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NjMxNmIxZGFjMzJkMzMwMDBiODE5YzI1Y2I1MmFmYjg4NjFiOTdiZWE3MzAxNWJmYTZkZTM3OTA3N2U5N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UnzUtnC-G0jT0udsXShRneIlovqDbQ__ogKEYfO-yK4)
> 
> So the parser seems to think the table ends at the empty line, and tries to draw the top and bottom border of a table

**Comment by OXY2DEV** [comment]
> Yeah, I think it's fine not to support these invalid tables. I just thought the virtual lines would fix this issue with content directly above or below tables, like here:
> 
> > After further investigation this seems to be an issue with the top and bottom table borders overlapping other ajacent content, for example this happens when there is no blank line after a title: ![image](https://private-user-images.githubusercontent.com/43008152/346335640-c819afb4-2fd4-42d1-a7df-cec2fb03d60a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTg5MzMsIm5iZiI6MTcyMDM1ODYzMywicGF0aCI6Ii80MzAwODE1Mi8zNDYzMzU2NDAtYzgxOWFmYjQtMmZkNC00MmQxLWE3ZGYtY2VjMmZiMDNkNjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEzMjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NjMxNmIxZGFjMzJkMzMwMDBiODE5YzI1Y2I1MmFmYjg4NjFiOTdiZWE3MzAxNWJmYTZkZTM3OTA3N2U5N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UnzUtnC-G0jT0udsXShRneIlovqDbQ__ogKEYfO-yK4)
> > 
> > So the parser seems to think the table ends at the empty line, and tries to draw the top and bottom border of a table
> 
> 

Unfortunately, keeping track of tables(especially where they start or end) is kinda hard since there's too many `what-if` cases.

**Comment by Saecki** [comment]
I just now discovered that there already is the `tables.use_virt_lines` option, which fixes all the issues I described above :+1:
