### ISSUE TITLE
Changed color background in headers and codeblocks 

### ISSUE THREAD

**Issue by JoseMRodriguezM** [OXY2DEV/markview.nvim#40]
Hi guys. I'm having an issue with the headers and code blocks, I don't know why appears a line in a different colour in the background, like in the image. 

![image](https://github.com/OXY2DEV/markview.nvim/assets/76118394/af4fde6e-936b-4e1e-9a04-27bd5bd95d5a)

This is my configuration: 

````
return {
  "OXY2DEV/markview.nvim",
  dependencies = {
    "nvim-tree/nvim-web-devicons", -- Used by the code bloxks
  },

  config = function()
    require("markview").setup({
      headings = {
        shift_width = 0,

        heading_1 = {
          style = "label",

          padding_left = " ",
          padding_right = " ",

          corner_right = "",
          corner_right_hl = "decorated_h1_inv",

          icon = "󰼏  ",
          sign = "",
          hl = "decorated_h1",
        },
        heading_2 = {
          style = "label",

          padding_left = " ",
          padding_right = " ",

          corner_right = "",
          corner_right_hl = "decorated_h2_inv",

          icon = "󰎨  ",
          sign = "",
          hl = "decorated_h2",
        },
        heading_3 = {
          style = "label",

          padding_left = " ",
          padding_right = " ",

          corner_right = "",
          corner_right_hl = "decorated_h3_inv",

          icon = "󰼑  ",
          hl = "decorated_h3",
          sign = "",
        },
        heading_4 = {
          style = "label",

          padding_left = " ",
          padding_right = " ",

          corner_right = "",
          corner_right_hl = "decorated_h4_inv",

          icon = "󰎲  ",
          sign = "",
          hl = "decorated_h4",
        },
        heading_5 = {
          style = "label",

          padding_left = " ",
          padding_right = " ",

          corner_right = "",
          corner_right_hl = "decorated_h5_inv",

          icon = "󰼓  ",
          sign = "",
          hl = "decorated_h5",
        },
        heading_6 = {
          style = "label",

          padding_left = " ",
          padding_right = " ",

          corner_right = "",
          corner_right_hl = "decorated_h6_inv",

          icon = "󰎴  ",
          sign = "",
          hl = "decorated_h6",
        },
      },
      code_blocks = {
        enable = true,

        style = "language",
        hl = "dark",

        position = "overlay",

        min_width = 60,
        pad_amount = 3,

        language_names = {
          { "py", "python" },
          { "cpp", "C++" },
        },
        language_direction = "right",

        sign = false,
        sign_hl = nil,
      },
      inline_code = {},

      block_quote = {
        enable = true,
        default = {},
        callouts = {},
      },

      horizontal_rule = {},

      hyperlink = {},
      image = {},

      table = {

        table_hls = { "rainbow1" },
        use_virt_lines = false,
      },
      list_item = {
        marker_plus = {
          add_padding = false,
          marker = "•",
          marker_hl = "rainbow2",
        },
        marker_minus = {
          add_padding = false,
          marker = "•",
          marker_hl = "rainbow2",
        },
        marker_star = {
          add_padding = false,

          marker = "•",
          marker_hl = "rainbow2",
        },
      },
      checkbox = {},
      highlight_groups = {
        {
          group_name = "red",
          value = { bg = "#453244", fg = "#f38ba8" },
        },
        {
          group_name = "red_fg",
          value = { fg = "#f38ba8" },
        },

        {
          group_name = "orange",
          value = { bg = "#46393E", fg = "#fab387" },
        },
        {
          group_name = "orange_fg",
          value = { fg = "#fab387" },
        },

        {
          group_name = "yellow",
          value = { bg = "#464245", fg = "#f9e2af" },
        },
        {
          group_name = "yellow_fg",
          value = { fg = "#f9e2af" },
        },

        {
          group_name = "green",
          value = { bg = "#374243", fg = "#a6e3a1" },
        },
        {
          group_name = "green_fg",
          value = { fg = "#a6e3a1" },
        },

        {
          group_name = "blue",
          value = { bg = "#2E3D51", fg = "#74c7ec" },
        },
        {
          group_name = "blue_fg",
          value = { fg = "#74c7ec" },
        },

        {
          group_name = "mauve",
          value = { bg = "#393B54", fg = "#b4befe" },
        },
        {
          type = "normal",
          group_name = "mauve_fg",
          value = { fg = "#b4befe" },
        },
        {
          group_name = "grey",
          value = { bg = "#7E839A", fg = "#313244" },
        },
        {
          group_name = "grey_fg",
          value = { fg = "#7E839A" },
        },

        {
          group_name = "dark",
          value = { link = "KazCodeBlock" },
        },
        {
          group_name = "dark_2",
          value = { bg = "#303030", fg = "#B4BEFE" },
        },

        {
          group_name = "gradient_0",
          value = { fg = "#6583b6" },
        },
        {
          group_name = "gradient_1",
          value = { fg = "#637dac" },
        },
        {
          group_name = "gradient_2",
          value = { fg = "#6177a2" },
        },
        {
          group_name = "gradient_3",
          value = { fg = "#5f7198" },
        },
        {
          group_name = "gradient_4",
          value = { fg = "#5d6c8e" },
        },
        {
          group_name = "gradient_5",
          value = { fg = "#5b6684" },
        },
        {
          group_name = "gradient_6",
          value = { fg = "#59607a" },
        },
        {
          group_name = "decorated_h1",
          value = { bg = "#f38ba8", fg = "#313244", bold = true },
        },
        {
          group_name = "decorated_h1_inv",
          value = { fg = "#f38ba8", bold = true },
        },
        {
          group_name = "decorated_h2",
          value = { bg = "#fab387", fg = "#313244", bold = true },
        },
        {
          group_name = "decorated_h2_inv",
          value = { fg = "#fab387", bold = true },
        },
        {
          group_name = "decorated_h3",
          value = { bg = "#f9e2af", fg = "#313244", bold = true },
        },
        {
          group_name = "decorated_h3_inv",
          value = { fg = "#f9e2af", bold = true },
        },
        {
          group_name = "decorated_h4",
          value = { bg = "#a6e3a1", fg = "#313244", bold = true },
        },
        {
          group_name = "decorated_h4_inv",
          value = { fg = "#a6e3a1", bold = true },
        },
        {
          group_name = "decorated_h5",
          value = { bg = "#74c7ec", fg = "#313244", bold = true },
        },
        {
          group_name = "decorated_h5_inv",
          value = { fg = "#74c7ec", bold = true },
        },
        {
          group_name = "decorated_h6",
          value = { bg = "#b4befe", fg = "#313244", bold = true },
        },
        {
          group_name = "decorated_h6_inv",
          value = { fg = "#b4befe", bold = true },
        },
      },
    })
  end,
}
```

**Comment by OXY2DEV** [comment]
I can't reproduce the issue.

![Screenshot_2024-07-08-06-36-09-883_com.termux-edit.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/21c9e33d-a814-4864-8fcc-40ceead6a0e7)

**Comment by JoseMRodriguezM** [comment]
mmm what? I don't understand why I have this issue. I could be because my colorscheme?

**Comment by OXY2DEV** [comment]
> mmm what? I don't understand why I have this issue. I could be because my colorscheme?

Hard to tell. If your `Normal` group has something other than `bg` & `fg` then it could happen.

If you change the color scheme to something else and the issue disappears then yeah the colorscheme is causing the issue.

**Comment by JoseMRodriguezM** [comment]
I'm using kanagawa. This is my config:

return {
  -- add gruvbox
  { "ellisonleao/gruvbox.nvim" },
  {
    "rebelot/kanagawa.nvim", -- You can replace this with your favorite colorscheme
    lazy = false, -- We want the colorscheme to load immediately when starting Neovim
    priority = 1000, -- Load the colorscheme before other non-lazy-loaded plugins
    opts = {
      -- Replace this with your scheme-specific settings or remove to use the defaults
      transparent = false,
      terminalColors = true,
      background = {
        -- light = "lotus",
        dark = "wave", -- "wave, dragon"
      },
      colors = {
        theme = {
          all = {
            ui = {
              bg_gutter = "none",
            },
          },
        },
      },
    },
  },
  -- Configure LazyVim to load your prefered theme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "kanagawa",
    },
  },
}

**Comment by OXY2DEV** [comment]
> I'm using kanagawa. This is my config:
> 
> ```
> return {
>   -- add gruvbox
>   { "ellisonleao/gruvbox.nvim" },
>   {
>     "rebelot/kanagawa.nvim", -- You can replace this with your favorite colorscheme
>     lazy = false, -- We want the colorscheme to load immediately when starting Neovim
>     priority = 1000, -- Load the colorscheme before other non-lazy-loaded plugins
>     opts = {
>       -- Replace this with your scheme-specific settings or remove to use the defaults
>       transparent = false,
>       terminalColors = true,
>       background = {
>         -- light = "lotus",
>         dark = "wave", -- "wave, dragon"
>       },
>       colors = {
>         theme = {
>           all = {
>             ui = {
>               bg_gutter = "none",
>             },
>           },
>         },
>       },
>     },
>   },
>   -- Configure LazyVim to load your prefered theme
>   {
>     "LazyVim/LazyVim",
>     opts = {
>       colorscheme = "kanagawa",
>     },
>   },
> }
> ```

Just run `:colorscheme default` and see what happens.

**Comment by JoseMRodriguezM** [comment]
Nop, the problem continuous:

![image](https://github.com/OXY2DEV/markview.nvim/assets/76118394/8cf2f044-812f-49b0-a3a6-158819991935)

**Comment by JoseMRodriguezM** [comment]
Using gruvbox:

![image](https://github.com/OXY2DEV/markview.nvim/assets/76118394/e33d62d3-a795-4321-9276-5c2ae8ca1caa)

The same

**Comment by OXY2DEV** [comment]
> Nop, the problem continuous:
> 
> ![image](https://github.com/OXY2DEV/markview.nvim/assets/76118394/8cf2f044-812f-49b0-a3a6-158819991935)
> 

I have no idea what's happening. My looks different then yours(look at the normal text color).

![Screenshot_2024-07-08-08-40-42-361_com.termux-edit.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/d88db0f8-5d24-4c64-91e9-d56eba4ba105)

**Comment by JoseMRodriguezM** [comment]
Yep, me neither, the truth is that I don't know what to play anymore haha

**Comment by OXY2DEV** [comment]
> Yep, me neither, the truth is that I don't know what to play anymore haha

It might be coming from the colors being combined with the background.

But then again distros tend to do things(sometimes unconventional) to look like other popular IDEs(e.g. VS Code) so it could be a side effect of that.

You can do either 1 of 2 things,
1. Wait for the color related update(the next update) and see if the issue persists.
2. Tinker around with the highlight groups and see what works.

> Or you can go down the rabbit hole of trying to understand the source code of the distro and find out what is causing the issue.

**Comment by JoseMRodriguezM** [comment]
Ok, I will try to modify the highlights groups.

**Comment by JoseMRodriguezM** [comment]
Hi it's me again hahah, but now with news. I found a solution to my issue, and the thing is that I was having trouble with this: { import = "lazyvim.plugins.extras.lang.markdown" }, in my lazyvim configuration. So now I uninstalled it and everything is working awesome!. (Attached screenshot to show that is working perfectly)

![image](https://github.com/OXY2DEV/markview.nvim/assets/76118394/c3a3408b-b267-4bdd-984c-4e2605dfd92d)

**Comment by OXY2DEV** [comment]
> Hi it's me again hahah, but now with news. I found a solution to my issue, and the thing is that I was having trouble with this: { import = "lazyvim.plugins.extras.lang.markdown" }, in my lazyvim configuration. So now I uninstalled it and everything is working awesome!. (Attached screenshot to show that is working perfectly)
> 
> ![image](https://github.com/OXY2DEV/markview.nvim/assets/76118394/c3a3408b-b267-4bdd-984c-4e2605dfd92d)
> 

Then you can close the issue. I will add this to the wiki(later) for future users.

**Comment by JoseMRodriguezM** [comment]
Nice!!! It's gonna be useful
