### ISSUE TITLE
[Feature Request] Support opening links with ge, gx

### ISSUE THREAD

**Issue by bockel** [OXY2DEV/markview.nvim#43]
When a link is concealed, built-in gx or ge commands do not work as expected. You have to navigate the concealed text to guess where the link is. It would be nice to map the keys to have the expected action as long as the cursor is anywhere in the concealed region.

A workaround may be to navigate to one character before the end of the concealed text and execute the ge/gx command.
The following vim actions seem to give the expected results for standard markdown `[text](link)` links:
<kbd>f</kbd> + <kbd>)</kbd> + <kbd>h</kbd> + <kbd>ge</kbd>

**Comment by OXY2DEV** [comment]
Can you check the `dev` branch and see if `gx` works as expected?

**Comment by OXY2DEV** [comment]
As there is currently ways to open the links(with just `gx`). This issue will be closed.

**Comment by rodhash** [comment]
Hello @OXY2DEV 

Using this link as example:
```markdown
[hosts](/etc/hosts)
```

`gx` is opening the link with System editor (ie: sublime, vs code, etc).. is this expected?

In order to open the file in a new buffer I'm able to do that only by using `gf` or with `ge` as mentioned [here](https://github.com/OXY2DEV/markview.nvim/issues/43#issue-2395464132) in the first msg.

**Comment by OXY2DEV** [comment]
@rodhash can you try out the `dev` branch?

On the `main` branch, links are directly opened via `vim.ui.open()`. So, this is expected behavior.

The version in the `dev` branch can check if a file is a text file and open it inside Neovim.

>[!WARNING]
> In the `dev` branch, `MarkOpen` isn't available. However, `gx` works like before.

**Comment by rodhash** [comment]
> @rodhash can you try out the `dev` branch?
> 
> On the `main` branch, links are directly opened via `vim.ui.open()`. So, this is expected behavior.
> 
> The version in the `dev` branch can check if a file is a text file and open it inside Neovim.
> 
> Warning
> 
> In the `dev` branch, `MarkOpen` isn't available. However, `gx` works like before.

Thank you.. I was already using Dev branch for the other feature so I think I'll stick to it from now on : )
