### ISSUE TITLE
[BUG] Block quote callouts don't display correctly

### ISSUE THREAD

**Issue by Zeioth** [OXY2DEV/markview.nvim#45]
## Config
* nvim version: 0.10
* theme: default (or any other)
* os: arch linux

```lua
  {
    "OXY2DEV/markview.nvim",
    ft = { "markdown" },
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons"
    },
    opts = {}
  },
```

## What should happen
![block_quotes](https://github.com/OXY2DEV/markview.nvim/assets/3357792/6807b4cb-6211-4a11-b340-152d84af4d7f)

## What actually happen
As you can see the callouts are not applied.
![screenshot_2024-07-09_13-33-16_656701036](https://github.com/OXY2DEV/markview.nvim/assets/3357792/781a681b-8754-4fc9-a831-82ef2e876e80)

## How to reproduce
With the default config, paste the next text
```markdown
> Block qutes and callouts/alerts

> This is a normal block quote.
> It spans a few lines.
>
> It has gaps between lines.

> Important
> This is a callout.
> It has it's own custom style.

> A success callout with a custom title.
> Custom titles are also supported.

> Note
> Custom titles are also supported.

> Note
> You can also nest them.
>
> > Bug
> > Like this one
```

**Comment by Zeioth** [comment]
It works correctly thank you
![screenshot_2024-07-09_14-03-06_927200959](https://github.com/OXY2DEV/markview.nvim/assets/3357792/47b73215-0c02-4711-ba79-8be567172d80)

It would be a good idea to mention that at the top of:
https://github.com/OXY2DEV/markview.nvim/wiki/Block_quotes

example markdown
```
> [!SUCCESS]
> Text that goes below
```

**Comment by Zeioth** [comment]
It would be a good idea to mention that at the top of:
https://github.com/OXY2DEV/markview.nvim/wiki/Block_quotes

example markdown
```
> [!SUCCESS]
> Text that goes below
```

**Comment by OXY2DEV** [comment]
It actually is [right here](https://github.com/OXY2DEV/markview.nvim/wiki/Block_quotes#match_string).

But I guess it is a bit hard to spot.

**Comment by Zeioth** [comment]
@OXY2DEV I saw it and I didn't understand. Up to you but I would approach wiki pages like:

* What is this for
* Image
* How to use it

And then the options in detail as we are currently doing.

**Comment by OXY2DEV** [comment]
> @OXY2DEV I saw it and I didn't understand. Up to you but I would approach wiki pages like:
> 
> * What is this for
> * Image
> * How to use it + minimal copy pasteable markdown example.
> 
> And then the options in detail as we are currently doing.

The wiki is incomplete simply because a lot of the stuff may change in the later updates. So until things get stable-ish, they are gonna look like that.
