### ISSUE TITLE
List and checkbox don't blend with CursorLine

### ISSUE THREAD

**Issue by iovis** [OXY2DEV/markview.nvim#5]
Beautiful plugin, congrats!

I was exploring and I noticed the following when using `set cursorline` (maybe missing a `hl_mode = "combine"`?):

![IMG_0891](https://github.com/OXY2DEV/markview.nvim/assets/6660202/8f44b35e-bd63-48e8-a604-caaf57f6c632)

It also happens with table borders, but that actually looks kind of nice because it looks like it's highlighting each cell.

**Comment by OXY2DEV** [comment]
![Screenshot_2024-06-29-11-05-28-934_com termux-edit](https://github.com/OXY2DEV/markview.nvim/assets/122956967/d1cd0dcf-3744-4aa0-9136-6529d601b6ff)

This will be fixed in the next update.
