### ISSUE TITLE
Image submission

### ISSUE THREAD

**Issue by OXY2DEV** [OXY2DEV/markview.nvim#50]
If you have screenshots that you want to put in the README(and the wiki if relevant) then you can post them here.

The image should be any of the following types.

**Comment by scottmckendry** [comment]
Hello @OXY2DEV! Submitting the first demo image on this thread. Heres markview.nvim with all stock settings combined with [cyberdream.nvim](https://github.com/scottmckendry/cyberdream.nvim):

![image](https://github.com/user-attachments/assets/c4810505-a590-4049-a2fd-75281bb02714)

**Comment by OXY2DEV** [comment]
> ![image](https://github.com/user-attachments/assets/c4810505-a590-4049-a2fd-75281bb02714)

I just realized that horizontal rules don't consider textoff. Anyway, I fixed the issue now.

Can you take a new screenshot?

**Comment by scottmckendry** [comment]
Oh nice, thanks for that quick fix! I've updated my comment with a new screenshot 🙂

**Comment by OXY2DEV** [comment]
> Oh nice, thanks for that quick fix! I've updated my comment with a new screenshot 🙂 

Yep, much better.

**Comment by nebunebu** [comment]
![callouts](https://github.com/user-attachments/assets/f905df28-f2cc-47d1-ae4d-e2ea268b3c67)

![checkboxes](https://github.com/user-attachments/assets/b3dd765e-b273-4a88-86d5-2ed194e62590)

![codeblocks](https://github.com/user-attachments/assets/fccc48b0-19f1-4782-bfef-afbd4f5d5a5d)

![headings](https://github.com/user-attachments/assets/c59df0c1-577e-4c32-b29d-f61e5afb8d18)

![tables](https://github.com/user-attachments/assets/735b993a-32a7-4297-b31b-7cf77074bafd)

**Comment by OXY2DEV** [comment]
> 
> ![callouts](https://github.com/user-attachments/assets/f905df28-f2cc-47d1-ae4d-e2ea268b3c67)
> 
> ![checkboxes](https://github.com/user-attachments/assets/b3dd765e-b273-4a88-86d5-2ed194e62590)
> 
> ![codeblocks](https://github.com/user-attachments/assets/fccc48b0-19f1-4782-bfef-afbd4f5d5a5d)
> 
> ![headings](https://github.com/user-attachments/assets/c59df0c1-577e-4c32-b29d-f61e5afb8d18)
> 
> ![tables](https://github.com/user-attachments/assets/735b993a-32a7-4297-b31b-7cf77074bafd)
> 
> 

Thanks for sharing these screenshots!

I am currently busy so I haven't been able to do much. So, it may take a while before images are added.

These images will be added to the wiki pages.

**Comment by mosheavni** [comment]
you better not host the images on the repo.
check out:
https://www.reddit.com/r/neovim/comments/wsg5yx/attention_to_all_plugin_authors_newcomers_careful/

**Comment by OXY2DEV** [comment]
> you better not host the images on the repo. check out: https://www.reddit.com/r/neovim/comments/wsg5yx/attention_to_all_plugin_authors_newcomers_careful/

They are mostly stored in the `wiki` repo. So, I don't think anyone will know or accidentally download them.

Plus, there will be a different branch for images(as GitHub generated links break after a while) when thre are more images.

**Comment by OXY2DEV** [comment]
> > > you better not host the images on the repo. check out: https://www.reddit.com/r/neovim/comments/wsg5yx/attention_to_all_plugin_authors_newcomers_careful/
> > 
> > 
> > They are mostly stored in the `wiki` repo. So, I don't think anyone will know or accidentally download them.
> > Plus, there will be a different branch for images(as GitHub generated links break after a while) when thre are more images.
> 
> everyone downloads them when they install this plugin in their neovim setup. most plugin managers do a shallow clone of the repo and that contains the images. <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/17252601/352950263-479c69ec-ef3c-438f-a602-5b6decb2e0af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzg2NzQsIm5iZiI6MTcyMjIzODM3NCwicGF0aCI6Ii8xNzI1MjYwMS8zNTI5NTAyNjMtNDc5YzY5ZWMtZWYzYy00MzhmLWE2MDItNWI2ZGVjYjJlMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA3MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODEzZjQ4YWQ1NjM4ZjZiNzFkN2JhNTRmYzlkNjgzNTg2NGMxNDlmNWIxNWE5YWEwM2I0ZGE1Y2EzNDE4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w0HhDUD7wrV2cG6KHP4reQ9WSGiBVkaE2hQRzOpn6gE">
> 
> admittedly they are less than 1 MB but we don't need even this 1 MB on our laptops.

![Screenshot_2024-07-29-13-35-38-758_com termux-edit](https://github.com/user-attachments/assets/a8d4de43-4c7b-4a08-8a42-4067fdd48cef)

Actually ~3MB of images but those aren't downloaded.

**Comment by mosheavni** [comment]
> > > > you better not host the images on the repo. check out: https://www.reddit.com/r/neovim/comments/wsg5yx/attention_to_all_plugin_authors_newcomers_careful/
> > > 
> > > 
> > > They are mostly stored in the `wiki` repo. So, I don't think anyone will know or accidentally download them.
> > > Plus, there will be a different branch for images(as GitHub generated links break after a while) when thre are more images.
> > 
> > 
> > everyone downloads them when they install this plugin in their neovim setup. most plugin managers do a shallow clone of the repo and that contains the images. <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/17252601/352950263-479c69ec-ef3c-438f-a602-5b6decb2e0af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzg2NzQsIm5iZiI6MTcyMjIzODM3NCwicGF0aCI6Ii8xNzI1MjYwMS8zNTI5NTAyNjMtNDc5YzY5ZWMtZWYzYy00MzhmLWE2MDItNWI2ZGVjYjJlMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA3MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODEzZjQ4YWQ1NjM4ZjZiNzFkN2JhNTRmYzlkNjgzNTg2NGMxNDlmNWIxNWE5YWEwM2I0ZGE1Y2EzNDE4YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w0HhDUD7wrV2cG6KHP4reQ9WSGiBVkaE2hQRzOpn6gE">
> > admittedly they are less than 1 MB but we don't need even this 1 MB on our laptops.
> 
> ![Screenshot_2024-07-29-13-35-38-758_com termux-edit](https://private-user-images.githubusercontent.com/122956967/352956468-a8d4de43-4c7b-4a08-8a42-4067fdd48cef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzk4MzksIm5iZiI6MTcyMjIzOTUzOSwicGF0aCI6Ii8xMjI5NTY5NjcvMzUyOTU2NDY4LWE4ZDRkZTQzLTRjN2ItNGEwOC04YTQyLTQwNjdmZGQ0OGNlZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwNzUyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTUxMWVmNDM5YTQ2ZDNhOGRhNjkxODkyNWNiM2VhMjI0M2I1NTFjMmY2ZjQ3NDM0MWU2OWVmYTQxMjFiYTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UbVxIIq6QZkB6eKOIC2E2_MjXmYDArFcDcfRgIcigqo)
> 
> Actually ~3MB of images but those aren't downloaded.

if you can do this hack also to `images` folder, that would be best.
