### ISSUE TITLE
Works in :h Markview but no other markdown files

### ISSUE THREAD

**Issue by jprugel** [OXY2DEV/markview.nvim#53]
Honestly I hate having to post an issue, but I am not sure where else to put this and nothing in the logging is suggesting to me that it is my configuration error. Is this a bug or a feature?

Config file: https://hatebin.com/dgygjrpmlo

<img width="1728" alt="Screenshot 2024-07-12 at 11 02 41 PM" src="https://github.com/user-attachments/assets/60f19a5b-6c35-4d97-a9cd-8d0cb8fdc38e">

**Comment by OXY2DEV** [comment]
Why are you using the `LspAttach` event?

The plugin uses `ftplugin` to start so there should be no need to specify the event or lazy load it.

Does removing it fix the issue?

**Comment by OXY2DEV** [comment]
You can also try running `:Markview enable` to see if the plugin has registered the buffer or not.

**Comment by OXY2DEV** [comment]
It is caused by `LspAttach`.

![Screenshot_2024-07-13-09-14-47-817_com.termux-edit.jpg](https://github.com/user-attachments/assets/34a67212-bde6-4bee-96f4-432e9c0abd02)

**Comment by jprugel** [comment]
> Why are you using the `LspAttach` event?
> 
> The plugin uses `ftplugin` to start so there should be no need to specify the event or lazy load it.
> 
> Does removing it fix the issue?

So by default it does not get loaded, so I had to give it an event to load it, I suppose I could disable lazy loading for it so that it always loads, but that doesn't seem to align with how others have set it up

**Comment by OXY2DEV** [comment]
> So by default it does not get loaded,

Yes, because neovim will handle the lazy loading.

> so I had to give it an event to load it,

You don't need to do that either. There was a typo in the README that turned `ft = "markdown"` to `ft ="md"`. This causes lazy to not load the plugin correctly.

> I suppose I could disable lazy loading for it so that it always loads, but that doesn't seem to align with how others have set it up.

There is nothing to gain with Lazy loading as the plugin doesn't `require()` files or run functions when neovim starts.

**Comment by jprugel** [comment]
So just to clarify, was it my typo? Because as far as I remember I just copy pasted from the wiki. If it was my mistake, I'm sorry for wasting your time.

**Comment by OXY2DEV** [comment]
> So just to clarify, was it my typo? Because as far as I remember I just copy pasted from the wiki. If it was my mistake, I'm sorry for wasting your time.

No, like I said.

> There was a typo in the README that turned `ft = "markdown"` to `ft = { "md" }`.

The README wasn't updated so the typo was in the example.
