### ISSUE TITLE
Missing Highlight Support for ==text== Syntax

### ISSUE THREAD

**Issue by lethc** [OXY2DEV/markview.nvim#54]
I'm enjoying using your plugin and find it very helpful. However, I've noticed that highlight syntax (using ==a text==) doesn't seem to be supported.

**Comment by OXY2DEV** [comment]
That's simply due to `markdown` parser not recognizing it.

There's really not much I can do about it since without `Tree-sitter` doing the parsing it would be very slow to detect things from texts.

**Comment by lethc** [comment]
> That's simply due to `markdown` parser not recognizing it.
> 
> There's really not much I can do about it since without `Tree-sitter` doing the parsing it would be very slow to detect things from texts.

I see. I didn't know that. I thought it was possible because with obsidian.nvim it worked fine. I guess will have to wait for tree-sitter to support the highlights. Thanks for the information!
