### ISSUE TITLE
Make code block more configurable

### ISSUE THREAD

**Issue by fpohtmeh** [OXY2DEV/markview.nvim#55]
Other markdown viewers have the following defaults:
1. no language icon
2. language isn't coloured
3. language background is the same as code background
4. language is located in the right corner and has no code below.
![image](https://github.com/user-attachments/assets/3efe10d3-7a22-49b2-89bd-36abd89ff68e)

**Comment by OXY2DEV** [comment]
> Other markdown viewers have the following defaults:

The plugin isn't trying to mimic other markdown previewers. It doesn't use the same defaults.

> 1. no language icon

Did you even read the wiki? You can just disable the icons.

> 3. language background is the same as code background

That's an issue with `nvim-web-devicons`.

> 4. language is located in the right corner and has no code below.

You know, you can just add empty space?

**Comment by OXY2DEV** [comment]
I will be closing this issue.

Reasons:
- Configuration options for the icons are provided.
- Code block widths & paddings can be configured.
- Icons can be disabled.
- It is impractical to add more than 1 line of spacing as the top/bottom border.
