### ISSUE TITLE
Table columns aren't properly aligned if `code block` touches the symbol |

### ISSUE THREAD

**Issue by fpohtmeh** [OXY2DEV/markview.nvim#56]
This markdown leads to the issue
```
| `PUBLISH_S3_STG_DIR` | S3 path where stage build should be uploaded for publishing.                   |
| `PUBLISH_S3_PROD_DIR`| S3 path where production build should be uploaded for publishing.              |
```

Plugin version: fca6d732085c52637a03b594922f8c8e2d831823

**Comment by fpohtmeh** [comment]
![img](https://github.com/user-attachments/assets/6ed44a2f-8b3f-4f51-8d71-15f50e34fada)

**Comment by OXY2DEV** [comment]
![Screenshot_2024-07-15-16-11-03-219_com.termux.jpg](https://github.com/user-attachments/assets/19df4cdf-0ef1-4c88-9076-933a3342552e)

Cannot reproduce issue.

If you are using a `distro` you should first check what options they set for markdown (most likely explained in their wiki pages).
