### ISSUE TITLE
Not displaying backtick (`) in code blocks

### ISSUE THREAD

**Issue by jako4295** [OXY2DEV/markview.nvim#57]
**Describe the bug**
When following the discussion from the link below the backtick is not displayed inside the code block.
https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown

**Are you using a distro?**
No

**Expected behavior**
It is expected that if one types `` `a `` then we obtain a codeblock with `a. However the backtick is currently not displayed at all.

**Actual behavior**
Only ` a ` is currently displayed.

**Screenshots**
Screenshots are attached with how it looks in normal mode and insert mode
<img width="69" alt="Screenshot 2024-07-15 at 13 18 10" src="https://github.com/user-attachments/assets/9141ef70-84d5-4fca-b4f1-a04a1839c462">
<img width="42" alt="Screenshot 2024-07-15 at 13 18 21" src="https://github.com/user-attachments/assets/5c1200ba-031a-45e1-9d40-314edcf15bc7">

**Neovim version**
0.10.0

**Additional context**
markdown extensions are provided as a screenshot.
<img width="725" alt="Screenshot 2024-07-15 at 13 21 18" src="https://github.com/user-attachments/assets/4e84abe7-8cc2-45bc-b09e-73bd5cea8218">

**Comment by OXY2DEV** [comment]
First, `inline codes`(like this one) is different from code blocks.

---

Besides, That's just how neovim shows inline codes.

This is NOT done by the plugin. It is done by `treesitter`

You can temporarily disable the plugin if it's a problem. Or you can change the `concealcursor` option(this is a neovim option) to 3 to make it not hide them on the current line. Or you can use `options` in the setup function mentioned in the [wiki](https://github.com/OXY2DEV/markview.nvim/wiki/Plugin-setup)

**Comment by OXY2DEV** [comment]
![Uploading Screenshot_2024-07-15-19-54-04-984_com.termux-edit.jpg …]()

I still have not managed to reproduce your issue. You might have some other plugin that changes what is concealed.
