### ISSUE TITLE
Nested list items with indent size of 4

### ISSUE THREAD

**Issue by serhez** [OXY2DEV/markview.nvim#59]
**Describe the bug**
Nested list items are rendered at the same level of the parent if the indent size is 4. Perhaps the levels are calculated assuming an indent size of 2 spaces.

**Are you using a distro?**
No

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2. Open a `markdown` document.
3. Write a list item, followed by a child list item nested with 4 spaces.

**Expected behavior**
The child list items should be rendered with a deeper level (i.e., starting on a higher column number) than the parent.

**Actual behavior**
The parent and child list items are displayed on the same level. Additional child items are indented more than necessary.

**Screenshots**

![Screenshot 2024-07-18 at 15 48 18](https://github.com/user-attachments/assets/656ee084-dc68-45b9-8368-21612b452dec)
![Screenshot 2024-07-18 at 15 48 30](https://github.com/user-attachments/assets/af881063-5e41-4ddf-a207-640cfd9f4d81)

**Neovim version**
0.10.0

**Additional context**
N/A.

**Comment by OXY2DEV** [comment]
![Screenshot_2024-07-28-17-30-58-703_com termux-edit](https://github.com/user-attachments/assets/c62f0e90-b612-4a2d-8606-d2352578eef0)

Trees-sitter was responsible for this bug(due to showing different ranges for different list items).

Hopefully, now this issue shouldn't occur anymore.
