### ISSUE TITLE
Doesn't render pip tables correctly

### ISSUE THREAD

**Issue by raffaem** [OXY2DEV/markview.nvim#62]
**Describe the bug**

[pandoc's pip tables](https://pandoc.org/MANUAL.html#extension-pipe_tables) are not rendered correctly

**Are you using a distro?**
A linux distro or a neovim distro? I'm not using a neovim distro

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document with the following content
```
| **Holiday n. 1** |            |
|:-----------------|:-----------|
| Start            | 2024-06-03 |
| End              | 2024-06-18 |
| Accounting       | 2024-06-25 |

| **Holiday n. 2** |            |
|:-----------------|:-----------|
| Start            | 2024-06-03 |
| End              | 2024-06-18 |
| Accounting       | 2024-06-25 |
```
**Expected behavior**
The table should be rendered correctly

**Actual behavior**
The table is rendered incorrectly, with the last horizontal line of the first table shifted to the right and no last line at all for the second table

**Screenshots**
![image](https://github.com/user-attachments/assets/4e51de85-66e6-4e4e-8117-d1c35fde75c7)

**Neovim version**
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by saecki** [comment]
`tables.use_virt_lines` should fix some of the  issues. The misalignment in the table header seems to stem from the bold text.

**Comment by OXY2DEV** [comment]
Overlapping can be fixed by using `use_virt_lines`(which you have fixed).

The other issue should be fixed in the next commit.
