### ISSUE TITLE
Table not display properly

### ISSUE THREAD

**Issue by faea726** [OXY2DEV/markview.nvim#66]
**Issue**
The last row of table has display issue

OS: Window
Terminal: Window Terminal
nvim -v: 0.10
Distro: NvChad
Font: Hack Nerd Font (download from [here](https://www.nerdfonts.com/font-downloads))

![image](https://github.com/user-attachments/assets/81995f36-4c46-43fc-bab6-fa0065a7a2de)
![image](https://github.com/user-attachments/assets/4bc3dc9c-cb7c-4f4e-8986-dee8f7096202)

**Comment by OXY2DEV** [comment]
That's a font issue. Please use a proper nerd font(or any *modern* font that supports Unicode characters).

**Comment by faea726** [comment]
> That's a font issue. Please use a proper nerd font(or any _modern_ font that supports Unicode characters).

Could you suggest some?
I download my font from [here](https://www.nerdfonts.com/font-downloads). they're all nerdfront that support unicode characters.

**Comment by OXY2DEV** [comment]
Did you try something like `JetBrainsMono`(the one I am using)?

It could also be a terminal rendering issue. But these are **Unicode characters**(they also work in normal fonts) so this shouldn't be the cause.

You can try changing the fonts to see if it works or not.

**Comment by faea726** [comment]
> Did you try something like `JetBrainsMono`(the one I am using)?
> 
> It could also be a terminal rendering issue. But these are **Unicode characters**(they also work in normal fonts) so this shouldn't be the cause.
> 
> You can try changing the fonts to see if it works or not.

It works fine with `JetBrainsMono Nerd Font`
![image](https://github.com/user-attachments/assets/45914c3f-6545-4955-863e-e10cc8d77d8f)

Broken when use `Hack Nerd Font`
![image](https://github.com/user-attachments/assets/5b8b8727-10e5-4c6c-bf33-4f7f3159fb5f)

**Comment by OXY2DEV** [comment]
If you have 2`fontForge` you can use that to fix the issue(it might require a bit knowledge and some trial & errors to fix).

Alternatively, if there are maintainers of that font you can ask them to fix it. I don't know if the `nerd-font` repo owners actively maintain the front or not(or if they even take font issues in GitHub). So, take this with a grain of 🧂.

**Comment by faea726** [comment]
I think the real problem is: `JetBrainsMono` is a **ligatures font**. And `Hack` is not.
