### ISSUE TITLE
Make icons optional instead of a requirement

### ISSUE THREAD

**Issue by datsfilipe** [OXY2DEV/markview.nvim#68]
This is probably a weird request but I found the icons to be a bit annoying (I normally don't use them in the plugins I have).

Would it be possible to make the icons optional? and the `nvim-web-devicons` dependency could also be optional.

**Comment by OXY2DEV** [comment]
> Would it be possible to make the icons optional? and the `nvim-web-devicons` dependency could also be optional.

It is already possible. [Check the wiki page](https://github.com/OXY2DEV/markview.nvim/wiki/Code-blocks#options), you will need to change the style to something you like.

For example,
```lua
code_blocks = {
  style = "minimal",
  hl = "Col7",

  min_width = 60
}
```
>[!TIP]
> You should change the value of `hl` to something you like(as it will be removed in the next update).

**Comment by datsfilipe** [comment]
oh ok! still think it should be easier, but if it's possible already it's fine
