### ISSUE TITLE
Cannot remove operator-pending mode concealment (modes setting)

### ISSUE THREAD

**Issue by roginfarrer** [OXY2DEV/markview.nvim#70]
**Describe the bug**

Setting `modes = {'n'}` to remove operator-pending mode doesn't work (i.e., plugin still conceals in operator-pending mode.

**Are you using a distro?**
No

**To Reproduce**
1.  Install `markview.nvim`
2. Use the following config:
    ```lua
    require('markview').setup{ modes = { 'n' }}
    ```
4.  Open a `markdown` document.

**Expected behavior**
If I hit `c`, `d`, `y`, etc, the concealment should drop

**Actual behavior**
Concealment still applies

**Neovim version**
0.10.0

**Additional context**
I can reproduce without any other plugins installed (aside from plugin's dependencies).

**Comment by OXY2DEV** [comment]
That's because neovim doesn't `redraw` the screen during that mode.

So, even though everything is cleared you will still see them

**Comment by roginfarrer** [comment]
Ah! `markdown.nvim` supported disabling in operator mode, so I assumed it was a plugin issue. I see that you've found a workaround, though. Thanks!

**Comment by OXY2DEV** [comment]
> Ah! `markdown.nvim` supported disabling in operator mode, so I assumed it was a plugin issue. I see that you've found a workaround, though. Thanks!

You can try using the dev branch if you *really* need it.

**Comment by OXY2DEV** [comment]
The issue will be closed now
