### ISSUE TITLE
Feature request: allow using language name instead of file extension for code block

### ISSUE THREAD

**Issue by mawkler** [OXY2DEV/markview.nvim#72]
Hi! First of all, thanks for creating an awesome Markdown plugin!

Currently, it seems that I have to specify the file extension when creating code blocks, and that using the language name doesn't work.

This doesn't work:

````markdown
```rust
fn main() {}
```
````

But this does:

````markdown
```rs
fn main() {}
```
````

I noticed the option `code_blocks.language_names` that allows the user to manually fix what language name is displayed, but I still seem to have to write the file extension.

Shouldn't it be possible to support language names natively as well? For one, [markdown.nvim](https://github.com/MeanderingProgrammer/markdown.nvim) supports this.

**Comment by OXY2DEV** [comment]
The only reason for this strange-ness is due to using `nvim-web-devicons`. I plan on moving away from that plugin in the next update.

**Comment by mawkler** [comment]
Thank you very much!

**Comment by mawkler** [comment]
@OXY2DEV I tried c9b4f77, but it seems like the nvim-web-devicons icon still doesn't appear for Rust code blocks like this one:

````markdown
```rust
fn main() {}
```
````

If it's of any help, [this is how render-markdown.nvim (previously markdown.nvim) fetches its icons for code blocks](https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/main/lua/render-markdown/icons.lua#L9-L18). It seems to just call `require('nvim-web-devicons').get_icon_by_filetype(language)` and doesn't seem to have to hard code a file extension to language mapping.

**Comment by OXY2DEV** [comment]
> @OXY2DEV I tried [c9b4f77](https://github.com/OXY2DEV/markview.nvim/commit/c9b4f77e880eb0ab9afd370ad82e3758513a4a3a), but it seems like the nvim-web-devicons icon still doesn't appear for Rust code blocks like this one:
> 
> ```
> ```rust
> fn main() {}
> ```
> ```
> 
> If it's of any help, [this is how render-markdown.nvim (previously markdown.nvim) fetches its icons for code blocks](https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/main/lua/render-markdown/icons.lua#L9-L18). It seems to just call `require('nvim-web-devicons').get_icon_by_filetype(language)` and doesn't seem to have to hard code a file extension to language mapping.

That's less of an issue with `markview` and more of an issue of `devicons`.

The commit does the opposite of what you are doing.

So if you type `rs` it would show `Rust`.

**Comment by mawkler** [comment]
@OXY2DEV I see. Is there any chance that you could support code blocks with the true language name as well? I would argue that is much more common than writing the file extension (which I didn't even know was supported by Treesitter).

**Comment by OXY2DEV** [comment]
I will even if you didn't say it.

**Comment by mawkler** [comment]
@OXY2DEV Ok, thank you!

**Comment by mawkler** [comment]
@OXY2DEV It seems like the nvim-web-devicon is still missing for Rust code blocks:

````markdown
```rust
fn main() {}
```
`````

I've tested with the default recommended lazy.nvim config.

**Comment by OXY2DEV** [comment]
> @OXY2DEV It seems like the nvim-web-devicon is still missing for Rust code blocks:
> 
> ```
> ```rust
> fn main() {}
> ```
> ```
> 
> I've tested with the default recommended lazy.nvim config.

That's cause I'm stupid 💀.
