### ISSUE TITLE
HRs use the screen width when they should be using window width

### ISSUE THREAD

**Issue by jakesarjeant** [OXY2DEV/markview.nvim#73]
**Describe the bug**
HRs are rendered with the width of the whole terminal screen, so when an HR is in a buffer/window that is smaller than the whole screen, the center point is rendered too far to the right or sometimes even off-screen

**Are you using a distro?**
No

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a markdown file
3. Type `---`
4. Run `:vsplit`

**Expected behavior**
The center (diamond) of the HR is centered in the window

**Actual behavior**
The diamond is centerd on the screen

**Screenshots**
<img width="1280" alt="Screenshot 2024-08-05 at 13 20 20" src="https://github.com/user-attachments/assets/5a2c1fe6-3016-43b7-aee4-fa1912bbe44c">

**Neovim version**
0.10.0

**Additional context**
N/A

**Comment by OXY2DEV** [comment]
Unfortunately this doesn't work well.

Let's say you open a file and use `:vsp` in that case which window will the plugin look at? Extmarks will be placed on the buffer itself.

So, regardless of what I do at least 1 window will have incorrect width of HR.

Plus, this wouldn't work when resizing and if it did that would be performance issues on larger files.

**Comment by jakesarjeant** [comment]
@OXY2DEV Right, but at least in the case where the buffer is only open in one window, shouldn't the diamond be centered?

I'll admit that having the same buffer open in two windows is not the most useful anyway. Still -- it could just be centered to whichever window is active

**Comment by OXY2DEV** [comment]
That's caused by `textoff`. Again, different windows can have different textoff(and initially the value will be 0 regardless of the actual width of the statuscolumn) so it's next to impossible to do it.
