### ISSUE TITLE
Add Title highlight group for table header

### ISSUE THREAD

**Issue by ColinKennedy** [OXY2DEV/markview.nvim#76]
[MeanderingProgrammer/render-markdown.nvim](https://github.com/MeanderingProgrammer/render-markdown.nvim) highlights the top of the table using a colorscheme's (I think) Title highlight group and the body is probably Text or some other "normal text" color., it'd be nice if this plugin also had separate highlight groups for title and body and linked those highlight groups to Neovim's built-ins so that colorschemes can reuse their existing colors

## render-markdown.nvim plugin
![image](https://github.com/user-attachments/assets/084d5a17-884e-4223-acb7-64db01e47c3f)

## Current markview.nvim plugin
![image](https://github.com/user-attachments/assets/c6a8dcb7-c24e-426d-922a-6995da2597a5)

**Comment by OXY2DEV** [comment]
There's a dedicated highlight group just for this.

Why would I reinvent the wheel?

![Screenshot_2024-08-05-19-31-41-248_com termux-edit](https://github.com/user-attachments/assets/4e090ba4-3b34-4e88-aa4b-a43a90e19bdd)

**Comment by ColinKennedy** [comment]
The colorscheme in question already has a color for @markup.heading.markdown & TItle

![image](https://github.com/user-attachments/assets/03abf31a-975a-456d-a11d-c3cea98738b2)

The issue from what I can see is that markview.nvim does not respect the existing color. MarkviewTableBorder is a solid color where I would've expected it to be `highlight link MarkviewTableBorder Title`. (This seems to be a bug)

(Feature request) Also it'd be nice if the title portion has a different highlight group from the body so that different colors for the table can be achieved like in the screenshot I'd posted from render-markdown.nvim

**Comment by OXY2DEV** [comment]
Markview doesn't even add any color to the text so I don't understand how that would be an issue.

Linking wouldn't solve any problem as the plugin only applies highlight groups to the border(not whatever is inside the cell).

All of the colorschemes I have already displays the heading in a different color.

![Screenshot_2024-08-05-19-31-41-248_com termux-edit](https://github.com/user-attachments/assets/5784bfb8-bb6f-42a2-9e89-79ee8e527a58)
![Screenshot_2024-08-05-19-49-01-620_com termux-edit](https://github.com/user-attachments/assets/1ff85386-51e9-4013-a7db-66415d7d1759)
![Screenshot_2024-08-05-19-49-19-593_com termux-edit](https://github.com/user-attachments/assets/d0a1dda1-21b4-454f-a014-3811bcec72f9)
![Screenshot_2024-08-05-19-49-53-095_com termux-edit](https://github.com/user-attachments/assets/e9c727a2-bc97-4f75-9ccf-86f1fc12cf38)

**Comment by OXY2DEV** [comment]
If you are asking about why the heading color is not applied to the border then that's because of a simple reason.

A lot of the colorschemes don't have the heading group so everything looks white in those cases. And it's hard to keep track of since some colorschemes will just straight up set it to a color making it hard to detect if a colorscheme has support for it or not.

**Comment by ColinKennedy** [comment]
As shown in my previous screenshots (at the bottom of each screenshot), the colorscheme defines the heading group and it links to Title so the colorscheme does define the necessary colors.

I checked out the source code:
https://github.com/OXY2DEV/markview.nvim/blob/7049a68dfaea0cad7d6be10111fb3b1f554c7be4/lua/markview.lua#L771-L784

It's blue in my screenshot because markview prefers `@comment.note` before checking for `Title`, which is fine since users can change it to something else in our own configurations. That's also the reason why the color changes when you load as different color schemes.

Still, it'd be really nice if we can have separate color options for the table title vs its body. As far as I can see, there's only `MarkviewTableBorder`. Would adding `MarkviewTableBorderTitle` or similar be acceptable?

**Comment by OXY2DEV** [comment]
You can do the exact thing with 5 lines of code.

```lua
tables = {
  hl = {
    "Title", "Title", "Title", "Title",
    "TableBorder", "TableBorder", "TableBorder", "TableBorder",  
    "TableBorder", "TableBorder", "TableBorder", "TableBorder",
    "TableAlignLeft", "TableAlignRight", "TableAlignCenter", "TableAlignCenter",
  }
}
```

**Comment by OXY2DEV** [comment]
```lua
tables = {
		text = {
			"╭", "─", "╮", "┬",
			"├", "│", "┤", "┼",
			"╰", "─", "╯", "┴",

			"╼", "╾", "╴", "╶"
		},
		hl = {
			"Title", "Title", "Title", "Title",
			"MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder",
			"MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder",

			"MarkviewTableAlignLeft", "MarkviewTableAlignRight", "MarkviewTableAlignCenter", "MarkviewTableAlignCenter"
		},

		use_virt_lines = true
	},
```

**Comment by ColinKennedy** [comment]
I tried out the configuration you'd recommended. This is the visual result

![image](https://github.com/user-attachments/assets/2a39d548-3a9a-4fc6-b599-53cbee4f08ed)

I also tried changing the values around

```
                            "Title", "Title", "Title", "Title",
                            "Title", "MarkviewTableBorder", "Title", "Title",
                            "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder",
```

![image](https://github.com/user-attachments/assets/46d2fdd7-89b7-40a7-9322-072ec623badf)

This was the closest I could get without the title spilling over into the body section.

e.g.

```
                            "Title", "Title", "Title", "Title",
                            "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder",
                            "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder",
```

![image](https://github.com/user-attachments/assets/3f898e3a-e3cb-469a-9bae-9db11afb3792)

```
                            "Title", "Title", "Title", "Title",
                            "Title", "Title", "Title", "Title",
                            "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder", "MarkviewTableBorder",
```

![image](https://github.com/user-attachments/assets/cfae4fb7-0f84-4837-9a48-5238e100d7c7)
