### ISSUE TITLE
Some flavors of Markdown code blocks do not render correctly.

### ISSUE THREAD

**Issue by mehalter** [OXY2DEV/markview.nvim#77]
**Describe the bug**
Some flavors of markdown such as Quarto/RMarkdown add on some extra syntactic sugar onto code blocks. The Markdown treesitter parser actually handles them all correctly, so it would be nice if this plugin also supported some of these.

Here are some examples of some valid markdown code block definitions:

```
```{lang_name}
```

```
```{{lang_name}}
```

```
```lang_name title="some allow extra options"
```

**Are you using a distro?**
In general, yes. But reproducible with a completely clean environment with only `markview.nvim` installed.

**To Reproduce**
1. Install `markview.nvim`.
2. Open a `markdown` document.
3. Create a code block using one of the syntaxes above
4. See that it doesn't parse the language properly
5. Use `:InspectTree` and see that the `language` node and `info_text` nodes are parsed correctly indicating it's valid in the markdown parser

**Expected behavior**
It to parse nicely

**Actual behavior**
The language is unable to be parsed

**Screenshots**
![2024-08-05_09:48:57_screenshot](https://github.com/user-attachments/assets/8c15d308-8cfe-4b42-9ab7-66843e9cd9da)
![2024-08-05_09:48:47_screenshot](https://github.com/user-attachments/assets/e39fd2a7-0976-4f5f-88b0-b93fa9d13ff4)

**Neovim version**
0.10.1

**Additional context**

Just a simple start to this support could be simply updating the lua pattern that is matched here: https://github.com/OXY2DEV/markview.nvim/blob/main/lua/markview/parser.lua#L211

to `"%s*```{*([^%s,}]*)"`

With this change the above screenshot looks like this:
![2024-08-05_09:49:43_screenshot](https://github.com/user-attachments/assets/aa631863-91b1-46d9-ae8c-5fb59a1209a5)

It would be nice if it replaced the entire `info_string` treesitter node rather than just the language text
which leaves the extra parameters dangling at the end, or some way to nicely format them (granted this isn't super necessary)

**Comment by OXY2DEV** [comment]
I will see what I can do
