### ISSUE TITLE
feat: no top/bottom table border

### ISSUE THREAD

**Issue by davidosomething** [OXY2DEV/markview.nvim#79]
**Describe the bug**
adding top and bottom border to tables introduces vertical shift when switching between insert and normal mode, it's a little annoying

[Screencast_20240805_114901.webm](https://github.com/user-attachments/assets/89889405-8bf5-4e01-921f-c6860a45e532)

would like just the inner lines to be rendered as box drawing characters
 
**Are you using a distro?**
No

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document.

**Expected behavior**
What is expected to happen.

**Actual behavior**
What actually happens.

**Screenshots**
If it's a visual glitch then screenshots are a **must**.

**Neovim version**
0.10.0

**Additional context**
E.g. other plugins that you use with this one.

**Comment by OXY2DEV** [comment]
Can you try adding this to your config?

```lua
tables = {
  use_virt_lines = false
}
```

**Comment by davidosomething** [comment]
on dev branch with that setting:

![image](https://github.com/user-attachments/assets/ebd13f6d-cbc7-493c-a9c9-043b1a6cba3b)

**Comment by OXY2DEV** [comment]
What's your conceallevel?

**Comment by davidosomething** [comment]
`conceallevel=0`

**Comment by OXY2DEV** [comment]
The plugin needs a conceallevel of 2 or higher.

**Comment by davidosomething** [comment]
here' it is with use_virt_lines = false and conceallevel=2
![image](https://github.com/user-attachments/assets/f79dabfd-6efd-4ebf-b94d-9f1ad32871a3)

it actually looks fine with conceallevel=0 and no `use_virt_lines` setting
![image](https://github.com/user-attachments/assets/782841f6-276f-4e73-a814-e592d45726d4)

btw, it's this virtual text i want to skip rendering:
![image](https://github.com/user-attachments/assets/719e5ca6-de31-4a0f-b68e-5281345f9583)
i like the left, middle, and right lines, just not the top and bottom sides of the table like this:
![image](https://github.com/user-attachments/assets/c6471744-d223-4599-9b51-0a74821b4a36)

**Comment by OXY2DEV** [comment]
You can try adding this to your config.

```lua
tables = {
  block_decorator = false
}
```

**Comment by davidosomething** [comment]
works! no more vertical movement! thanks so much

[Screencast_20240806_003128.webm](https://github.com/user-attachments/assets/1f35a8b1-bb7d-490d-a2db-e18831532136)
