### ISSUE TITLE
Invalid 'line': out of range when rendering a table

### ISSUE THREAD

**Issue by fuelen** [OXY2DEV/markview.nvim#8]
Table:
```markdown
| **text**   | link                             |
|------------|----------------------------------|
| **link1**  | N/A                              |
| **link2**  | [example](https://example.com/)  |
```

**Comment by OXY2DEV** [comment]
This has been fixed in the `dev` branch

**Comment by fuelen** [comment]
Actually, I wanted to report another issue but caught the error mentioned above while preparing the example :slightly_smiling_face: 

I wanted to report on the rendering issue when a link is present in the table

![image](https://github.com/OXY2DEV/markview.nvim/assets/588762/d633313d-c27c-46ca-8ed4-38ae84c5e75e)

**Comment by OXY2DEV** [comment]
That's actually only 1 of the bugs(there's one for *italics*, **bolds**, **italic bolds**, __ones using underscore instead of asterisks__, image links, hyperlinks, code blocks and basically everywhere neovim conceals by default).


I have to refactor entire code for making tables(again).

**Comment by TarunDaCoder** [comment]
Hello, I am facing a similar issue, but with `invalid 'col': out of range` when I try to render a code block.

**Comment by OXY2DEV** [comment]
> Hello, I am facing a similar issue, but with `invalid 'col': out of range` when I try to render a code block.

Do you happen to have the code block nested inside something else?

Or do you have some line in the the code block that is empty(or misaligned with the rest of the text)?

> Also you should provide a screenshot and what you wrote when you face an issue.
