### ISSUE TITLE
links disabled still conceals

### ISSUE THREAD

**Issue by davidosomething** [OXY2DEV/markview.nvim#80]
**Describe the bug**

have set `links = { enable = false }`
icons are no longer rendered (like the image icon), but the plugin still does fancy stuff to links
 
[Screencast_20240806_004103.webm](https://github.com/user-attachments/assets/8c4d0756-2fe7-42e9-9c6b-5ae97b85b183)

**Are you using a distro?**
No

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document.

**Expected behavior**
What is expected to happen.

**Actual behavior**
What actually happens.

**Screenshots**
If it's a visual glitch then screenshots are a **must**.

**Neovim version**
0.10.0

**Additional context**
E.g. other plugins that you use with this one.

**Comment by OXY2DEV** [comment]
That's a feature provided by `tree-sitter` not much I can do.

**Comment by davidosomething** [comment]
i mean i still want the `[brackets]`
