### ISSUE TITLE
QUESTION: how to activate hybrid mode

### ISSUE THREAD

**Issue by verajosemanuel** [OXY2DEV/markview.nvim#82]
**Describe the bug**
cant find in documentation how to work using hybrid mode

**Are you using a distro?**
No

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document.
3. write some markdown

**Expected behavior**
i expect hybrid mode running

**Actual behavior**
i only see rendered markdown when exiting edit mode

**Neovim version**
0.10.0

**Comment by OXY2DEV** [comment]
Check the [README on the dev branch](https://github.com/OXY2DEV/markview.nvim/tree/dev?tab=readme-ov-file#-hybrid-mode).
