### ISSUE TITLE
[Bug]: links are not presented as raw when using hybrid-mode in Normal mode 

### ISSUE THREAD

**Issue by mcauley-penney** [OXY2DEV/markview.nvim#86]
**Describe the bug**
When using hybrid-mode with normal mode (`hybrid_modes = { 'n' }`), links are not derendered correctly.

**Are you using a distro?**
No

**To Reproduce**
1. Install `markview.nvim`.
2. Configure `markview.nvim` with `hybrid_modes = { 'n' }`
3. Open a `markdown` document.
4. put your cursor on a link.

**Expected behavior**
The link will completely derender, showing the raw text.

**Actual behavior**
Only the link icon is removed.

**Screenshots**
![markview-link](https://github.com/user-attachments/assets/aa95ed55-56d5-49a0-8039-e1b7a6926633)

**Neovim version**
```
NVIM v0.11.0-dev-554+g3bc864e77
Build type: Release
LuaJIT 2.1.1720049189
```

**Additional context**
N/A

**Comment by OXY2DEV** [comment]
This is not a bug. This is the default behavior of `conceal`.

To overwrite this behavior you can add this to your config.

```lua
{
  callbacks = {
    on_enable = function (_, win)
      vim.wo[win].conceallevel = 2;
      -- You need to add the short name of the modes where you want everything under the cursor be concealed.
      -- E.g. "nc" will make it conceal under the cursor on normal & command mode. On the other hand, "" will make it never conceal anything under the cursor.
      vim.wo[win].concealcursor = "";
   end
}
```

**Comment by mcauley-penney** [comment]
I didn't know this and I think this is reasonable, thank you.

I normally agree with adhering with the default behavior but it's hard to foresee someone not wanting to drop the entire conceal on hovering when using 'n' in the hybrid-mode table. This *feels* like it should be the default behavior when using that option.

**Comment by OXY2DEV** [comment]
> This _feels_ like it should be the default behavior when using that option.

That's because `hybrid_mode` isn't a default behavior as I have no idea whether it helps or just gets in the way. If this was a default then it would be very annoying to look at(because only the concealment will be removed, the virtual texts will stay).

**Comment by mcauley-penney** [comment]
> If this was a default then it would be very annoying to look at(because only the concealment will be removed, the virtual texts will stay)

I don't think this is true. I'm using the hybrid-mode with the callback you gave to remove both concealment *and virtual text* on hover and insert mode. I'm doing this because not having conceal removed when hovering a link makes it difficult to yank the URL or `gx` to follow it. It also makes it more annoying to modify concealed text in general, like headings.

Furthermore, I've done this specifically to have as little visual jitter as possible. The default settings cause a lot of visual changes when editing the document because all rendering is removed every time the user enters insert mode. With the below config, the rendering stays on every line but the current one, whether the user is in insert or normal. This makes sense to me because I typically don't need to see the raw text in other parts of the document, just the raw text I'm editing.

### defaults

Editing and yanking links:
![markview-default](https://github.com/user-attachments/assets/52ee2635-bc31-4106-bdc2-af712a950258)

### custom configuration

Editing headings and links, yanking links:
![markview-custom](https://github.com/user-attachments/assets/73b23fd8-ee4b-4eeb-a774-35250b6dcf1a)


My configuration is:

```
{
    "OXY2DEV/markview.nvim",
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons"
    },
    config = {
      modes = { "n", "no", 'i' },
      hybrid_modes = { 'n', 'i' },
      headings = {
        shift_width = 0
      },
      list_items = {
        enable = false,
        marker_minus = {
          add_padding = false,
        },
        marker_plus = {
          add_padding = false,
        },
        marker_star = {
          add_padding = false,
        }
      },
      callbacks = {
        on_enable = function(_, win)
          vim.wo[win].conceallevel = 2;
          vim.wo[win].concealcursor = "";
        end
      }
    }
  }
```

**Comment by OXY2DEV** [comment]
> I don't think this is true. I'm using the hybrid-mode with the callback you gave to remove both concealment and virtual text on hover and insert mode. I'm doing this because not having conceal removed when hovering a link makes it difficult to yank the URL or gx to follow it. It also makes it more annoying to modify concealed text in general, like headings.

You are misunderstanding the issue. The issue happens when you have a `concealcursor` value but don't use `hybrid-mode`.

**Comment by mcauley-penney** [comment]
That's why I said in my original message that "This feels like it should be the default behavior when using that option." What I meant was that the conceal options should be the default *when using the hybrid-mode option*.

**Comment by OXY2DEV** [comment]
> That's why I said in my original message that "This feels like it should be the default behavior when using that option." What I meant was that the conceal options should be the default _when using the hybrid-mode option_.

Fair enough.
