### ISSUE TITLE
Coloured heading background have disappeared after an update

### ISSUE THREAD

**Issue by kamack38** [OXY2DEV/markview.nvim#87]
**Describe the bug**

**Are you using a distro?**
Yes, NvChad

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Install `markview.nvim`.
2.  Open a `markdown` document.

**Expected behaviour**
It should look as in the README

**Actual behaviour**
![image](https://github.com/user-attachments/assets/4368870a-a267-4c63-a879-d07de933cb1e)

**Neovim version**
0.10.1

**Comment by OXY2DEV** [comment]
Are you using a transparent colorscheme?

If yes then the background won't be applied since the plugin won't have a background color to work with.

**Comment by kamack38** [comment]
> Are you using a transparent colorscheme?
> 
> If yes then the background won't be applied since the plugin won't have a background color to work with.

I don't really know. But everything has been working till I updated the plugin. Is there any way to go back the way things were?

**Comment by OXY2DEV** [comment]
> I don't really know.

Just send a screenshot.

> But everything has been working till I updated the plugin. Is there any way to go back the way things were?

Which branch are you using?

**Comment by kamack38** [comment]
![image](https://github.com/user-attachments/assets/0618f465-dcab-49e7-8b40-24857c758814)

I'm using the main branch

**Comment by OXY2DEV** [comment]
> ![image](https://private-user-images.githubusercontent.com/64226248/355596272-0618f465-dcab-49e7-8b40-24857c758814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzcxNDIsIm5iZiI6MTcyMjk3Njg0MiwicGF0aCI6Ii82NDIyNjI0OC8zNTU1OTYyNzItMDYxOGY0NjUtZGNhYi00OWU3LThiNDAtMjQ4NTdjNzU4ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDIwNDA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYTlhOTIxZmE3OTU3YWE3Mjc1MWU1Y2IxODM4MzdlZjMzYzRlZGU1NmFkNmY4NGZjOTg4YTFiN2IwZmNhNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WtHBk-QK9fC051Wk9K4_XSoG5HH5F7urdJj1_EhUlKI)
> 
> I'm using the main branch

Transparent colorschemes don't have background colors. So, the plugin can't calculate the colors for the background.

That's why they are not showing up.

**Comment by kamack38** [comment]
I was able to fix it using this:
```lua
      vim.api.nvim_set_hl(0, "MarkviewHeadin1", { bg = "#453244", fg = "#f38ba8" })
      vim.api.nvim_set_hl(0, "MarkviewHeadin1Label", { fg = "#f38ba8" })
      vim.api.nvim_set_hl(0, "MarkviewHeading2", { bg = "#46393E", fg = "#fab387" })
      vim.api.nvim_set_hl(0, "MarkviewHeading2Label", { fg = "#fab387" })
      vim.api.nvim_set_hl(0, "MarkviewHeading3", { bg = "#464245", fg = "#f9e2af" })
      vim.api.nvim_set_hl(0, "MarkviewHeading3Label", { fg = "#f9e2af" })
      vim.api.nvim_set_hl(0, "MarkviewHeading4", { bg = "#374243", fg = "#a6e3a1" })
      vim.api.nvim_set_hl(0, "MarkviewHeading4Label", { fg = "#a6e3a1" })
      vim.api.nvim_set_hl(0, "MarkviewHeading5", { bg = "#2E3D51", fg = "#74c7ec" })
      vim.api.nvim_set_hl(0, "MarkviewHeading5Label", { fg = "#74c7ec" })
      vim.api.nvim_set_hl(0, "MarkviewHeading6", { bg = "#393B54", fg = "#b4befe" })
      vim.api.nvim_set_hl(0, "MarkviewHeading6Label", { fg = "#b4befe" })
      require("markview").setup {
        headings = {
          heading_1 = {
            sign_hl = "MarkviewHeadin1Label",
            hl = "MarkviewHeadin1",
          },
          heading_2 = {
            sign_hl = "MarkviewHeading2Label",
            hl = "MarkviewHeading2",
          },
          heading_3 = {
            sign_hl = "MarkviewHeading3Label",
            hl = "MarkviewHeading3",
          },
          heading_4 = {
            sign_hl = "MarkviewHeading4Label",
            hl = "MarkviewHeading4",
          },
          heading_5 = {
            sign_hl = "MarkviewHeading5Label",
            hl = "MarkviewHeading5",
          },
          heading_6 = {
            sign_hl = "MarkviewHeading6Label",
            hl = "MarkviewHeading6",
          },
        },
   }
```
