### ISSUE TITLE
Some list items aren't displayed correctly when padding is disabled

### ISSUE THREAD

**Issue by kamack38** [OXY2DEV/markview.nvim#89]
**Describe the bug**

**Are you using a distro?**
Yes, NvChad

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document. And type:
```md
- first
    - sss
    - sdfsdfs
- second
```
3. Remove padding by disabling it in the config:
```lua
        list_items = {
          marker_minus = {
            add_padding = false,
             text = "",
          },
```

**Expected behavior**
The second list item should be displayed as ` sss`

**Actual behavior**
![image](https://github.com/user-attachments/assets/c9ecaeba-0ee4-49f5-abd9-e4b039b815f7)

**Neovim version**
0.10.1

**Additional context**
This happens on every item which is the first one in the new indent.

**Comment by OXY2DEV** [comment]
That's just lists work in markdown.

List items can't simply skip over indent levels(2 spaces are considered a level).

If you do that treesitter will consider every after the previous indent level to be a marker. You can run `:InspectTree` and see that the size of the marker is larger than all the other items.

This is not a bug.

**Comment by kamack38** [comment]
so then why does this work with padding enabled?

**Comment by OXY2DEV** [comment]
> so then why does this work with padding enabled?

Because in that case you allow the plugin to mess with the text.

Try to put your cursor on the markers. You can't because everything before the text is replaced with virtual text.

You can't do that while the padding is disabled since it will cause the list item to be snapped to the actual level(in this shifting the text by 2 columns to the left).
