### ISSUE TITLE
This entirely breaksNeorg

### ISSUE THREAD

**Issue by tungstengmd** [OXY2DEV/markview.nvim#91]
**Describe the bug**
It doesn't do anything to markdown files and Norg files aren't set to ft=norg for some odd reason?

**Are you using a distro?**
Idk if [this](https://github.com/Neko-Vim/NekoVim) counts?

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document.
3.  Open a Norg file.
4.  Whoop-de-doo it doesn't work.

**Expected behavior**
Both work in harmony.

**Actual behavior**
They actually don't work and have caused a markup war where they both lose and have no highlighting?

**Screenshots**
![image](https://github.com/user-attachments/assets/20f3b143-bf5b-4da7-9e57-67a35c5359d4)
![image](https://github.com/user-attachments/assets/d766f30e-a5cc-4208-8ac7-1ef6c3d3195f)

**Neovim version**
0.10.0

**Additional context**
I also have Neorg.

**Comment by tungstengmd** [comment]
wait a sec there's something else wrong

**Comment by esn89** [comment]
@tungstengmd what was the fix you have for this?

**Comment by tungstengmd** [comment]
check your plugin list, it seems vim-polyglot isn't friendly to norgs

**Comment by esn89** [comment]
I don't have vim-polyglot installed though.

Do we need it?  Looking at it, https://github.com/sheerun/vim-polyglot?tab=readme-ov-file#language-packs

It doesn't even cover the norg files.

**Comment by tungstengmd** [comment]
look i don't know why but after removing it, it ended up fixing my norgs
it might be because it's a vim plugin and not a neovim one
might be worth checking ur plugins for that
