### ISSUE TITLE
[Question]: How to disable tree-sitter conceals in hybrid modes?

### ISSUE THREAD

**Issue by niksingh710** [OXY2DEV/markview.nvim#92]
Creating this to ask Ques.
As Discussion tab is not available.

![](https://github.com/OXY2DEV/markview.nvim/raw/images/Main/html_showcase.gif)

As in this preview, the current line is not concealed, how to get that behavior?

**Comment by OXY2DEV** [comment]
You need to set the `concealcursor` option(it's not done by default since the value will change based on your use case).

For the demo I used.
```lua
{
  modes = { "n", "c" },
  hybrid_modes = { "n" },

  callbacks = {
    on_enable = function (_, win)
      vim.wo[win].conceallevel = 2;
      -- This will prevent Tree-sitter concealment being disabled on the cmdline mode
      vim.wo[win].concealcursor = "c";
    end
  }
}
```

**Comment by niksingh710** [comment]
https://github.com/user-attachments/assets/b7101197-cf1b-4e2a-b0c6-2e6c125eac70

Facing this odd behavior.
If I go I insert mode, then every thing goes unconcealed.

**Comment by OXY2DEV** [comment]
> 2024-08-08-18-13-53.mp4 
> Facing this odd behavior. If I go I insert mode, then every thing goes unconcealed.

This is bug. I am almost done fixing it.

**Comment by jmwright-wavefin** [comment]
I'm also facing this problem.  As seen below, you can't clearly see the text while in normal mode.

<img width="465" height="140" alt="Image" src="https://github.com/user-attachments/assets/67f079c7-116a-435b-9a79-aedaa6bc316a" />

Once I got into insert mode, it works as expected.

<img width="458" height="159" alt="Image" src="https://github.com/user-attachments/assets/90e3288d-9d34-4c60-8956-09c60d9add46" />

Here's my config. I have some extra config for Markview to play nice with CodeCompanion. I have `markdown` and `markdown_inline` installed for Treesitter.

```lua
{
    "OXY2DEV/markview.nvim",
    lazy = false,
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-lua/plenary.nvim",
    },
    opts = function()
      local function conceal_tag(icon, hl_group)
        return {
          on_node = { hl_group = hl_group },
          on_closing_tag = { conceal = "" },
          on_opening_tag = {
            conceal = "",
            virt_text_pos = "inline",
            virt_text = { { icon .. " ", hl_group } },
          },
        }
      end

      return {
        markdown = {
          hybrid_modes = { "n", "i" },
        },
        html = {
          container_elements = {
            ["^buf$"] = conceal_tag("", "CodeCompanionChatVariable"),
            ["^file$"] = conceal_tag("", "CodeCompanionChatVariable"),
            ["^help$"] = conceal_tag("󰘥", "CodeCompanionChatVariable"),
            ["^image$"] = conceal_tag("", "CodeCompanionChatVariable"),
            ["^symbols$"] = conceal_tag("", "CodeCompanionChatVariable"),
            ["^url$"] = conceal_tag("󰖟", "CodeCompanionChatVariable"),
            ["^var$"] = conceal_tag("", "CodeCompanionChatVariable"),
            ["^tool$"] = conceal_tag("", "CodeCompanionChatTool"),
            ["^user_prompt$"] = conceal_tag("", "CodeCompanionChatTool"),
            ["^group$"] = conceal_tag("", "CodeCompanionChatToolGroup"),
          },
        },
      }
    end,
  }
```

Here's the output of `:checkhealth markview`. It seems fine. The symbols it prints I'm able to see.

```
💻 Neovim: ~
- ✅ OK Version: `0.11.3`

📂 Runtime path: ~
- ✅ OK Runtime: `nvim-treesitter` isn't loaded before `markview.nvim`.
- NOTE: If you have changed the directory name of `nvim-treesitter` or `markview.nvim`, the result will be inaccurate!

💡 Parsers: ~
- ✅ OK `nvim-treesitter/nvim-treesitter` found.
- ✅ OK ` html` parser was found.
- ✅ OK ` typst` parser was found.
- ✅ OK `󰍔 markdown_inline` parser was found.
- ✅ OK ` latex` parser was found.
- ✅ OK `󰬠 yaml` parser was found.
- ✅ OK `󰍔 markdown` parser was found.

✨ Icon providers: ~
- ✅ OK `nvim-tree/nvim-web-devicons` found.
- `echasnovski/mini.icons` not found.

🚧 Configuration: ~
- ✅ OK No errors found!

...
```

Also, doing `:Markview Toggle` makes the problem go away.

**Comment by OXY2DEV** [comment]
@jmwright-wavefin you have `render-markdown` enabled, disable it first.

Also, it should be,

```lua
preview = {
  hybrid_modes = { "n" }
}
```
