### ISSUE TITLE
[Feature Request] Option to disable signcolumn icons globally

### ISSUE THREAD

**Issue by carlosflorencio** [OXY2DEV/markview.nvim#95]
Hi,

Could we add an option to disable the gutter icons globally?
<img width="76" alt="image" src="https://github.com/user-attachments/assets/5b31127f-fe90-4dd8-a89e-9dbfef23006d">

It would make the window cleaner and less distracting.

Thanks for the plugin!

**Comment by OXY2DEV** [comment]
There already is.

```lua
headings = {
  heading_1 = { sign = "" },
  heading_2 = { sign = "" }
}
```
