### ISSUE TITLE
Markview patches `gx` which does not work for me on win11 for urls

### ISSUE THREAD

**Issue by GitMurf** [OXY2DEV/markview.nvim#97]
**Describe the bug**
It looks like the plugin patches the native `gx` keymap (as seen here #43). But it breaks gx for me. I am on Windows so don't know if that is the problem.

I have fixed it by "patching the patch" ;-) by removing the keymap patch this plugin adds using: `vim.api.nvim_buf_del_keymap(0, 'n', 'gx')`.

**Are you using a distro?**
No

**Neovim version**
0.10.0

**Additional context**
I am on Windows 11

**Comment by GitMurf** [comment]
@OXY2DEV this does not appear to have fixed the issue. Links in this format `[]()` do work now fine but regular "naked" links do not still. See below:

```
This will work: [espn](https://www.espn.com) but this same "naked link" will not: https://www.espn.com without `[]()` format.
```

**Comment by OXY2DEV** [comment]
It should work like normal now.

**Comment by GitMurf** [comment]
Thanks @OXY2DEV for getting on it so fast! All seems to be working nicely now :-)
