### ISSUE TITLE
Recommend a config setup where `n` / `i` modes work as usual but other modes like `v` / `V` "disable" Markview (showing raw markdown)

### ISSUE THREAD

**Issue by GitMurf** [OXY2DEV/markview.nvim#98]
**Describe the bug**
When doing visual selection (v / V) I would like to have just the raw markdown with all the Markview stuff disabled / cleared. And then when switching back to n/i Markview works as normal.

I tried things like the on mode change callback but could not successfully get a consistent workflow going for it. It seems disabling the plugin and/or clearing the rendered stuff is difficult to manage the state properly to get it to work.

**Are you using a distro?**
No

**Expected behavior**
Simple config where in v / V visual selection modes I can have just raw markdown and then when exiting visual selection it goes back to normal Markview enabled.

**Neovim version**
0.10.0

**Comment by OXY2DEV** [comment]
That's not the default behavior. Did you set `modes` to something?

**Comment by GitMurf** [comment]
> That's not the default behavior. Did you set `modes` to something?

What do you mean that is not the default behavior? Are you saying that the default should work like I want it to where v / V visual selection just show the raw markdown and remove all the markview stuff?

**Comment by OXY2DEV** [comment]
> > That's not the default behavior. Did you set `modes` to something?
> 
> What do you mean that is not the default behavior? Are you saying that the default should work like I want it to where v / V visual selection just show the raw markdown and remove all the markview stuff?

Yes

**Comment by GitMurf** [comment]
It appears the problem occurs with hybrid mode. Here is my simple config I am testing:

```lua
    opts = function()
      return {
        modes = { 'n', 'i' },
        hybrid_modes = { 'n', 'i' },
      }
    end,
```

Here is what the text looks like:

![image](https://github.com/user-attachments/assets/b9ac68fc-88c7-4bfe-a012-1cb7908aac30)

Here is what is looks like in `v` visual selection. You see it tries to show the raw markdown correctly, but the rendered list bullets etc. are not cleared:

![image](https://github.com/user-attachments/assets/0b7e9d98-9b37-4fef-b4f6-2a2ec0de45b8)

**Comment by GitMurf** [comment]
Also I tried it with a minimal config of exactly what you have on the README for a hybrid mode config and same issue:

```lua
require("markview").setup({
    modes = { "n", "no", "c" }, -- Change these modes
                                -- to what you need

    hybrid_modes = { "n" },     -- Uses this feature on
                                -- normal mode

    -- This is nice to have
    callbacks = {
        on_enable = function (_, win)
            vim.wo[win].conceallevel = 2;
            vim.wo[win].concealcursor = "c";
        end
    }
})
```

**Comment by GitMurf** [comment]
@OXY2DEV perfect! it works great now. thanks for getting on it so quickly.
