### ISSUE TITLE
Flashing display during paragraph movement

### ISSUE THREAD

**Issue by ColinKennedy** [OXY2DEV/markview.nvim#99]
**Have you done all of these?**

- [x] I am using the latest version of the plugin.
- [x] I have checked the wiki.
- [x] I have checked previous issues(even closed ones).

**Describe the bug**
When pressing `{` or `}` the markview plugin changes back to ASCII, causing a flash on the screen.

**Neovim version**
```
NVIM v0.11.0-dev-345+g3e6cec0be
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

```bash
nvim --version
# Output
```

**Are you using a distro?**
No

**To Reproduce**
Steps to reproduce the bug:

1. Load this `reproduction.lua file`

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
      "justinmk/vim-ipmotion",
      config = function()
          vim.g.ip_skipfold = 1
      end,
      keys = {
          { "{", desc = "Go to the previous paragraph including whitespace." },
          { "}", desc = "Go to the next paragraph including whitespace." },
      },
  },
  {
      "OXY2DEV/markview.nvim",
      config = true,
      lazy = false,      -- Recommended

      dependencies = {
          "nvim-treesitter/nvim-treesitter",

          "nvim-tree/nvim-web-devicons"
      }
  },
  {
      "nvim-treesitter/nvim-treesitter",
      build = ":TSUpdate",
      config = function()
        require("nvim-treesitter.configs").setup {
            ensure_installed = {
                "html",
                "markdown",
            }
        }
      end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

2.  Open a `markdown` document.

```md
## Requires
- lazy.nvim requires git 2.27+ so that it can used the --filter=blob:none
    - Reference: https://stackoverflow.com/a/51411174
    - Install on CentOS 7 with: https://computingforgeeks.com/install-git-2-on-centos-7/
- Requires jedi-language-server to be installed (for null-ls)
- For debugging [debugpy](https://pypi.org/project/debugpy)
- Requires [fd](https://github.com/sharkdp/fd), for searching folder with :FzfCd / <leader>cD

## Optional Requires
- Anything that `:checkhealth` recommends
- [fswatch](https://github.com/emcrisostomo/fswatch), for better LSP file change performance
    - Reference: https://github.com/neovim/neovim/pull/27347


## Mappings
### Workspace switching
1. mode
2. mapping
3. description
```

Move around with `}` and `{` keys

**Expected behavior**
No flashing

**Actual behavior**
The windows flashes as you move. I enabled `hybrid_modes = { "n" },` so that the flashing will stop though it isn't my preferred mode.

I'm guessing the reason for the flash is because markview seems to disable its extmarks when the user goes into command-line mode, which I think `vim-ipmotion` has to do in order to call its vimscript paragraph function. So the bug outlined here I think would happen with basically any mapping that calls out to vim / lua.

Edit: I also got the flashing to stop by adding `modes = { "n", "no", "c" },` to the configuration

**Recording**
(Warning: Flashing colors)

https://github.com/user-attachments/assets/fa68143d-f38a-4128-85f5-5e864d1aa739

**Comment by OXY2DEV** [comment]
Not really much I can do about it since keymaps are supposed to use `<cmd>` to run commands instead of directly using `:`(this introduces similar visual bugs in plugins using `vim.ui_attach()`).

**Comment by ColinKennedy** [comment]
I wouldn't know exactly how but https://github.com/MeanderingProgrammer/render-markdown.nvim manages this without any particular changes on my side.

https://github.com/user-attachments/assets/3412cfab-2b3b-4f1a-aac3-4be8a2aaa7d3

**Comment by OXY2DEV** [comment]
Because that plugin lacks the entire feature.

**Comment by ColinKennedy** [comment]
If the flashing occurs due to a sort of "auto-toggle" that this plugin implements then I can see a route forward.

The cause of the flashing is due to rapid inputs to `<cmd>`. If this plugin adds a (small interval) [debounce](https://gist.github.com/runiq/31aa5c4bf00f8e0843cd267880117201) to whatever is handling the display toggling then multiple, rapid `<cmd>` calls will not cause flashing but interactive command calls like when a user manually types out `:%s/foo/bar/g` will still display the underlying ASCII text as intended. What do you think?

**Comment by MeanderingProgrammer** [comment]
> Because that plugin lacks the ability to run on any mode

My plugin can in fact run in any and all modes, this is incorrect
